### ISSUE TITLE
adiff with equal start/end timestamp does not select changes with that timestamp

### ISSUE THREAD

**Issue by nrenner** [drolbr/Overpass-API#113]
E.g. [adiff:"2014-06-25T23:46:35Z","2014-06-25T23:46:35Z"](http://overpass-api.de/api/interpreter?data=[adiff:"2014-06-25T23:46:35Z","2014-06-25T23:46:35Z"];%28node%28bbox%29;way%28bbox%29;relation%28bbox%29;%29;out meta geom%28bbox%29;&bbox=9.544943,47.7589664,9.5453575,47.7594645) does not match changes with `timestamp="2014-06-25T23:46:35Z"`. Don't know if this is by design or what the right thing to do is here, but I would expect this query to return the changes.

Subtracting one second from the start date [does work](http://overpass-api.de/api/interpreter?data=[adiff:"2014-06-25T23:46:34Z","2014-06-25T23:46:35Z"];%28node%28bbox%29;way%28bbox%29;relation%28bbox%29;%29;out meta geom%28bbox%29;&bbox=9.544943,47.7589664,9.5453575,47.7594645).

Example use-case is querying for ([changeset 23168078](http://www.openstreetmap.org/api/0.6/changeset/23168078/download)) with created_at/closed_at from [changeset xml](http://www.openstreetmap.org/api/0.6/changeset/23168078) as time range.

**Comment by drolbr** [comment]
The diff call is intended to be the same as a direct diff between the queries for both timestamps. Hence, a diff call with equal timestamps is expected to be empty.
