### ISSUE TITLE
using existing database

### ISSUE THREAD

**Issue by Dmitry1987** [drolbr/Overpass-API#144]
Hello! 
I am trying to install this API to use together with Nominatim searcher and mapnik renderer.
tried to find settings like "db_name, db_user, db_pass" or similar, to connect to existing OSM database I have installed with both mapnik and nominatim, but there are no settings like this anywhere :( 

I wonder if it is possible at all, or this API needs it's own unique structure database?  can I connect it somehow to nominatim db?  or do I need to go through import process again, and make a separate db from fresh osm files, using overpass api import tools?

Thank you!

**Comment by billsinc** [comment]
@Dmitry1987 sorry to resurrect and old thread but I too am looking for this solution...did you find one?

**Comment by Dmitry1987** [comment]
No, I didn't, sorry.

**Comment by mmd-osm** [comment]
These days you can use compression for Overpass API. For a full planet including meta data (but without previous OSM object versions), that's about 130 GB.

However, as stated earlier, you *cannot* connect to any other DB.
