### ISSUE TITLE
Generic "object" primitive

### ISSUE THREAD

**Issue by sanderd17** [drolbr/Overpass-API#150]
I sometimes find myself writing queries like these:

``` C
(
  node["shop"="bakery"]({{bbox}});
  way["shop"="bakery"]({{bbox}});
  relation["shop"="bakery"]({{bbox}});
);
out center;
```

So I'm just interested in a certain POI, and I don't care how it's represented in OSM.
This is a bit redundant to write. If you want to edit one selecting tag (f.e. search for butchers instead), you need to edit it three times.

As such, it would be handy to have an "object" primitive that's just the union between all other primitives with the same selection. The query above could be simplified to

``` C
object["shop"="bakery"]({{bbox}});
out center;
```

It's just a bit of syntactic sugar that makes writing queries easier. It doesn't give extra features, but could make many queries look nicer.

**Comment by rentrop** [comment]
+1 This SO Question also points out the problem/repetitiveness:
http://stackoverflow.com/questions/41388724/overpass-does-not-find-all-cinemas-overpass-api-documentation/

**Comment by mmd-osm** [comment]
Release 0.7.55 will provide the following syntax variant:

```C
nwr["shop"="bakery"]({{bbox}});
out center;
```

This issue can be closed now.
