### ISSUE TITLE
Timeout on simple way->node query

### ISSUE THREAD

**Issue by plepe** [drolbr/Overpass-API#151]
The following query works fine:
```
[out:json];way(4681923)->.a;(node(w.a)[highway];);out meta qt geom;
```

This one produces a timeout:
```
[out:json];way(4681923)->.a;(node(w.a)[highway=crossing];);out meta qt geom;
```

The only difference is the "=crossing" condition. I guess, this is a bug ...

I'm using overpass-api.de/api/ and a local installation. Both show the same behaviour.

**Comment by mmd-osm** [comment]
@plepe : if you're happy with this approach and your issue is solved, would you mind closing this ticket? Thank you.

**Comment by plepe** [comment]
Yes, I'm happy with the approach. On the other hand I'm not convinced, that should be assumed to resolve this issue? Maybe Overpass should convert all selectors internally to regexp?

**Comment by mmd-osm** [comment]
Converting everything to regex is not a good idea, as it has quite some performance impact.

Here's another recommended approach for your issue. If forces a certain processing sequence: first determine the nodes and based on the very small list of nodes, do the filtering on highway=crossing. This tip was given by Roland at some other occasion (don't remember where it was).

```C
way(4681923);
node(w);
node._[highway=crossing];
out meta;
```

**Comment by drolbr** [comment]
It has been fixed in the meanwhile.
