### ISSUE TITLE
Consistency checks for dispatcher/update process

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#155]
Following the [emergency rollback in November](https://lists.openstreetmap.org/pipermail/talk/2014-November/071366.html) and issue #152, I'm creating this new issue to collect some ideas to prevent possible data corruption by server administration mistakes.

- [ ] Dispatcher: don't allow `--area` in conjunction with `--meta` or `--attic` in dispatcher_server.cc

```C++
  if (areas && meta)
  {
    cout<<"\"--areas\" can't be used in conjunction with \"--meta\".\n";
    return 0;
  }

  if (areas && attic)
  {
    cout<<"\"--areas\" can't be used in conjunction with \"--attic\".\n";
    return 0;
  }
```
- [ ] check that only one update process is running
- [ ] don't allow dispatcher to run without --meta / --attic if corresponding files already exist in the database directory - NB: this check might be tricky in case of --attic
- [ ] don't allow update_database to run in non-transactional mode, if dispatcher is running
- [ ] don't allow update_from_dir to run in non-transactional model, if dispatcher is running
- [ ] warn, if osm3s_query is used along with `--db-dir` and dispatcher is handling this db dir.

For the last three points I'm thinking about some checks for existing osm3s_v0.7.... files in the target directory (or possibly /run/shm/osm3s* files?).

Rationale: if the dispatcher is handling a db dir, all changes need to go through the dispatcher as well.

**Comment by drolbr** [comment]
> check that only one update process is running

This is already done.

The other four checks have been added in 2084f7b164232f7d83b81575debdbd81dd960dff .
