### ISSUE TITLE
Overpass API with Lua support

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#172]
Having the [long term development ideas](https://wiki.openstreetmap.org/wiki/Overpass_API/development) in mind, I want to bring up the idea to incorporate a Lua based sandbox into Overpass API. This sandbox is to run untrusted Lua code as part of an Overpass QL/XML Query, i.e. directly operate as a filter or statement. It should be possible to access different inputsets with all nodes/ways/relations/areas including tags and meta data and also with the option to manipulate some of this data (especially tags). Also, it would be cool to expose io, so that the Lua function could generate some custom response based on some input data- if that's acceptable from a security pov.

I also thought about Javascript, but this seemed a bit too heavy to me, although it is much more commonly used and many more libraries are available. At least there are other projects in the OSM space offering Lua support today (e.g. OSRM and osm2pgsql), so there's at least some mind share in the OSM community. There's even a JIT compiler available, although an OSRM ticket reports only 10-20% speed up.

Lua is rather lightweight and can be easily embedded in C++. Kai Krüger did a first prototype for osm2pgsql in just about 10 days with the ability to rewrite tags, etc. In OSRM, Lua is used for [routing rule customization](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua).

A lot of the following ideas would be in scope for such an enhancement. Due to the very generic nature many other use cases should be possible as well, e.g. numerous QA related checks.

* Backing renderers

    * Coarse Coordinates 
    * Filter, add, rewrite Tags   (#49)

* Fun with numbers (#78)

    * Length calculator 
    * Sorting 
    * Select by Route 

*    Multiple sources (probably not easily possible)

    * Engine to mix sources 
    * Blending rules 
    * Enhance Changesets 

Syntax example:

```C
area(xyz)->.boundaryarea;
( 
  node(area.boundaryarea)["addr:housenumber"];
  way(area.boundaryarea)["addr:housenumber"](lua:some_lua_filter);>;
);
lua(some_lua_function);
out meta;

{{lua

function some_lua_function
  for v in vector.nodes do
    node_function(v)
  end
end

function some_lua_filter
...only even numbers and buildings with at least xyz m²
end

}}
```

If this all makes sense, the most difficult part is probably to define a suitable way to expose current Overpass API C++ to Lua, keeping abstraction, performance and memory consumption in mind.

**Comment by jotpe** [comment]
Great idea and cool example! 
Depending on the programming skills or complexity of lua code, this could decreasy easly server cpu performance. Not afraid of?
