### ISSUE TITLE
CSV output: issues with Excel

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#175]
See http://www.technologyblog.de/2014/12/thailands-tankstellen-excel/

> Da sich zumindest mein Excel etwas komisch anstellt die thailändischen Schriftzeichen korrekt anzuzeigen wenn ich die csv-Datei direkt öffne wandle ich zunächst die Kodierung in UTF-8 mit BOM um. Ich verwende dazu Notepad++, das geht aber auch mit jedem anderen Editor der das unterstützt.

Beim Testen mit LibreOffice sind bisher keine Probleme mit dem Zeichensatz aufgetreten. Es scheint aber so zu sein, dass zumindest für Excel zusätzlich ein BOM für UTF-8 (\uFEFF) benötigt wird.

Damit verbunden schlage ich vor, den Parameter csv-headerline in eine komma-separierte Liste "csv options" umzufunktionieren. Dadurch sollten die Parameter insgesamt besser lesbar sein und gleichzeitig zukünftige Erweiterungen ermöglichen. Die Reihenfolge der "csv options" soll keine Rolle mehr spielen. Das csv-Trennzeichen bleibt wie bisher der dritte Parameter (aus Semikolon-Sicht betrachtet).

**Bisher:**
 `[out:csv( fieldname_1 [,fieldname_n ...] [; csv-headerline [; csv-separator-character ] ] )]`

**Neu:**
`[out:csv( fieldname_1 [,fieldname_n ...] [; (comma-separated list of csv options) [; csv-separator-character ] ] )]`

csv-options:
- `with_headerline`         <--- vormals "yes"
- `no_headerline`           <---- vormals "no"
- `with_bom`
- `no_bom`

`yes` und `no` sollen nur noch unterstützt werden, wenn keine anderen csv-Optionen angegeben werden (Rückwärtskompatibilität), sonst Fehlermeldung.

Ebenfalls müsste geklärt werden, ob für Excel im Content-type zusätzlich noch ein Charset=utf-8 aufgenommen werden sollte ([code](https://github.com/drolbr/Overpass-API/blob/c987176fa0f28eb603562ab5c533f8f7ad70982c/src/overpass_api/frontend/web_output.cc#L288)).

**Comment by jotpe** [comment]
I like your csv options. Its more flexible and more nice. But I like even more the syntax of the PostgreSQL [COPY statement](http://www.postgresql.org/docs/9.2/static/sql-copy.html). With this you can collect all csv parameter into one set.

```
[out:csv ( [fieldname_1] [, ...] ] ) [ [ with ] ( option [, ...] ) ]
```

where *option* can be one of:

``` 
DELIMITER 'delimiter_character'
HEADER [ boolean ]
QUOTE 'quote_character'
ESCAPE 'escape_character'
FORCE_QUOTE { ( column_name [, ...] ) | * }
BOM [ boolean ]
```

If not specified it would prefer this default values.
DELIMITER should be changed from `\t` to `,` by default. Only single byte character.
HEADER should true by default.
QUOTE should be `"` by default. Only single byte character.
ESCAPE should be quote option by default.
FORCE_QUOTE should be empty by default.
BOM should be false by default.

**Comment by mmd-osm** [comment]
That looks great as well, as it's also a quite comprehensive list of features we want to support in the end.

However, I don't really know, if the tokenizer is able to deal with this format that easily. I picked the comma separated list as it's known to work without issue. Also, we somehow need to make sure that the extended format remains backwards compatible with what we have right now.

Maybe Roland (@drolbr) could provide some insight on what the best option to enhance the current format might be.

**Comment by jotpe** [comment]
The csv options are still a comma separated list, while FORCE_QUOTE would be an inner comma separated list. I think reading the values is not the problem. Maybe error handlig.

> Also, we somehow need to make sure that the extended format remains backwards compatible with what we have right now.

We discuss already a new syntax, which leads automatically incompatibility. Hasn't the csv feature still an experimental status?

**Comment by drolbr** [comment]
The presented extension is anyway backwards compatible: If no "with" is present then all options remain on the default.

However, I have stated on purpose that we have to sort things like quotation marks, escaping and also potentially number formats. It is a perfectly legitimately goal to get compatible to both Libreoffice and Excel.

One thing to keep in mind: I'm currently reworking the programming interface for the output to make future output formats simpler to implement. I've commited a non-working preview in the out_csv_finetuning branch. So it could make sense to defer the implementation for some weeks until this new interface gets operational.
