### ISSUE TITLE
Attic vs. redaction design issue

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#176]
Please compare [node history](http://www.openstreetmap.org/node/3213017427/history) vs. [attic result](http://overpass-turbo.eu/s/6O1)

Minutely updates only contain the deletion information, but I don't know where to get redaction details from. Might need some input from @pnorman on the expected behavior.

**Comment by pnorman** [comment]
The (`redact`)[http://wiki.openstreetmap.org/wiki/API_v0.6#Redaction:_PUT_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2F.23id.2F.23version.2Fredact.3Fredaction.3D.23redaction_id] API call does not result in anything that is picked up by osmosis-generated replication diffs - i.e. insufficient information is published to keep a full history planet up to date.

**Comment by mmd-osm** [comment]
Closing this issue, as there's no upstream support to handle redaction, except for the main db.
