### ISSUE TITLE
Edge Values with " " or opening_hours & CSV

### ISSUE THREAD

**Issue by TheFive** [drolbr/Overpass-API#178]
(english see below).
Hallo, 

ich habe gerade versucht den CSV Modus in meinem kleinen Projekt "OSM Count" zu promoten. Dabei wollte ich opening_hours mit ausgeben.
Opening_hours haben das Problem, das sie sowohl , als auch ; beinhalten. Texte wie Opening Hours setzt man dann am besten in Anführungszeichen. (Ich nutze gerne ; als Trenner, da das bei EXCEL in deutsch default ist, und damit die CSV direkt in EXCEL geöffnet werden können, ohne über den Import Dialog zu gehen).

Christoph 
edit: Ich hab gerade auch eine Öffnungszeit mit einem TAB drin gefunden, d.h. Öffnungszeiten kann man nicht mit dem CSV Import rausbekommen.

---

In short: i have tried to use opening_hours in the out:csv mode. opening_hours is a field, that may contain semicolon, comma & tab, so all standard CSV separater can found in the field. So it is necessary to edge the values with "".

**Comment by jotpe** [comment]
TheFive is right.
Without right quoting, there is always the possibility for corrupt csv.

I think implementation of 2.5-2.7 from [RFC 4180](http://www.ietf.org/rfc/rfc4180.txt) is needed.

**Comment by mmd-osm** [comment]
fyi: We discussed this point already in https://github.com/drolbr/Overpass-API/pull/135 (see first post), but it didn't make it into 0.7.51 unfortunately. It's still a TODO along with two other csv related issues (#175 and https://github.com/drolbr/Overpass-API/pull/145)

Please also check http://blog.openstreetmap.de/blog/2014/11/overpass-api-version-51-mit-holprigem-start/ :

> Der Modus ist aber noch nicht abschließend fertig: CSV ist kein so klar umrissenes Dateiformat wie XML oder JSON. Die Tücke liegt dabei in Detailfragen, z. B. welche Zeichen auf welche Weise escaped werden sollen, ob man Anführungszeichen um Einträge mit Leerzeichen oder gleich für alle Einträge braucht. Oder auch nur, wie Fehlermeldungen eingebaut werden sollen. Daher bitte ich um Rückmeldung, am besten als Issues auf Github, oder als Mail an talk@ oder talk-de@.

**Comment by TheFive** [comment]
Hi, sorry, was not intended at criticism.
I am aware, that not everything can be implemented in the first version. As i did not found the issue here, i felt i had to add for completeness.

**Comment by mmd-osm** [comment]
No worries, that's exactly what Roland asked for. I didn't know, if you read the blog post before, so I quoted it here to provide some more context... yes, there are still some rough edges :)

**Comment by TheFive** [comment]
Hi, i have read the blogpost, it makes me aware of the new export format.
I did not bing "escape sequence" and "" together :-). I have skipped opening_hours in my webapp and implemented a overpass-turbo shortcut to the CSV without.
So i hope that with one of the next "Wochenaufgaben" your format is promoted a little bit more.

I love easy accessible OpenStreetMap data.

**Comment by drolbr** [comment]
Implemented in bf184de58533017f77692fb01399824463eac503
The change will get to the main server with the next release.
