### ISSUE TITLE
Augmented diff status returns id with new line

### ISSUE THREAD

**Issue by thomersch** [drolbr/Overpass-API#179]
When polling http://overpass-api.de/api/augmented_diff_status, I will receive something like `1225883\n`. In my opinion there shouldn't be a new line at the end of the response, because that way I have to do a unnecessary string operation before being able to pass the request back to Overpass.

**Comment by mmd-osm** [comment]
[Other apps](https://github.com/osmlab/osm-stream/blob/gh-pages/osmstream.js#L30) seem to work without any special treatment, e.g. `parseInt` will simply ignore the additional line break. Can you add some more detail where this presumably causes some real issue?

btw: It would be interesting to have some feedback from @rurseekatze, if this was in any way relevant for openrailwaymap.org.

**Comment by thomersch** [comment]
Well, the case you're demonstrating is a piece of JavaScript code, which is very far away from the protocol layer and in addition to that doesn't care too much about correctness.

When using a strict language - like in my case Go - the trailing `\n` is part of the answer, so I have to perform an additional `strings.Trim(idStr, "\n")` to get rid of it. If I don't strip the new line and simply pass it back to Overpass, it will return even an invalid response, so I would say that this is a real existing issue there.

**Comment by rurseekatze** [comment]
No, this problem was not relevant for me and OpenRailwayMap. I just had problems caused by the data itself that was returned in the adiff requests (order of objects, missing objects, data format that did not fit to my requirements). See #139 for more details.

**Comment by mmd-osm** [comment]
@thomersch : we're revisiting old issues to see if they are still relevant. After almost two years, this issue was not important or urgent enough to be considered, and basically nobody else ever complained about the line break. Also, there's no documentation to specify, that the call should only return numbers.

May I suggest to close this issue, as you already have a work around available. Thanks.

**Comment by thomersch** [comment]
I still wonder why it's there, but apparently nowadays everyone is doing JavaScript, so I guess I will keep "working around".

**Comment by mmd-osm** [comment]
I think it is just a side effect of using `echo` without `-n` in bash scripts: https://github.com/drolbr/Overpass-API/blob/minor_issues/src/cgi-bin/augmented_diff_status#L49
