### ISSUE TITLE
Main Overpass API Is Down

### ISSUE THREAD

**Issue by hallahan** [drolbr/Overpass-API#181]
It looks like `http://overpass-api.de/api/interpreter` is not working:

Is this the right place to submit something like this?

![screenshot 2015-01-14 10 16 33](https://cloud.githubusercontent.com/assets/556367/5744569/c0aaf10e-9bd6-11e4-8cf8-b73c7806ae5f.png)

**Comment by hallahan** [comment]
Never mind - I see what I did. It's weird that it didn't warn me that the query would take a very long time. I should have set the bbox for the school query.

**Comment by drolbr** [comment]
Thank you for the screenshot.

The interpreter is operating normally. Line 11 of the query reads

    node[amenity=school]"

Please note that there is no bounding box provided. This means: give me all schools around the world.

Most likely using

    node[amenity=school]({{bbox}})

instead will solve your problem. Actually the error message is a protective measure: The server aborts the query before it used excessive resources.

**Comment by hallahan** [comment]
Brilliant work btw. I love you it was straight C++ and CGI!!!!!
