### ISSUE TITLE
too much optimizing when converting Overpass QL to compact

### ISSUE THREAD

**Issue by malenki** [drolbr/Overpass-API#183]
[This query](http://overpass-turbo.eu/s/76P) returns 46 weirs. When exporting it to compact, a ".rivers" gets dropped and the result are only 9 weirs.

(sanderd17 helped creating this query and debugging it)
(I was pointed to report the issue here instead of [here](https://github.com/tyrasd/overpass-turbo/issues/142).)

**Comment by mmd-osm** [comment]
It also affects a number of different conversions (XML -> compact, XML -> QL, QL -> compact,..), as well as `<`, `<<`, `>` and `>>`. Reason is that the `from` parameter is not considered in those cases.

statement_dump.cc needs to be adapted.

**Comment by mmd-osm** [comment]
Fix is available in #184.

**Comment by malenki** [comment]
Thanks for the quick fix.

**Comment by mmd-osm** [comment]
Please note that it might take some time until Roland merges this fix and it is available up on overpass-api.de.

**Comment by mmd-osm** [comment]
You can retest the fix now by temporarily changing the server in overpass turbo settings to: http://dev.overpass-api.de/api_mmd/ and then exporting your initial query to compact ql again.

Please report back any issues you might come across.

**Comment by drolbr** [comment]
Fixed in a23af2763386a238595c45929a49d454ef6e9bb3 by merge of https://github.com/drolbr/Overpass-API/pull/184
