### ISSUE TITLE
field selection for other formats than CSV

### ISSUE THREAD

**Issue by TheFive** [drolbr/Overpass-API#186]
Now there are two ways, to control the size of Overpass output.

a) out XXX;
b) a field list in CSV Type

I suggest to allow a field list for JSON and other formats too, just to reduce the size of the result of an Overpass Query.
e.g.: If you are interested in the administrative borders of Germany (name, border type, german regional / gemeindeschluessel) but not more, the result set has felt 3 times bigger size than necessary.

**Comment by TheFive** [comment]
see Rolands comment here:
https://github.com/drolbr/Overpass-API/issues/187#issuecomment-71016968

**Comment by pyrog** [comment]
I have a similar issue, I need a field list for JSON to **control the size of Overpass output**, but also to **improve readability of data**. on the map.

I don't need derived fields (e.g. complete addresses), just few "simples" fields (e.g. name, operator…).

As I don't use QGIS and I want to provide these data on a map for "newbies", is it possible to reopen this issue ?

**Comment by mmd-osm** [comment]
You can use the `convert` statement for this purpose, please see the overpass ql documentation on the osm wiki.

**Comment by pyrog** [comment]
I read the [english](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#The_statement_convert) and [french](https://wiki.openstreetmap.org/wiki/FR:Overpass_API/Overpass_QL#Conversion_.28convert.29) documentation, but I don't understand.
How to use it ? Do you have an example ?

**Comment by mmd-osm** [comment]
Sure: http://dev.overpass-api.de/blog/compound_values.html#suffix
