### ISSUE TITLE
derived fields (e.g. complete addresses)

### ISSUE THREAD

**Issue by TheFive** [drolbr/Overpass-API#187]
One of my overpass vision is, that overpass reduces the barrier in using OpenStreetMap data.
But OpenStreetMap data is complex and not easy to interpret.

There is always the discussion in redundancy of tags, that has a "georelation" like "is in".

Is it possible, to enrich a result set with something like

"derive addr:street from building around"
"derive addr:plz from relation type PLZ"
...

2 samples for usage:
a) my osm count (quality assurance motivation tool :-)) (can be found on github)
To create the relation pharmacy and border, I send out several overpass questions (for each boundary i am interested in, one) this uses 6 hours to do every query. Downloading all german pharmacies just takes about 2 or 3 minutes in ONE query.

b) List of Pharmacies with addresses.
Building an easy way to present enriched data to the enduser will show not only the mappers that OpenStreetMap is a database, and not simply a map.

I assume a pharmacy finder will take about 1-2 days to implement with a nice frontend. If you want to present addresses, and you have to implement the "is in" relation by your own, you'll need much more knowledge and may be not start the project.

Christoph

**Comment by mmd-osm** [comment]
Thank you for your proposal. 

I want to comment briefly on the postal code part. This could be achieved today already, albeit the result cannot be consumed without a bit of post processing. The following query will first return a node, followed by another line with postal code area details. A non-csv based approach was also discussed [here](https://help.openstreetmap.org/questions/35976/add-reverse-geocoding-information-to-the-overpass-resulting-set) before.

I don't know exactly how much time that takes, but it should be faster than 6 hours.


```C
[timeout:3600]
[out:csv(::type, ::id, ::lat, ::lot, "addr:housenumber", "addr:street", "addr:postcode", "addr:city", name, postal_code)]
[bbox:{{bbox}}];

node[amenity=pharmacy]->.pharmacies;
foreach.pharmacies(
  out;
  is_in;
  area._[boundary=postal_code];
  out;   // for non-csv mode: change to "out ids;" 
);  
/* uncomment for non-csv mode:
.pharmacies is_in;
area._[boundary=postal_code];
out;
*/


// see: http://wiki.openstreetmap.org/wiki/DE:Overpass_API/Beispielsammlung#Geocoding_Informationen_zu_POIs_hinzuf.C3.BCgen
```

**Comment by mmd-osm** [comment]
Nominatim already provides everything what you're looking for - today. By simply putting those osm ids into a nominatim query, postal codes, streets and house numbers are automatically derived:

Example:

`http://nominatim.openstreetmap.org/reverse?osm_type=N&osm_id=270051254&format=xml`

It's a pity that their [usage policy](http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy) it so restrictive. Anyhow, you should get in touch and find out what is permissible usage for your scenario.

I leave it up to Roland to comment on how/if Overpass API will support this use case in the future.

**Comment by TheFive** [comment]
Hi MMD Hi Roland,

I did not ask because my actual topics in development. For me it is more a "strategic" Question, wether operpass (as THE OpenStreetMap Query Language) will support reducing redundancy in data or not. 

The discussions, wether to map redundant data or not, will stop immediate for every data support overpass is offering. (similar to the influence editor and renderer developer have on mapping) :-)

And it is my wish to ease the deriving fields mechanism to the end user. If you want to build a small front end for (let my stay at this example) pharmacies in a JavaScript app. Asking Overpass for the pharmacies, and looking in nominatim for existence of further adress information is not very simple, compared to a single overpass query.

It could be solved, by building this redundancy when importing the OSM Data to overpass, but this implies, that Overpass gets Information about our tagging schemes, or a language extension, which allows to get easy information about "close" objects, or objects a given object "is in".

Christoph

**Comment by drolbr** [comment]
Hi Christoph,

these are tow different issues.

First, in the long run, Overpass API will offer various ways of data reduction. Coordinate centers are already available. And the CSV format allows to show only certain tags. Simplification has been mentioned, and other options are as reasonable.

Second, to properly identify and stich adresses is a very difficult task. Think of cases where the item in question is a node, and a relation on the enclosing building is the only hint for address data, poentially contraditing the closest entrance. And for the textual representation: this varies between countries. For example, some countries have the house number before the street, others the other way round.

Therefore, a high quality software should invoke Nominatim at some point, because Nomiatim is designed to handle such cases properly.

**Comment by TheFive** [comment]
Hi Roland,

typically the faction of mapper, that would like to reduce redundancy in OpenStreetMap, tells that PLZ, Town is easy to catch from the data, and it is the same for including buildings, but may be they do not develop a query language and do not oversee all possible complications.

I think i have to play with the for_each statement and with nominatim.

Christoph

**Comment by mmd-osm** [comment]
@TheFive : I tested the following query on my local instance:  

```C
[timeout:3600];

area[name="Deutschland"]->.a;

( node(area.a)[amenity=pharmacy]; 
  way(area.a)[amenity=pharmacy];
 rel(area.a)[amenity=pharmacy];
)->.pharmacies;

foreach.pharmacies(
  out center;
  is_in;
  area._
  [boundary=administrative]
  ["de:amtlicher_gemeindeschluessel"];
  out ids;   
);  

.pharmacies is_in;
area._[boundary=administrative]
  ["de:amtlicher_gemeindeschluessel"];
out;
```

It will print a pharmacy following by all area ids this pharmacy is in. The file concludes with a list of all areas with full detail.

```XML
  <node id="3090862473" lat="49.2388708" lon="6.7019792">
    <tag k="addr:housenumber" v="1"/>
    <tag k="addr:street" v="Gluckstraße"/>
    <tag k="amenity" v="pharmacy"/>
    <tag k="name" v="Vitalikum Apotheke"/>
  </node>
  <area id="3600062372"/>
  <area id="3600062466"/>
  <area id="3601184560"/>
```

Total runtime: 20 minutes for Germany. This is probably somewhat higher on overpass-api.de due to a higher overall CPU load.

**Comment by mmd-osm** [comment]
@TheFive : I tested the following query on my local instance:  

```C
[timeout:3600];

area[name="Deutschland"]->.a;

( node(area.a)[amenity=pharmacy]; 
  way(area.a)[amenity=pharmacy];
 rel(area.a)[amenity=pharmacy];
)->.pharmacies;

foreach.pharmacies(
  out center;
  >;
  is_in;
  area._
  [boundary=administrative]
  ["de:amtlicher_gemeindeschluessel"];
  out ids;   
);  

.pharmacies is_in;
area._[boundary=administrative]
  ["de:amtlicher_gemeindeschluessel"];
out;
```

It will print a pharmacy following by all area ids this pharmacy is in. The file concludes with a list of all areas with full detail.

```XML
  <node id="3090862473" lat="49.2388708" lon="6.7019792">
    <tag k="addr:housenumber" v="1"/>
    <tag k="addr:street" v="Gluckstraße"/>
    <tag k="amenity" v="pharmacy"/>
    <tag k="name" v="Vitalikum Apotheke"/>
  </node>
  <area id="3600062372"/>
  <area id="3600062466"/>
  <area id="3601184560"/>
```

Total runtime: about 30 minutes for Germany. This is probably somewhat higher on overpass-api.de due to a higher overall CPU load.

**Comment by TheFive** [comment]
Thanks, i will try this out (after the Wochenaufgabe #osmwa0607).
It looks like doing a query per "Gemeinde" is the easiest, but not fastet method.

**Comment by TheFive** [comment]
Hi mmd,

I have implemented a download and JSON Store in my postgres db of this "area" enriched OSM Data. 
a download for AT needs about an hour. With the given timeout, Germany is not completed.

What is better for the overpass server, fragmenting the query in 16 subqueries (per "state"), or increasing the timeout ?

Christoph

**Comment by TheFive** [comment]
Hi MMD,

I have tried this approach with AT and DE. In AT i get the full results in 1 hour.
For DE 1:40 min i get 1978 pharmacies, increasing time to 5 hours results in 9.000 Pharmacies (roundabout), so a total download i expect to take 10 hours (18.000 pharmacies).
i can try this, i was never thrown out from the system, only my time limit limits my queries.


a) is it a problem, that i run queries that need 10 hours ?
(it limits the amount of Data i can use for the Wochenaufgaben, i am keen to support e.g. firestations, to let this "go on").

b) Do you see an option to move the loop around, and loop over a list of "gemeindeschluessel" and collecting the pharmacies for this ? 

c) as i still have the idea (and the sourcecode) to run nominatim for each changed POI, i can try to use that information for counting, but than i have to build the country structure not by the gemeindeschluessel, but by admin_level and mapping from admin_level to nominatim names. OK, this idea is offtopic in an overpass github.

Christoph

**Comment by mmd-osm** [comment]
Hi,

somehow your answer slipped under the radar as the question is already "closed". Maybe you want to reopen it?

I can answer part b) yes that should be possible by using the following query:

```
[timeout:3600];

rel[boundary=administrative]
  ["de:amtlicher_gemeindeschluessel"]->.gem;


foreach.gem(
  out tags;
  map_to_area -> .a;
  ( node(area.a)[amenity=pharmacy]; 
    way(area.a)[amenity=pharmacy];
    rel(area.a)[amenity=pharmacy]; );
  out tags center;
);  
```

**Comment by TheFive** [comment]
Thanks for your answer.

**Comment by mmd-osm** [comment]
Maybe you've noticed already: Nominatim now supports queries by OSM object id with up to 50 objects in one call. See http://wiki.openstreetmap.org/wiki/Nominatim#Address_lookup for details.

**Comment by TheFive** [comment]
thanks for the information.
