### ISSUE TITLE
shrink relation ways to bbox

### ISSUE THREAD

**Issue by jotpe** [drolbr/Overpass-API#191]
How to remove all ways from a big relation, which haven't got any nodes in my bbox? I want to reduce the data for faster rendering. 

```c
[bbox:{{bbox}}];
rel["name:de"="Israel National Trail"];
```
This will receive all ways.
I tried to something like this, buts it return 300 times more data. I strongly guess, it is wrong.

```c
[bbox:{{bbox}}];
rel["name:de"="Israel National Trail"];

(._;>)->.a;
foreach.a(
 way.a ({{bbox}})->.b;
.b out;
);
```

A kind of #171 would help too ;-)

**Comment by mmd-osm** [comment]
Hi!

can you try this one? I think that's the shortest result you can get atm:

```C
[out:json];
rel["name:de"="Israel National Trail"];
way(r)({{bbox}});
out ids geom;  // or: out tags geom;
```

**Comment by drolbr** [comment]
Thank you mmd for answering the question. It is exactly "all way that are members of the given relation and inside the bounding box".

**Comment by jotpe** [comment]
supi
