### ISSUE TITLE
developer communication channel ?

### ISSUE THREAD

**Issue by sletuffe** [drolbr/Overpass-API#198]
Hi,
This might not be the best place, but is there some mailing list/forum/wiki/here is fine prefered place to discuss possible evolutions of the Overpass software between developers ?

And if not, should we set one ?

imho dev@lists.openstreetmap.org is too generic, osm's wiki isn't quite practical and the github issues tracking system covers a too wide range of propositions (even with github tags) where we encounter more "I'd like that..." than "I'm going to do that, is this a good idea ?".

Things that could come up with on such a communication channel could be :
* Discussing this https://github.com/drolbr/Overpass-API/pull/160 beforehand and going to another direction.
* Things Iike "I'd like to add an 'out gpx;' option to export result as gpx but I am wondering if it is best suited inside overpass or if I should rather do an external for that

note: please don't answer to those 2 points, I'd be more than happy to re-send on the proper channel

**Comment by mmd-osm** [comment]
Just a  few comments from my side:

* There's a [long term roadmap](http://wiki.openstreetmap.org/wiki/Overpass_API/development) out there, but not any kind of dedicated dev discussion site that I'm aware of, except for GitHub maybe. If I'm stuck, I send an email to Roland. 

* Roland is currently applying for a FOSSGIS grant to get two new servers (prod + dev), replacing the current production server (yeah!). This should make it much easier to attract a larger developer community.

https://www.fossgis.de/wiki/F%C3%B6rderantr%C3%A4ge/Overpass_API_2015 (Google Translation looks good enough).

* Also, the code is currently undergoing some larger restructuring in the output section (see https://github.com/drolbr/Overpass-API/commits/out_csv_finetuning). Adding another output option like `out gpx;` will be much easier in the future. I would highly recommend to wait until that refactoring is done.

**Comment by drolbr** [comment]
Hi,

> imho dev@lists.openstreetmap.org <mailto:dev@lists.openstreetmap.org> is
> too generic, osm's wiki isn't quite practical and the github issues
> tracking system covers a too wide range of propositions (even with
> github tags) where we encounter more "I'd like that..." than "I'm going
> to do that, is this a good idea ?".

I would highly appreciate such a channel, preferably a mailing list. 
Would you volunteer to run such a list?

Best regards,

Roland

**Comment by sletuffe** [comment]
As far as I'm concerned, a list would be fine as well.
As to run this list, I'd be happy to do that but really like to avoid any system setup if possible.

It just so happen ;-) that I'm the http://listes.openstreetmap.fr sympa administrator. However, I could understand that using the domain of the french chapter doesn't fit well with an international project.
But, frankly, I'm a bit scared by the "reactivity" of the sys admin of the openstreetmap.org as they have quite other serious matter to manage : My last bug report about archives's cache pages never got an answer.
<troll>and mailman is ugly</troll>

But if that matters, I'll try that on the @lists.openstreetmap.org sub-domain, no problems.
--
sly

**Comment by drolbr** [comment]
Hi Sylvain,

> It just so happen ;-) that I'm the http://listes.openstreetmap.fr sympa
> administrator.

Thank you. This is actaully what I have hoped for.

 > However, I could understand that using the domain of the
> french chapter doesn't fit well with an international project.

I'm perfectly fine with this. The service itself is offered from a ".de" 
domain, and the Overpass Turbo frontend is run from a ".eu" domain and 
in fact located in South Tyrol. So it is anyway spread about Europe.

Roland

**Comment by sletuffe** [comment]
Any preferred wish for it's address/name ?
overpass-dev@listes.openstreetmap.fr
overpass@listes.openstreetmap.fr
dev-overpass@listes.openstreetmap.fr

That name will end in square brackets in the subjets like [overpass]

**Comment by drolbr** [comment]
Thank you for organising the list.

> Any preferred wish for it's address/name ?

> overpass@listes.openstreetmap.fr

I would prefer this one. It is the most straightforward.

Roland

**Comment by sletuffe** [comment]
Then here we go !
Anyone can subscribe with a web browser:
http://listes.openstreetmap.fr/wws/subscribe/overpass
(Seams like defaut interface language is french but can be turned to english on the bottom left)

or by email by sending an email to 
sympa@listes.openstreetmap.fr 
with subject :
subscribe overpass

Sympa's full documentation is here :
http://listes.openstreetmap.fr/wws/help/introduction

I'll turn both of you list admins as soon as subscribed if you want to

**Comment by sletuffe** [comment]
Closed because done.
