### ISSUE TITLE
Attic data cutoff

### ISSUE THREAD

**Issue by sanderd17** [drolbr/Overpass-API#199]
Hi, I wondered if there's an attic data cutoff.

On IRC, we tried to fetch the complete first version of the Nasser lake (http://api.openstreetmap.org/api/0.6/relation/280282/1), but we only got empty datasets.  We tried with a minimal query like
```C
[date:"2009-11-01T00:00:00Z"];
rel(280282);
out;
```
However, when we adapted the date, we did get data

```[date:"2012-06-02T13:24:35Z"];``` was the first timestamp that give us any data, while a second earlier (```[date:"2012-06-02T13:24:34Z"];```) didn't work. 

Is it normal that there's no data available before June 2012? And is this documented somewhere? Other old objects seem to also have a cutoff data, though for the ones I tested, it's a different one.

**Comment by mmd-osm** [comment]
Hi,

yes, there's a cutoff day. Attic database creation starts with the first ODbL compliant planet after the license change, which gives us some day in September 2012 as a starting point. Any previous versions, which were existing before that day won't be available in a query. I don't know if this is documented somewhere, if so it might be in German. 

I will add a link here, once I find something suitable.
