### ISSUE TITLE
Object version in JSON output

### ISSUE THREAD

**Issue by Skippern** [drolbr/Overpass-API#200]
I cannot find the object versions in the JSON output, have this been overlooked? As it is now I need to download the objects I need to manipulate in XML format, something that complicates the task quite a lot

**Comment by mmd-osm** [comment]
Hi,

most likely, you didn't use  `out meta;` in your query. If that doesn't solve the issue, could you please post your query somewhere (e.g. link to overpass turbo)?

**Comment by Skippern** [comment]
I tried to add `out meta;` but still got the same result:
```json
{
    "id": 24602288, 
    "type": "way", 
    "tags": {"highway": "cycleway", "bridge": "yes"}, 
    "nodes": [267437148, 267436749]
},
```

The search query is: `way(area:'+str(cityID)+')["highway"]; out body; >; out meta; out skel qt;`, in python with an overpass-wrapper

**Comment by mmd-osm** [comment]
Ok, there seems to be some issue with that overpass wrapper. Try to remove the final `out skel qt;`  in your query - that might cause some confusion in the wrapper code, as the nodes will appear both with/without meta data now. If you can't influence the Overpass QL code created by the wrapper, I would suggest to create a new issue there.

Do you need to have version information for both nodes & ways? In that case you would use a query like:

```C
[out:json];
(way(area:3601184820)["highway"];>;);
out meta;
```
This query will return all highway-tagged ways in area 3601184820 (=area for relation 1184820, as an example) along with all its nodes in JSON format, including meta data.

Try it in overpass turbo: http://overpass-turbo.eu/s/7Uy

**Comment by Skippern** [comment]
Finally managed it after playing a little around with the `;`

`(way(area:'+str(cityID)+')["highway"]; >; ); out meta `

Damn syntax :D
