### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by drolbr** [drolbr/Overpass-API#202]
The following query uses more than 16 GB of RAM, but isn't stopped by the resource control:

[timeout:3600](way['man_made'='pier']['area'='no']%28around:3660000,36.1,140.7%29;);
out center;

The resource control should instead abort the query once it takes more than 512 MB of RAM.

**Comment by mmd-osm** [comment]
I wonder if introducing `setrlimit` would be a good idea to also control runaway queries on OS level. We could define soft limits both memory/cpu consumption but would need to gracefully handle signals (which is tricky).

**Comment by drolbr** [comment]
This is caught now by the general resource limit.
