### ISSUE TITLE
Provide File Size With GET Requests

### ISSUE THREAD

**Issue by hallahan** [drolbr/Overpass-API#204]
I'm working on an Android application that will be getting data from the Overpass API. I'd like to provide the user with a progress bar to show how far we are into a download. For some reason I'm not getting the actual bytes total from the GET Request:

https://github.com/hallahan/DownloadManagerTest/blob/master/app/src/main/java/com/spatialdev/downloadmanagertest/MainActivity.java#L145

This is for OpenMapKit:

https://github.com/AmericanRedCross/OpenMapKit

Anyway, I'm wondering if there is a technical reason we aren't provided with the response size? Downloading from other URLs does give me the file size.

**Comment by hallahan** [comment]
To take out the Android context, I'm not getting the percentage of the download when using wget.

When downloading from Overpass, I see this:

```
interpreter?data=(way[buildin     [                                    <=>             ]  53.28M  2.08MB/s   in 36s
```

But when I'm doing a GET elsewhere, I see this:

```
QGIS-2.8.1-1.dmg.1             15%[=======>                                            ]  27.49M  2.66MB/s   eta 53s 
```

Is this a technical limitation where Overpass is sending back data while still computing the complete file?

**Comment by mmd-osm** [comment]
Hi there,

that's a [known limitation](http://wiki.openstreetmap.org/wiki/Overpass_API#Limitations). The reasons are similar to why the HTTP header can't provide an error code in any case, see [this comment](https://github.com/drolbr/Overpass-API/issues/94#issuecomment-44868471).

**Comment by hallahan** [comment]
Ah, exactly what I was thinking. Thank you for those answers, I appreciate your insight.
