### ISSUE TITLE
no diff in foreach

### ISSUE THREAD

**Issue by jotpe** [drolbr/Overpass-API#205]
When i declare a diff parameter from date a to date b, it looks like that this will be ignored while iterating over a set of areas.

``` c
[diff:"2015-04-03T00:00:00Z","2015-04-07T00:00:00Z"];
area[type=boundary]["name:de"~"^(Deutschland|Österreich|Schweiz)$"]; 
foreach(
    node(area)[emergency=siren]; out meta;
);
```

http://overpass-turbo.eu/s/8Dq

**Comment by drolbr** [comment]
Fixed in 4501972758a752632117975335e1f0d3e936a035: Now shows an error message.
