### ISSUE TITLE
Overpass result_set in overpass answer

### ISSUE THREAD

**Issue by kiselev-dv** [drolbr/Overpass-API#206]
Is it possible to add all result_sets which were assigned to elements into query answer?

Lets say, I have a query like this:

```
[out:json];
(
  (
    rel["type"="route"]["route"="bus"]({{bbox}});
    rel(br)["type"="route_master"];
  )->.rels;
  (
    .rels;
     node(r.rels:"stop");
  )->.stops;
  (
    .rels;
     node(r.rels:"platform");
  )->.platforms;
  (
    .rels;
    way(r.rels:"");
    >;
  )->.ways;
);
out body qt;
```

with four outsets specified:

```
rels stops platforms ways
```

Is it possible to get them all in results?

in other words I want to get results like this:

``` javascript
{
  "type": "node",
  "id": 694437882,
  "lat": 50.8394243,
  "lon": 39.0681387,
  "_result_sets": ["rels", "platforms"]
}

{
  "type": "node",
  "id": 694437882,
  "lat": 50.8394243,
  "lon": 39.0681387,
  "_result_sets": ["rels", "stops"]
}
```

Or get result sets specifyed in any other form. Maybe with query metadata. Like this way:

``` javascript
"version": 0.6,
"generator": "Overpass API",
"osm3s": {
    "timestamp_osm_base": "2015-04-13T07:44:02Z",
    "copyright": "..."
},
"result_sets": {
    "rels": [{"type":"relation", "id":"12345"}, {"type":"node", "id":"694437882"}],
    "stops": [ {"type":"node", "id":"694437882"}]
},
"elements":[
   //elements returned in old plain way
]
```

It will allows to send one query instead of three and get data elements separated by types.

**Comment by mmd-osm** [comment]
Could you elaborate a bit, what is original problem you're trying to solve with this approach. You're already proposing a solution, but we really want to understand your requirement first. Maybe there's a completely different way already available:

Let's take a look at your second syntax proposal as an example. This looks very much like the problem described in #236 and I also believe this could also be tackled by using  `out count;` without any further changes to Overpass API.

**Comment by drolbr** [comment]
The following variant will insert a headline before each set:

```
[out:json];
make headline set="rels";
out;
(
  rel["type"="route"]["route"="bus"]({{bbox}});
  rel(br)["type"="route_master"];
)->.rels;
.rels out;
make headline set="stops";
out;
(
  .rels;
   node(r.rels:"stop");
)->.stops;
.stops out;
make headline set="platforms";
out;
(
  .rels;
   node(r.rels:"platform");
)->.platforms;
.platforms out;
make headline set="ways";
out;
(
  .rels;
  way(r.rels:"");
  >;
)->.ways;
out;
```

More is possible with the convert command.
