### ISSUE TITLE
area["type"="boundary"]["int_name"="Deutschland"]: ERROR 504: Gateway Time-out.

### ISSUE THREAD

**Issue by ypid** [drolbr/Overpass-API#207]
Hi,

i have a question about the following query:

    [date:"2015-04-19T00:00:00"][out:json][timeout:4000];
    area["type"="boundary"]["int_name"="Deutschland"];
    foreach(
        node(area)["opening_hours"]->.t; .t out tags;
        way(area)["opening_hours"]->.t; .t out tags;
    );

I have run this query a few times now using wget and it never completed, instead I get the following error message:

    http://overpass-api.de/api/interpreter:
    2015-04-17 21:59:29 ERROR 504: Gateway Time-out.

    real	15m17.075s
    user	0m0.004s
    sys	0m0.000s

Related to:

* https://github.com/ypid/opening_hours-statistics
* https://github.com/ypid/opening_hours.js/blob/fc33b18ebf4f18e8f98c30831efe9f433becb90d/Makefile#L194
* https://blog.openstreetmap.de/blog/2015/04/wochenaufgabe-oeffnungszeiten/

Any idea?

**Comment by mmd-osm** [comment]
This topic is now being picked up in another ticket #220. I suggest to close this one.

**Comment by ypid** [comment]
OK.
