### ISSUE TITLE
Website points at bad release URL

### ISSUE THREAD

**Issue by karlwettin** [drolbr/Overpass-API#211]
<http://www.overpass-api.de/no_frills.html> and several other webpages points at:

http://overpass-api.de/misc/osm-3s_v0.7.3.tar.gz

This is a 404. You should change this. I also recommend a redirect rule on your to httpd to catch /misc/* and send it on to the github release directory!

**Comment by mmd-osm** [comment]
As Roland is currently in the middle of moving the old server to the new one, this is somewhat expected. You can find those files here at this time: http://prev.overpass-api.de/misc/

I would recommend to check back when the server move is completed. By then, the links you mentioned should be functioning again.

**Comment by drolbr** [comment]
Fixed in commit 77030fdeb7af390c2cdc85646c05cd98d567b44f
