### ISSUE TITLE
autoconf fails building on Ubuntu 15.04

### ISSUE THREAD

**Issue by karlwettin** [drolbr/Overpass-API#212]
Tried to build from source on Ubuntu 15.04. Autoconf reported a bunch of unknown macros. Bypassed using autoreconf --install, but this caused import of osm.bz2 to coredump at end of parsing file. 

So I suppose there are dependencies available by default in 14.04 that are not available by default in 15.04, or something like that. I simply gave up, headed for 14.04 and ran using an official distribution instead.

**Comment by mmd-osm** [comment]
Your message is somewhat unclear to me. Can you please provide some more information about:

* which exact version did you try to compile?
* what messages did you get from autoreconf?
* did you see any issues during `configure` or `make`?
* which osm.bz2 did you try to import?
* which exact error message did you get during the import?

**Comment by mmd-osm** [comment]
Ubuntu 15.04 reached [end of life on February 4, 2016](https://wiki.ubuntu.com/Releases). Please try a more recent release and report back if the issue still persists.

**Comment by drolbr** [comment]
We should check whether the autoconf works on Ubuntu 16.04 and corresponding Debian or other linuxes.

**Comment by karlwettin** [comment]
We could provide you with VMs for this in the KVM hypervisor at openstreetmap.se, if you want. Might however be quite a bit of work to set it up so they automated would clone, build, report errors and so on. I personally don't have the time but could set up the VMs of anyone else want to do the rest. : ) Let me know.

**Comment by mmd-osm** [comment]
I'd suggest to use travis ci for this purpose. They also offer Ubuntu 16.04.

Here's a build on an earlier version: https://travis-ci.org/mmd-osm/Overpass-API/builds/150989390

**Comment by mmd-osm** [comment]
I use Ubuntu 16.04 locally without issues, and run some automated tests for my test branch via travis ci: https://travis-ci.org/mmd-osm/Overpass-API/builds/153053852

Automated testing could also be set up for Ubuntu 16.04 each time we commit something to the repo, although that would require some docker workarounds (see https://github.com/geerlingguy/ansible-role-mysql/commit/e5a02eda82a2411544cac3d213a83d807a1464a7)

**Comment by drolbr** [comment]
The software has built successfully on Ubuntu 16.04.

However, it is necessary to compile with -O2 instead of -O3. It's a compiler thing, looks like bad optimization assumptions about pointers, but I haven't investigated further than to check that the source code is correct.

I'll keep this bug open as a reminder to update the documentation.

**Comment by drolbr** [comment]
Documentation updated in 77030fdeb7af390c2cdc85646c05cd98d567b44f

**Comment by mmd-osm** [comment]
> However, it is necessary to compile with -O2 instead of -O3.

What kind of issue did you run into? I'm running 16.04 & `-O3` without issues here.
