### ISSUE TITLE
`kill_my_queries` not killing my queries

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#214]
Trying to stop a long running query using `/api/kill_my_queries`, but the `kill` command doesn't have any impact, the query just continues as before till its end. This can be verified by checking `top` or by simply running `kill_my_queries` again: it would claim to have killed the same query again (and again). 
Am I missing something here?

* I tend to replace `kill $PID` by a `kill -9 $PID`. Would that be safe?
* `dispatcher --query_token` seems to return only a single PID. How would we get an exhaustive list of all processes run by an IP address (assuming the dispatcher will allow more than one query, which is not the case on overpass-api.de) and kill them all at once.
* Should we add a signal handler in Overpass API for SIGTERM and maybe also SIGPIPE to shut down the process?

**Comment by mmd-osm** [comment]
See http://article.gmane.org/gmane.comp.gis.openstreetmap.overpass/274

**Comment by drolbr** [comment]
In commit 9e60cd030f87732bfb0f9c1a9ca5279976c31bce this has been repaired. It now kills all queries of a user at once. In addition, there is a new API call, /status, that shows the server's bookkeeping of your queries.
