### ISSUE TITLE
Suppress "-lrt" switch when linking on OSX

### ISSUE THREAD

**Issue by malcolmh** [drolbr/Overpass-API#216]
Causes make to fail. Re-running the g++ command with this switch deleted works OK.

**Comment by mmd-osm** [comment]
Relevant changes: https://github.com/mmd-osm/Overpass-API/commit/bd091c081f3777dc42e4ad892e513afec03a8b09

autoscan, aclocal, autoheader, libtoolize, automake --add-missing, autoconf ,... needs to be re-run.

**Comment by CamonZ** [comment]
Any chance of getting this fixed?

@mmd-osm I arrived here through [this question](https://help.openstreetmap.org/questions/47209/install-overpass-on-mac-os-x) on OSM, I noticed the branch you linked for [this build](https://travis-ci.org/mmd-osm/Overpass-API/builds/97856095) is no longer on your repo. 

Did you merge the fixes on your `master` branch?

**Comment by mmd-osm** [comment]
> Did you merge the fixes on your master branch?

No, my master branch corresponds to @drolbr's master branch, my current consolidated version is in branch test755.However, as I don't have a Mac for testing, those changes to configure.ac and Makefile.am didn't go anywhere. You need to apply them manually.

**Comment by drolbr** [comment]
Fixed in ade51fafd2735b92eb90f1075a219edab58e4944

**Comment by mmd-osm** [comment]
(actual patch in: 147c3dcdd8914530a29252152706215814884955)
