### ISSUE TITLE
Overpass + OSM2World: OSM Version 0.6 requires a version attribute 

### ISSUE THREAD

**Issue by kekscom** [drolbr/Overpass-API#218]
Hi Roland,
Seems that OSM2World can't convert Overpass results as OSM 0.6 is expecting a version attribute on nodes. At least it seems to be in the specs.
I'm pinging @tordanik as well, as you both probably might discuss a solution.

**Comment by TheFive** [comment]
I have not tested it, but out meta
should solve your problem.

http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL

Christoph

**Comment by kekscom** [comment]
Thanks, that worked.
Without meta, the response might not be valid OSM 0.6, but for reduced response size I'm all for the current aproach.
Solved by RTFM.
