### ISSUE TITLE
Query by object version number

### ISSUE THREAD

**Issue by mvexel** [drolbr/Overpass-API#219]
It is already possible to [query by user / uid](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_user_.28user.2C_uid.29), so querying by version should not be too hard..I hope?

I would want to query 
- by exact version number
- by min / max version number

**Comment by mmd-osm** [comment]
Thanks for the suggestion! I have some follow-up question/comment on it.

Like the user/uid query, querying by exact version number would only return those objects, which *currently* have that version number in question.

Let say, an object currently has version 3 and you query for version 2. In that case the query would NOT return the data from version 2, but instead no result at all. Is this how you intend this to work? That would be quite easy to do, I guess.

In general, the query would always refer to a particular point in time (either current time, or some given time via `[date:xxxx-yy-zz...]`) and always consider the version available at that time for querying.

Can you shed some light on some use cases you have in mind for this query, maybe?

**Comment by mmd-osm** [comment]
Maybe similar? https://github.com/openstreetmap/openstreetmap-website/issues/1067

**Comment by tilmanb** [comment]
> Let's say an object currently has version 3 and you query for version 2. In that case the query would NOT return the data from version 2, but instead no result at all. Is this how you intend this to work? That would be quite easy to do.

Yes, that would be helpful. Call this filter current_version, and usage should be

`way[landuse](current_version:7)({{bbox}});`

to get all landuses in the BBOX that are currently at version 7.

If this is easy to implement, implement it :-) and there will be an abundance of happyness :-)

**Comment by drolbr** [comment]
The first option is now implemented in 46b45ad40ddfca3609aaa419cbef6c1d1963b52a.
This means that you can now filter a set of results for those elements that have a specific version or a specific changeset.

**Comment by maning** [comment]
Is this deployed in overpass turbo already?

**Comment by drolbr** [comment]
Yes, on the dev server: http://overpass-turbo.eu/s/prE

**Comment by mvexel** [comment]
Very cool. The link above does not currently work -- did you decommission that API endpoint?
Do you have visibility on a production release for this?

**Comment by mmd-osm** [comment]
Link is still working here, maybe some noscript blocking issue on your end?

**Comment by mvexel** [comment]
Figured it out, it was a mixed content block from chrome. I have HTTPS everywhere installed so I was automatically redirected to the https site, but the link in the query was of course still http 🦐
