### ISSUE TITLE
Excessive memory usage 2 (around/add_coord)

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#222]
around.cc:add_coord needs some safeguarding to prevent high memory usage. Depending on the query this eats up all available memory before running out of memory.
Test query available in my home dir on dev instance under ~/sample/around_issue

**Comment by matkoniecz** [comment]
http://overpass-turbo.eu/s/ai8 (with large radius) failed after working for a long time, http://overpass-turbo.eu/s/ai9 returned almost immediately (searching entire world). Both queries search for the same tag, not present in data.

In my usecase I am trying to find location of nearest object with match tag set. I am doing it by running queries with increasing radius, till I find at least one object.

**Comment by mmd-osm** [comment]
Thanks! The first query seems to allocate quite a huge amount of memory with noticeable impact on munin stats. 

BTW: Could you please replace the first link by a version *without* auto-run, so that people clicking on the links above don't accidentally execute the query immediately. You could of course stop the query later on, but that doesn't work reliable at the moment and the query keeps on running on the server.

**Comment by matkoniecz** [comment]
> replace the first link by a version without auto-run

Done. 

I was not aware that it has such significant impact. How large radius is starting to cause trouble? In my automated testing of style I may run hundreds of queries each day and limiting to smaller radius would not be a big problem.

I used 100km radius after larger radius values were blocked what was limiting but it was not causing significant trouble. Currently I am using 3600km limit (though in most cases target is found earlier, without reaching limit) and I am worried that it may be inefficient use of resources.

**Comment by mmd-osm** [comment]
Note to self: added `.htaccess` in cgi_bin directory on dev instance with 
```
RLimitMem 4294967296
```

This will kill the `interpreter` binary when hitting the 4GB memory limit.

**Comment by mmd-osm** [comment]
>I was not aware that it has such significant impact. How large radius is starting to cause trouble? 

According to munin the committed memory went up to 50GB, while server only has 32GB physical memory. I would say, that's definitively too much.

I limited the available memory to 4GB/process on the dev instance now, so you can try different queries without affecting the main server too much. Normally, a query would only get 512MB to 1GB. Server endpoint is: `http://dev.overpass-api.de/api_mmd/`

It's hard to give a good recommendation for the current implementation. I tested with Essen and a radius of 1500km, which already hit the 4GB limit. On the main instance, this would still return some data at the expense of even higher memory consumption.

@drolbr : Roland: do you think you can add a memory limit in `.htaccess` on the main instance as well?

**Comment by mmd-osm** [comment]
OS-level resource constraint was added in: https://github.com/drolbr/Overpass-API/commit/260684bdc7270dd38fecdca649c1eefd3b3ef133
