### ISSUE TITLE
Wrong admin regions returned

### ISSUE THREAD

**Issue by thomfre** [drolbr/Overpass-API#228]
When I query the API for info about Bergen, Hordaland, Norway, I get back that it belongs to the state Kebbi in Nigeria. I get the same for Utrecht in The Netherlands. This started happening a few days ago. I tried reporting this in the OSM forums and in the OSM chat, I was told this might be a bug in the Overpass API.

**Comment by mmd-osm** [comment]
Hi there!

could you please also post the query you're trying to execute? Otherwise it
will be very difficult to analyze your issue.

**Comment by thomfre** [comment]
`<osm-script output="json"><coord-query lat="60.3190" lon="5.353333" /><print/></osm-script>`

**Comment by mmd-osm** [comment]
Thanks! I can reproduce this on the main overpass instance, but not on
rambler or my dev instance. One of the incorrectly returned areas was last
changed more than a year ago, i.e. not a temporary kind of inconsistent
relation.

At this point I'd like to ask Roland (@drolbr) to take over, as I'm running
out of ideas.

**Comment by dmitrybitman** [comment]
Hi. I'm having the same issue, this is the test case: http://overpass-turbo.eu/s/bnh Result contains areas such as Mutale Ward 8 and Ntungamo which are in Africa, not in Ukraine. This problem only occurs on overpass-api.de/api/ server.

**Comment by mmd-osm** [comment]
The faulty areas have been created on Wednesday at 7pm:

```XML
<meta osm_base="2015-09-10T16:01:02Z" areas="2015-09-09T19:33:02Z"/>
```

Maybe check back again tomorrow when the areas have been recreated.

**Comment by dmitrybitman** [comment]
Nope. Bad areas are still there:
```xml
  <meta osm_base="2015-09-11T12:11:02Z" areas="2015-09-10T20:34:02Z"/>
  ...
  <area id="3603657767">
    <tag k="admin_level" v="10"/>
    <tag k="boundary" v="administrative"/>
    <tag k="name" v="Mutale Ward 9"/>
    <tag k="ref" v="93402009"/>
    <tag k="type" v="boundary"/>
  </area>
```

**Comment by thomfre** [comment]
The problem is kinda gone now, but now nothing is returned... I guess this was intentional? (to recreate the areas?)

**Comment by mmd-osm** [comment]
Roland is currently rebuilding areas from scratch. Please watch [this space](http://wiki.openstreetmap.org/wiki/Overpass_API/status) for updates.

**Comment by mmd-osm** [comment]
@thomfre: according to the wiki page, the issue seems to be resolved now.

Could you please close this ticket?

Thanks.

**Comment by thomfre** [comment]
Seems to be fixed now :) Thanks!
