### ISSUE TITLE
rules folder missing in tarball archives

### ISSUE THREAD

**Issue by freebird2** [drolbr/Overpass-API#230]
Hey Roland,

first, thanks a lot for this great piece of software. Just a minor issues: in the tarballs the rules folder is missing (https://github.com/drolbr/Overpass-API/tree/master/rules), discovered while trying to reproduce http://wiki.openstreetmap.org/w/index.php?title=Overpass_API/install&section=13#Area_creation

Should be an easy fix :-)
Thanks & cheers
Toby

**Comment by drolbr** [comment]
Fixed in commit baea969fdaf7fd2bad08a06ef9873679116903f6
