### ISSUE TITLE
Weird error message on Overpass Turbo

### ISSUE THREAD

**Issue by k1wiosm** [drolbr/Overpass-API#231]
I keep getting this error message on Overpass Turbo: 

```
An error occured during the execution of the overpass query!

Request rejected. (e.g. server not found, request blocked by browser addon, request redirected, internal server errors, etc.)

Error-Code: error (0)
```

with this query:

```
[out:json][timeout:300][date:"2015-09-01T00:00:00Z"];
{{geocodeArea:USA}}->.searchArea;
(
  node["exit_to"](area.searchArea);
  way["destination"]["highway"="motorway_link"](area.searchArea);
  way["destination"]["highway"="motorway"](area.searchArea);
);
out count;
```

However using dev server it works:

```
{{data:overpass,server=http://dev.overpass-api.de/api_mmd/}}
```

(I first asked this question at https://github.com/tyrasd/overpass-turbo/issues/203 but it seems to be an Overpass API problem)

**Comment by tyrasd** [comment]
This is actually the same bug as described in #220: The server times out internally resulting in a `504 Gateway Timeout` error (which misses the CORS HTTP headers set resulting in the generic error message displayed by overpass turbo).

**Comment by k1wiosm** [comment]
I am not getting this error anymore.

The error that I currently get is this one:

    An error occured during the execution of the overpass query! This is what overpass API returned:
    
    runtime error: Query run out of memory using about 2048 MB of RAM.

And I can fix this using `[maxsize:4294967296]` as described on [the wiki](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Element_limit_.28maxsize.29).

I guess this could be closed?

**Comment by matkoniecz** [comment]
Given that it is duplicate, maybe it should be closed?

**Comment by mmd-osm** [comment]
Yes, please go ahead and close it!
