### ISSUE TITLE
Java-compatible HTTPS certificate for overpass-api.de

### ISSUE THREAD

**Issue by simon04** [drolbr/Overpass-API#233]
Currently, https://overpass-api.de/ uses a StartSSL.com certificate. Unfortunately, its CA is not trusted by Java's keystore. Therefore, https://overpass-api.de/ cannot be accessed from Java applications such as JOSM.

Would it be possible to replace that certificate by another free (as in beer) certificate, e.g., https://www.globalsign.com/ssl/ssl-open-source/?

**Comment by drolbr** [comment]
Basically yes. The problem is: What if now somebody else complains that his software won't accept that CA?

**Comment by mmd-osm** [comment]
There are some scripts out there to automatically add those certificates:  https://github.com/haron/startssl-java

Don't know if linking to such a script would be an option. It's a one time activity - though with some high potential to annoy users :)

**Comment by simon04** [comment]
openstreetmap/operations/issues/55 is related.

**Comment by mmd-osm** [comment]
Update: http://article.gmane.org/gmane.comp.gis.openstreetmap.overpass/232

**Comment by drolbr** [comment]
No further complaints. Hence I assume "Let's encrypt" is a trusted CA for everyone.
