### ISSUE TITLE
User filter ignores global bbox

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#234]
Test case:   http://overpass-turbo.eu/s/bO4

```C
[bbox:{{bbox}}];
node(user:"drolbr");
out geom;
```
Result: >14.000 nodes from all over the world, most of which are outside the bbox.

Expected behavior:  according to the wiki, the global bbox setting can *define a bounding box that is then implicitly added to all queries*. The query should return only nodes in the current bbox.

The following test case look ok, though.  http://overpass-turbo.eu/s/bO5

```C
node(user:"drolbr")({{bbox}});
out geom;
```

**Comment by drolbr** [comment]
Fixed in 013cb2430d739bb08af9862e57c9ababd6757147
