### ISSUE TITLE
allow union on results, symmetrical to difference

### ISSUE THREAD

**Issue by matkoniecz** [drolbr/Overpass-API#235]
http://overpass-turbo.eu/s/bSv from http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_API_by_Example#Find_all_bus_stops_which_are_not_included_in_a_relation works, but after changing set difference to set union query crashes (see http://overpass-turbo.eu/s/bSw).

> ( .all; - ._; );

works as expected

I expected 

> ( .all; + ._; );

to result in set union, but resulted in

> Error: line 13: parse error: Unknown type "+" 

In this query such union may make no sense but there are cases where set union would be useful.

**Comment by mmd-osm** [comment]
The "+" operator you're trying to use is invalid syntax, hence the error message (not crash!) you get as a result.

Please refer to the [documentation](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Union) in the wiki. Solution would be to use `(.all; ._;);` instead.

Would you mind closing this message after reading, as it's not a valid bug report. Thanks.

**Comment by matkoniecz** [comment]
> The "+" operator you're trying to use is invalid syntax

I am aware. I am proposing to allow this syntax.

**Comment by mmd-osm** [comment]
Ah, ok. From your description it was not clear to me that you're proposing a syntax enhancement.

In fact, `+` will never be symmetrical to `-`, as `-` always only allows two statements, i.e. you cannot do something like `(.stmt1; - .stmt2; - .stmt3;);`. On the other hand,  `+` allows you to create the set union based on as many statements as you like.

I don't really see any obvious benefit from this syntax variant, so from my side it's a clear :-1: .
However, Roland is the one to convince...

**Comment by matkoniecz** [comment]
And probably giving a good error message is not worth increased complexity in the parser...

**Comment by mmd-osm** [comment]
@matkoniecz : I think we agree here that's really not worth the effort. Could you please close this issue then, as there's nothing left to do. Thanks.
