### ISSUE TITLE
Annotate per output step

### ISSUE THREAD

**Issue by sanderd17** [drolbr/Overpass-API#236]
I would like to propose a way to annotate outputs from different output commands.

F.e. say you want to compare the number of in a series of municipalities. When you write a query like

``` C
[out:json];

area[postalcode=8840]->.a;
way[amenity=bakery](area.a);
out;

area[postalcode=8800]->.a;
way[amenity=bakery](area.a);
out;
```

The results get concatenated to one list, and you can't check the completeness of the individual municipalities. Either you need to perform individual calls, or you need to do the boundary matching again afterwards.

So I propose the `out annotate` action, as following:

``` C
[out:json];

area[postalcode=8840]->.a;
way[amenity=bakery](area.a);
out annotate "8840";

area[postalcode=8800]->.a;
way[amenity=bakery](area.a);
out annotate "8800";
```

The `annotate` action must always be followed by a quoted string. That string will be added to the different outputted elements as following:

``` JS
...
{
  "type": "way",
  "id": 114659521,
  "nodes": [
    1298263999,
    1298263994,
    1298263945,
    1298263974,
    1298263999
  ],
  "tags": {
    "building": "house",
    "name": "Dessertje",
    "shop": "bakery"
  },
  "annotation":"8840"
},
{
  "type": "way",
  "id": 114659521,
  "nodes": [
    1298263999,
    1298263994,
    1298263945,
    1298263974,
    1298263999
  ],
  "tags": {
    "addr:housenumber":"10",
    "addr:street":"Moststraat",
    "building": "house",
    "name": "Crevits",
    "shop": "bakery"
  },
  "annotation":"8800"
},
...
```

For other outputs, the same sort of annotation could be used: the `::annotation` key for CSV, an `annotation="..."` for XML, etc.

Thanks for considering this.

**Comment by mmd-osm** [comment]
A similar question was recently asked on help osm. I believe this should
also work in your case:
https://help.openstreetmap.org/questions/45530/placeholder-item-in-overpass-api

**Comment by sanderd17** [comment]
Using an ```out count``` is indeed a working hack to split the outputs.

The existance of a hack makes this a low-priority issue IMO, but it would still be nice to be able to not need the hack.

In any case, thanks for the tip.

**Comment by mmd-osm** [comment]
@sanderd17 : With 0.7.54, it's now possible to introduce some artificial separator:

```C
area[postalcode=8840]->.a;
way[amenity=bakery](area.a);
out;

make here_a_new_block_begins;
out;

area[postalcode=8800]->.a;
way[amenity=bakery](area.a);
out;
```

**Comment by drolbr** [comment]
In addition, it is possible to add an extra tag to every element:

```
area[postal_code=8840]->.a;
way[shop=bakery](area.a);
convert way ::=::,::id=id(),is_in_postal_code="8840";
out;

area[postal_code=8800]->.a;
way[shop=bakery](area.a);
convert way ::=::,::id=id(),is_in_postal_code="8800";
out;
```

Currently, this preserves only the tags of the way. If you need to keep also the members then use the above solution with the marker, please.
