### ISSUE TITLE
Idea: add function to sum up spatial length of ways

### ISSUE THREAD

**Issue by saerdnaer** [drolbr/Overpass-API#237]
like the experimental [count](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Counting_of_elements) function but not the number of elements but the spatial length of non-closed ways.

**Comment by drolbr** [comment]
Implemented in 0762e15444e81b58e91f69453e586df788fca26a

Syntax is: `length()` as evaulator. An example:

```
way[name="Wilhelm-Stricker-Weg"];
out geom;
make stats length=sum(length()),section_lengths=set(length());
out;

```

**Comment by tordans** [comment]
In case anyone stumbles upon this.

I was wondering how to connect the list of length values from `section_lengths` to the OSM ways.

Here is my workaround: https://overpass-turbo.eu/s/1buu

```js
[out:json][timeout:25];
(
  way["highway"="service"]({{bbox}});
);
out geom;
make stat total_length=sum(length()),way_id_length=set(type() + ",#" + id() + ",length(m):" + length());
out;
```

Which returns a string that can be processed to get the length per way-id.
```json
{
  "type": "stat",
  "id": 1,
  "tags": {
    "total_length": "58.626",
    "way_id_length": "way,#262073667,length(m):18.509;way,#262073675,length(m):40.117"
  }
}
```

Another way would be to trust in the fact(?) that the order of all values of make-variable(ids, lengths) is the same, so `make test ids=set(id()),lengths=set(length());` could be used to split (by `;`) and match by array index.
   ```
  {
  "type": "test",
  "id": 1,
  "tags": {
    "ids": "262073667;262073675",
    "section_lengths": "18.509;40.117"
  }
  }
   ```



Other thinks I learned:
* It looks like there is no way to add (merge) the `length` output to the elements-object of `type:way`; it is always separate from the OSM elements.
* `stats` can be any string, its just the value for the `"type": "stats"`.
* The variable names can have any value (`length=sum(length())` could be `total_length=…`).
* One can access `tags`-values with `t["highway"]`, but the result will be compacted.
* The way `make` is used above, one can only have on make-call.

**Comment by drolbr** [comment]
General remark: please do not comment on issues that are closed since years. Most likely, nobody will ever read that. Rather feel free to open a new issue for a remark.

For the given problem I suggest

    [out:json];
    way["highway"="service"]({{bbox}});
    convert result ::=::,::geom=geom(),length=length();
    out geom;

The convert statement amends each OSM element with a length tag. The result can be seen on [this Overpass Turbo instance](https://olbricht.nrw/ovt/). The main instance does not support the produced GeoJson.

**Comment by DaveF63** [comment]
> please do not comment on issues that are closed since years. Most likely, nobody will ever read that.

I disagree with this. Given software is updated, an original, accepted answer can often be wrong. Many come to these pages via a google search.

I came to this page via the 'Related Questions' column on the OSM help forum.
