### ISSUE TITLE
Overpass-QL: easier way to find nodes without a specific key

### ISSUE THREAD

**Issue by saerdnaer** [drolbr/Overpass-API#238]
introduce ```node[!name];```  as short version of ```node[name!~"."];```

**Comment by mmd-osm** [comment]
Duplicate of #132

**Comment by saerdnaer** [comment]
Wah. Thats a first. Duplicates for my own issues. Sorry.

**Comment by mmd-osm** [comment]
Maybe add a comment to the other ticket that the current syntax really does
not cut it from a usability pov and why it shouldn't be low prio after all.
