### ISSUE TITLE
Querying time ranges: newer and older

### ISSUE THREAD

**Issue by d3netxer** [drolbr/Overpass-API#243]
It is possible to query meta by using 'newer'  http://wiki.openstreetmap.org/wiki/Overpass_API#Meta_data

Is it possible to query meta within a time range?

**Comment by mmd-osm** [comment]
Did you look at the `changed` filter already? 

http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_date_of_change_.28changed.29

**Comment by drolbr** [comment]
"changed" should do the job.
