### ISSUE TITLE
adiff: incorrect action type (create/modify/delete)

### ISSUE THREAD

**Issue by borazslo** [drolbr/Overpass-API#244]
I am working with different adiff queries. It seems to me that there are problems with create/modify/delete actions. Sometimes it says "create" when the way is only modified (received two new tags).

__Example:__
Query:
````
[timeout:255]
[adiff:"2015-11-18T00:00:00Z","2015-11-25T00:00:00Z"];
(
node["amenity"="place_of_worship"]["religion"="christian"]["denomination"~"catholic"](44.793530904744074,15.57861328125,48.99463598353405,27.0703125);
way["amenity"="place_of_worship"]["religion"="christian"]["denomination"~"catholic"](44.793530904744074,15.57861328125,48.99463598353405,27.0703125);
relation["amenity"="place_of_worship"]["religion"="christian"]["denomination"~"catholic"](44.793530904744074,15.57861328125,48.99463598353405,27.0703125);
);
out body meta;
>;
out meta skel qt;
```

From the result:
```
<action type="create">
  <way id="307677433" version="2" timestamp="2015-11-21T21:42:13Z" changeset="35497759" uid="57628" user="Domcsi">
    <nd ref="3128816182"/>
    <nd ref="3128817864"/>
    <nd ref="3128816224"/>
    <nd ref="3128816180"/>
    <nd ref="3128816204"/>
    <nd ref="3128817854"/>
    <nd ref="3128816211"/>
    <nd ref="3128817860"/>
    <nd ref="3128817850"/>
    <nd ref="3128817855"/>
    <nd ref="3128817871"/>
    <nd ref="3128817877"/>
    <nd ref="3849938088"/>
    <nd ref="3849938089"/>
    <nd ref="3849938091"/>
    <nd ref="3849938090"/>
    <nd ref="3128816182"/>
    <tag k="amenity" v="place_of_worship"/>
    <tag k="building" v="church"/>
    <tag k="denomination" v="roman_catholic"/>
    <tag k="name:hu" v="Szent Miklós püspök templom"/>
    <tag k="religion" v="christian"/>
    <tag k="url:miserend" v="http://miserend.hu/?templom=3551"/>
  </way>
</action>
```

Problem:
[307677433:history](http://www.openstreetmap.org/way/307677433/history) is created 1 year ago. In the last week Domcsi modified it, so it should be labeled as "modify" with the correct "old" and "new" elements.

(I'm developing a light weight comparison tool with Overpass-API:adiff: https://github.com/borazslo/OSM-Overpass-Diff )

**Comment by mmd-osm** [comment]
`create` is correct in this case, as your query asks for `["denomination"~"catholic"]`. In v1, this tag didn't exist yet, so v2 is the first version, where the way comes into existence based on the filter criteria you use. `modify` would be wrong, as there's no previous version of the way, having ` ["amenity"="place_of_worship"]["religion"="christian"]["denomination"~"catholic"]`.

**Comment by borazslo** [comment]
Thank you for your response. So create/modify/delete is not referred to the node/way/relation itself (sonot the node is created/modified/deleted), but it is referred to its place in the results of the query/filter. So create means, that it is new in the result list (but it can be very old). Then modify means, that the item was in v2 and it is in v2 too, but there were changes in tags/nds/member. Finally delete means only that that item is not in the result list anymore. But I does not imply that the item is not exists. Am I right?

p.s.: Can we clarify this in the wiki page for "the next generations"?

**Comment by mmd-osm** [comment]
Let me put it another way: basically the query is executed twice. Once for timestamp t0 (2015-11-18T00:00:00Z in your example) and again for timestamp t1 (2015-11-25T00:00:00Z). Simply put, that gives the following options:

* Case 1: Object exists in t0 and t1 (no changes) -> no output
* Case 2: Object didn't exist in t0, but exists in t1 -> create
* Case 3: Object exists in t0, but no longer in t1 -> delete
* Case 4: Object was modified between t0 and t1 -> modify

Even if there are many changes between t0 and t1, only 1 change is reported.

**Comment by mmd-osm** [comment]
@borazslo : if this answers your question, could you please close this ticket? Thanks.

**Comment by borazslo** [comment]
@mmd-osm : Thank you for your explanation. I added this explanation to the wiki for other users like me. See: http://wiki.openstreetmap.org/wiki/Overpass_API/Augmented_Diffs
(Please feel to correct or complete it.)

**Comment by pierzen** [comment]
See #292 where I reported a similar problem.

I reported an inconsistancy in results for small and large bbox Queries. For a small bbox, the same way id="412947345" where a "damage:" tag is added reports as **modified** while this is reported as **new** for a large bbox.
