### ISSUE TITLE
Data returned outside bounding box

### ISSUE THREAD

**Issue by malcolmh** [drolbr/Overpass-API#249]
A query with a global bounding box often returns data well outside that bounding box. The data always lies on a northeast diagonal and at a distance of hundreds and sometimes thousands of km distant from the BB. An example is attached. The query script was run with arguments: "241 200"

[Archive.zip](https://github.com/drolbr/Overpass-API/files/76153/Archive.zip)

**Comment by mmd-osm** [comment]
Unfortunately, your query doesn't return any data at all here. Can you please post an overpass-turbo.eu share-link instead?

**Comment by malcolmh** [comment]
The query BB is in the Atlantic, so there is no data within the BB. The only data returned is the spurious data, as you will see if you input the OSM file into JOSM & zoom right out.

**Comment by mmd-osm** [comment]
Sorry, still unable to reproduce. Here's the overpass turbo link I used (generated by gen9.sh 241 200, query stored in a file instead of calling osm3s_query): http://overpass-turbo.eu/s/dvo

And here's the result from overpass-api.de

```
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base="2016-01-02T11:11:02Z"/>

  <bounds minlat="36.0313" minlon="-10.5469" maxlat="36.5979" maxlon="-9.84375"/>


</osm>

```

**Comment by malcolmh** [comment]
I am running a local instance, v7.52, built & running on a Mac. I do not see any errors in apply_osc_to_db.log. I have also tried submitting the same query to overpass-api.de & I can confirm that it returns an empty data set. Weird!

**Comment by mmd-osm** [comment]
I already tried to set up an automated test on travis-ci.org for MacOS X: https://github.com/mmd-osm/Overpass-API/tree/test752_macosx and run the test suite in that environment. That should help to identify some potential issues on that platform upfront. 

The relevant steps are outlined in the following .travis.yml file:

https://github.com/mmd-osm/Overpass-API/blob/test752_macosx/.travis.yml

Running the test suite currently fails for some unknown reason (see towards line 823):
https://travis-ci.org/mmd-osm/Overpass-API/builds/99829148

It would be good to get this somehow running. As I don't have a Mac for testing, is this something you could look into, i.e. following all the steps in .travis.yml. You can of course also take a look in the log file to see the exact sequence of events.

That would however require to use the overpass git master version, rather than the one from dev.overpass-api.de/releases.

**Comment by malcolmh** [comment]
OK, I'll give it a try (tomorrow). Can I do this without building a planet DB?

**Comment by mmd-osm** [comment]
Great. Yes, the test suite creates some artificial test data, a planet DB wouldn't be needed in that case.

**Comment by malcolmh** [comment]
Followed the script - here is the output: 
[test.txt.gz](https://github.com/drolbr/Overpass-API/files/76615/test.txt.gz)

**Comment by mmd-osm** [comment]
Thanks a lot for testing the script! The output looks exactly like on the travis ci instance: compiling the binaries looks great, but for some reason the test suite doesn't run - most likely there's some issue with the paths somewhere or the BASEDIR for the tests. 

I need to think a bit how we can track this down further....

Maybe Roland has some idea, why the test suite fails on OS X? @drolbr

**Comment by drolbr** [comment]
I don't understand what the Travis instance does in detail.
The following sequence of commands should let the whole thing run:

```
git clone https://github.com/drolbr/Overpass-API.git
cd Overpass-API/
git checkout minor_issues
cd src
autoreconf
libtoolize 
automake --add-missing
autoreconf
cd ../build/
../src/configure --prefix="`pwd`/../"
make install
cd ../osm-3s_testing/
../test-bin/run_testsuite.sh 40
```

In particular, it should not be necessary and should be avoided to explicitly copy files or set permission bits. I could imagine that this results in that a different configuration than expected is executed.

If one of the above steps fails then we should walk through it to understand why it fails.

**Comment by mmd-osm** [comment]
I tried those instructions on the minor_issues branch on travis for Mac OS X:

* autoreconf did not work:

```
$ autoreconf
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:12: error: required file './ar-lib' not found
configure.ac:12:   'automake --add-missing' can install 'ar-lib'
configure.ac:12: error: required file './compile' not found
configure.ac:12:   'automake --add-missing' can install 'compile'
configure.ac:16: error: required file './config.guess' not found
configure.ac:16:   'automake --add-missing' can install 'config.guess'
configure.ac:16: error: required file './config.sub' not found
configure.ac:16:   'automake --add-missing' can install 'config.sub'
configure.ac:9: error: required file './install-sh' not found
configure.ac:9:   'automake --add-missing' can install 'install-sh'
configure.ac:16: error: required file './ltmain.sh' not found
configure.ac:9: error: required file './missing' not found
configure.ac:9:   'automake --add-missing' can install 'missing'
Makefile.am: error: required file './depcomp' not found
Makefile.am:   'automake --add-missing' can install 'depcomp'
Makefile.am:171: warning: user variable 'distdir' defined here ...

/usr/local/Cellar/automake/1.14.1/share/automake-1.14/am/distdir.am: ... overrides Automake variable 'distdir' defined here

autoreconf: automake failed with exit status: 1
```

I used the following instead:

```
  - autoscan
  - aclocal
  - autoheader
  - glibtoolize
  - automake --add-missing
  - autoconf
```

Travis.yml file: https://github.com/mmd-osm/Overpass-API/blob/test_minor_issues_osx/.travis.yml

**The test passes with a few issues:**

* File error catched: `0 /Users/travis/build/mmd-osm/Overpass-API/osm-3s_testing/run/test_dispatcher_server_26/./osm3s_share_test Unix_Socket::3`  --> probably socket name too long
* Some osm3s_query* fail (not OSX specific)


Full log file: https://travis-ci.org/mmd-osm/Overpass-API/builds/155713481

**Comment by mmd-osm** [comment]
@malcolmh : is this issue still relevant, are you still able to reproduce it or did you find some other solution?

If you think there's nothing left to do, would you mind closing this issue? Thanks.

**Comment by malcolmh** [comment]
I haven't hit it since upgrading to 7.53, so I will declare the issue moot.

**Comment by mmd-osm** [comment]
ok, great. Thanks for the quick feedback!
