### ISSUE TITLE
relation contains bbox

### ISSUE THREAD

**Issue by Skippern** [drolbr/Overpass-API#256]
I am working on analysing GPX files, and are looking for a way to easily identify in which country a specific GPX track is. I can easily get a bbox or a point cloud from the GPX and need a good way to search for the encompassing country. A overpass search of the type `[contain];relation({bbox})["type"="boundary"]["admin_level"="2"];out meta` or similar giving matches for any `admin_level=2` relation that completely encircles or intersect the `bbox` would solve this.

Currently I have a list of virtual bboxes to test against, where positive result downloads the relations from overpass and tests again against each relation encountered. The problem is that each of these test bboxes must intersect or contain a complete relation in order to find them, also for some places in the world I will need to test against multiple huge relations, such as along the US/Canada border, along the Russian border, etc.

**Comment by mmd-osm** [comment]
This looks like a duplicate of #253. 

You could use something like `is_in({{center}});area._["type"="boundary"]["admin_level"="2"];out meta;`, but that doesn't really scale well to many nodes.

**Comment by Skippern** [comment]
Is there any syntax for this in the pipeline?

**Comment by mmd-osm** [comment]
Not sure if I'm getting your point. Why would a syntax be of any help to you, if there's no implementation behind?

**Comment by Skippern** [comment]
Sorry, bad wording, any possibility for this being implemented shortly?

**Comment by mmd-osm** [comment]
Duplicate / similar requirement: https://github.com/drolbr/Overpass-API/issues/253

**Comment by Skippern** [comment]
I have managed to solve this using pivot for single node, so I consider this closed
