### ISSUE TITLE
Area creation fails after ~5 hours

### ISSUE THREAD

**Issue by jansauerbrey** [drolbr/Overpass-API#261]
Hi,

I installed the stable version 0.7.52 and started the area creation process with

`nohup ./bin/rules_loop.sh "/home/user/osm/db" &`

the process seems to start fine and the nohup.out shows messages, ie. 

`After 4h40m45s: in "query", part 4, on line 245. Stack: 0 of 5462570`

 for about 5 hours. Then suddenly it fails with the message:

`runtime error: Query run out of memory in "recurse" at line 255 using about 1608 MB of RAM.`

Afterwards it starts the process from the beginning. The whole process is running on a VM with 4 cores and 32GB RAM.
Any ideas what could be the reason for the sudden error?

Thanks,
Jan

**Comment by mmd-osm** [comment]
That's a known issue, See http://wiki.openstreetmap.org/w/index.php?title=Overpass_API/Installation&mobileaction=toggle_view_desktop#Area_batch_run_out_of_memory_error

**Comment by jansauerbrey** [comment]
Thanks for the hint to the page. I must have missed it in my google searches. For now it works, but process still running.

**Comment by mmd-osm** [comment]
I created a pull request to have this limit raised to a suitable value. At least two productive overpass instances are currently affected by this.
