### ISSUE TITLE
Missing configure script?

### ISSUE THREAD

**Issue by arminus** [drolbr/Overpass-API#263]
The build instructions on [http://overpass-api.de/full_installation.html](url) refer to src/configure - that script seems to be missing form the master branch...

**Comment by mmd-osm** [comment]
That's only provided in the official release, for the master branch please refer to http://wiki.openstreetmap.org/wiki/Overpass_API/Installation#Option_2:_Installation_via_bleeding_edge_dev_version_.28expert_use.29
