### ISSUE TITLE
runtime error: open64: 0 Success ... bad pos in index file

### ISSUE THREAD

**Issue by yoavartzi** [drolbr/Overpass-API#264]
I have been experiencing the following error:
runtime error: open64: 0 Success ../osm-db/node_tags_global.bin.idx File_Blocks_Index: bad pos in index file

The query is:
query(nwr(keyval('abandoned:tourism','theme_park')),qtype(findkey('name')))

It's the only query I tried. I tried to re-build the database 3 times and re-downloaded the planet OSM file, but I keep getting the same error message. I am using Ubuntu on a EC2 instance.

Any idea? I will be happy to provide any information that can help.

---

The database was built using:
export EXEC_DIR=/home/yoav/nlmaps/osm
export DB_DIR=/home/yoav/nlmaps/osm-db
export PLANET_FILE=/home/yoav/nlmaps/planet-latest.osm.bz2
nohup overpass-nlmaps/src/bin/init_osm3s.sh $PLANET_FILE $DB_DIR $EXEC_DIR &

**Comment by mmd-osm** [comment]
You seem to use some spin off project, which uses some older Overpass API version under the hood -> https://github.com/carhaas/overpass-nlmaps

Please try to reproduce this with an official Overpass API version, first. Also, please raise an issue with that project, as we have no idea, how overpass-nlmaps differs from the official version.

Also, the query you mentioned in not in Overpass XML or QL format, and therefore not compatible.
