### ISSUE TITLE
Covert request for OsmFilter

### ISSUE THREAD

**Issue by homersimpsons** [drolbr/Overpass-API#266]
Hello, thank you for overpass :)
There is an option that I would love:
convert overpass request to OsmFilter requet, to be aple to copy/paste this in a parameter file and then use it on a specific map, or a huge map.
It could be, on overpass-turbo [website](http://overpass-turbo.eu/) in menu export>request>OsmFilter parameter file

Thank you

**Comment by mmd-osm** [comment]
Hi there,
this is the Overpas API issue tracker. If you want to request new features for overpass turbo, please use this one here instead: https://github.com/tyrasd/overpass-turbo/issues

**Comment by homersimpsons** [comment]
Okay, I request there then :) Thank you
