### ISSUE TITLE
 Replication terminates with what():  Bad geometry for way

### ISSUE THREAD

**Issue by geohacker** [drolbr/Overpass-API#269]
Hey everyone!

I've been running into this the past week trying to setup an instance of Overpass, using documentation on the [wiki](http://wiki.openstreetmap.org/wiki/Overpass_API/Installation) and the [website](http://dev.overpass-api.de/full_installation.html), using version `osm-3s_v0.7.52`. I imported planet from May 1, ran minutely diffs and get the following error:

```
Way 3453383 has changed at timestamp 2016-02-16T23:22:09Z in two different diffs.
terminate called after throwing an instance of 'std::logic_error'
  what():  Bad geometry for way 3498958
./bin/apply_osc_to_db.sh: line 116: 20184 Aborted                 (core dumped) ./update_from_dir --osc-dir=$1 --version=$DATA_VERSION $META --flush-size=0
```

Along with warnings like: 

```
Version 1 has a later or equal timestamp (2016-05-01T07:58:33Z) than version 2 (2016-05-01T07:58:33Z) of Node 4158924290

Way 414665517 used in relation 6181436 not found.
Way 414665517 used in relation 6181436 not found.
```

There are the three different things I tried:

1. Clone the existing database from overpass-api.de, then start minutely, hourly or daily,  from March 31, 2016 based on some trial running queries before and after.
2. Clone attic data from overpass-api.de, then start minutely, hourly or daily, from March 31.

All failed with errors similar to above with different way IDs. Here's the command that I'm using:

`nohup bin/apply_osc_to_db.sh "diffs-min/" 1901571 --meta=yes --augmented_diffs=yes &` - the dispatcher is running with --meta and --attic

I also tried cloning Overpass master and the same error persists. I found some relevant conversation [here](http://gis.19327.n5.nabble.com/attic-errors-td5861099.html) but couldn't nail the issue based on my approaches above. 

@drolbr @mmd-osm - What could I be missing? Thank you!

**Comment by mmd-osm** [comment]
Hi,

your start replicate id seems to be too high. At the time of writing this, you shold start with 1860622, as can be seen in the respective replicate id file: http://dev.overpass-api.de/clone/replicate_id

For attic data, you should also use `--meta=attic`. Also I wouldn't use  `--augmented_diffs=`  as a parameter anymore, as that concept has been replaced by attic data in the meantime.

**Comment by geohacker** [comment]
@mmd-osm - thank you so much for the quick response! Okay I see. When I looked replicate_id in my db clone it was `16110` - which somehow felt odd and continued with trials to find a recent change. 

I think this inconsistency may have been because I ran download_clone.sh with and without attic data. 

@mmd-osm - part of the reason why I had to kick off two clone operation is because when I ran `./bin/download_clone.sh --source=http://dev.overpass-api.de/api_drolbr/ --db-dir="db/" --meta=yes &` I ran into the following error, while running a query:

```
terminate called after throwing an instance of 'Zlib_Inflate::Error'
what():  Zlib_Inflate: -5
Aborted (core dumped)
```

This got me thinking that the dev.overpass-api.de/ clone is from a pre 0.7.52 version without compression. Is this the case? 

Also, since this ticket isn't a bug report, is there a different place where I should ask questions? Thank you so much.

**Comment by mmd-osm** [comment]
The dev list would be a good place for those kind of questions: http://listes.openstreetmap.fr/wws/info/overpass

**Comment by geohacker** [comment]
@mmd-osm okay great. Does dev.overpass-api.de use 0.7.52 with compression? 

I'll close this and move the list for further questions. Thanks again.

**Comment by geohacker** [comment]
The gist of the problem looks like it was because I picked a wrong replication ID. I'm going to give this another shot, with a clone and minutely replication from that point. Closing. Thank you!
