### ISSUE TITLE
Augmented Delta between two dates - Output contains data out of date range

### ISSUE THREAD

**Issue by pierzen** [drolbr/Overpass-API#270]
Querying for Adiff, I often see output containing diffs out of date range. This can be reproduced with the following request :

```
[adiff:"2016-05-05T00:00:00Z","2016-05-06T00:00:00Z"];
(  node(56.69191139138273,-111.36566162109375,56.695870366414596,-111.35900974273682);
   way(56.69191139138273,-111.36566162109375,56.695870366414596,-111.35900974273682);
   relation(56.69191139138273,-111.36566162109375,56.695870366414596,-111.35900974273682); 
);  out meta;
```

The following diffs in the output are months/years before 2016-05-05
way id=155730405	timestamp=2012-03-18T22:53:52Z
relation id=172567	timestamp=2016-01-26T17:47:17Z

The following query let's me validate if for this bbox, all the diffs for 2016-05-05 were returned. No missings were found.

```
[date:"2016-05-06T00:00:00Z"];
(
  node({{bbox}})(newer:"2016-05-05T00:00:00Z");
  way({{bbox}})(newer:"2016-05-05T00:00:00Z");
  relation({{bbox}})(newer:"2016-05-05T00:00:00Z");
);
out meta;
```

**Comment by mmd-osm** [comment]
As several nodes belonging to way 155730405 changed in the timeframe you provided, way 155730405 will appear in the result. It really doesn't matter if the way id is from 2012-03-18, as you can always change nodes without touching ways at all - but that still affects the overall geometry of the way, hence the way is considered to have changed as well.

See:
```C
[adiff:"2016-05-05T00:00:00Z","2016-05-06T00:00:00Z"];
(  
   way(155730405)(56.69191139138273,-111.36566162109375,56.695870366414596,-111.35900974273682);
  
); (._;>;); out meta;
```

and based on the changeset found in the result, you inspect the respective changeset in achavi: http://nrenner.github.io/achavi/?changeset=39124684

**Comment by pierzen** [comment]
Thanks for your explanation. I will simply ignore ways and relations that are out of the requested date range.

We can have different perspectives analyzing OSM data. My objective is to look at Contributors actions, to identify objects (either nodes, ways or relations) that they have modified.   Since I already select all nodes modified, my query is ideal for the objectives of the analysis.
