### ISSUE TITLE
Regexp: Escaping "|" metacharacter with "\" does not work

### ISSUE THREAD

**Issue by slhh** [drolbr/Overpass-API#271]
Seaching for "I" in tag values I have tried the following query:

http://overpass-turbo.eu/s/gfl

The unexpected result includes ways with the tag:
`lanes:backward=1`

Some more test have shown that escaping the | metacharacter with `\` doesn't work.
I have been able to get the desired result using `[|]` instead of `\|` as a workaround.

**Comment by mmd-osm** [comment]
You also need to escape the `\` escape character: 

 `way["lanes:backward"~"\\|"];`

**Comment by tyrasd** [comment]
See http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Value_matches_regular_expression_.28.7E.2C_.21.7E.29 for a reference of this behaviour in the Overpass QL documentation.

**Comment by drolbr** [comment]
Question answered.
