### ISSUE TITLE
way(r)[!=v] takes forever whereas way(r)[k!=v] is very quick

### ISSUE THREAD

**Issue by naomap** [drolbr/Overpass-API#272]
Hello !

I'm preparing an Overpass workshop for SOTM FR, and came across a performance issue which I don't understand. The following request is pretty quick :

rel(165712);
way(r)["railway"!="platform"];
out; >; out;

However if you turn "railway"!="platform" into "railway"="platform" it takes forever !

Do you have any idea why that is the case ?

Regards,
Antoine.

**Comment by drolbr** [comment]
Yes. It is a bad guess by the scheduler in the query command. It assumes that there are many elements that don't carry a tag and therefore filters for other criteria first. But it assumes that there are few elements that carry a tag and therefore filters for that first - it tries to enumerate all way ids that have the tag [railway=platform].

I suggest one of the two workarounds:

rel(165712);
way(r)["railway"~"^platform$"];
out; >; out;

or

rel(165712);
way(r);
way._["railway"="platform"];
out; >; out;

The first one replaces the exact value with a regular expression that matches only the exact value. The second one enforces the order by first colleting all relation members and then filtering them for the tag.

**Comment by mmd-osm** [comment]
@naomap : if you like, you can also add your SOTM Fr presentation to the Wiki page: https://wiki.openstreetmap.org/wiki/Overpass_API#Talks.2C_Presentations.2C_Workshops - we're somewhat short Overpass presentations in French.

**Comment by drolbr** [comment]
Fixed in commit 6e4d723bc1d63b75d07a86f57cacbffdbcf584dc
