### ISSUE TITLE
Searching for buildings depending on geo position

### ISSUE THREAD

**Issue by phnmnm** [drolbr/Overpass-API#273]
Hi,

I am trying to get the building polygon depending on a position (lat,lon in WGS84) inside the painted polygon on the map.

I try:
**[bbox: lat-0.00003,lon-0.00003,lat+0.00003,lon+0.00003]; ((way[building];); >; );out;**

My problem is that if buildings are very close to each other I get 2/3 buildings...

Is it better to work with **(around:rad,lat,lon)**. And if yes how would you do it?

If you need more info let me know.

Hope you can help me.

best regards

**Comment by mmd-osm** [comment]
Can you provide a concrete example as overpass-turbo.eu link?

**Comment by phnmnm** [comment]
I didnt find a way to export as a link but here is my request which you can paste @overpass-turbo.eu

[bbox: 49.0664,12.8846,49.0665,12.8847]; ((way[building];); >; );out;

**Comment by phnmnm** [comment]
In this case I dont have any meta information to postprocess which building is the correct one.

If there is a housenumber I can compare and define the correct building.

**Comment by phnmnm** [comment]
And if I make my bbox too small I dont get any building

**Comment by phnmnm** [comment]
http://overpass-turbo.eu/

**Comment by mmd-osm** [comment]
You need to click on the "Share" button and copy the permalink.

**Comment by phnmnm** [comment]
Ahhh ... Im blind..

http://overpass-turbo.eu/s/ghq

**Comment by phnmnm** [comment]
I am checking if the geo position is inside the resulting building polygon.

Anyway if it would be possible by filtering the query request I would like to know it.

**Comment by mmd-osm** [comment]
Not sure, if I'm following you. In your first post, you mentioned " inside the painted polygon on the map.", now you're talking about "inside the resulting building polygon".

I would highly recommend to follow this topic up on https://help.openstreetmap.org, as this Github issue tracker is meant for software bugs and enhancement requests. Your question seems more like a "How-to" thing, which is better suited for Help OSM.

**Comment by mmd-osm** [comment]
@phnmnm, as there's no follow up from your side, may I kindly ask you to close this issue? Thanks.
