### ISSUE TITLE
node._ does not filter-out ways and relations!?

### ISSUE THREAD

**Issue by zstadler** [drolbr/Overpass-API#274]
I expected `node._;` to filter everything except the nodes in the input set.

However, the results of
```
(rel(11);>;);
out count;
node._ ;
out count;
```
show that the full input set was included in the output set:  
```
  <count total="811" nodes="791" ways="19" relations="1"/>
  <count total="811" nodes="791" ways="19" relations="1"/>
```

It seems there is no difference between `node._;` and `way._;`.
```
(rel(11);>;);
out count;
way._;
out count;
```
produces the same results.

**Comment by mmd-osm** [comment]
According to the Wiki, the _"item" filter selects all elements from its input set._ Unfortunately, it doesn't specify exactly, if filtering by type should also be done. IMHO I think this would make sense. as you pointed out. Let's leave this to Roland to clarify the intended behavior.

Once the original query is translated into Overpass XML, `way._` is represented as `<item set="_"/>` - the reference to the way is gone. I guess that's the reason, why `way._` or `node._` all return the same result.

The following, rather weird looking workaround stores the original inputset in two different inputsets `.a` and `.b` and determines the intersection. In the Overpass XML variant, the node and both inputsets are still present.

```C
((rel(11);>;)->.a;)->.b;
.a out count;
node.a.b;
out count;
```


```XML
  <query into="_" type="node">
    <item set="a"/>
    <item set="b"/>
  </query>
```

Result:

```XML
  <count total="811" nodes="791" ways="19" relations="1" areas="0"/>
  <count total="791" nodes="791" ways="0" relations="0" areas="0"/>
```

**Comment by zstadler** [comment]
Thanks for the insight. I think it is misleading when the "node" and "way" prefixes have no impact. I hope 
@drolbr will agree with me.

As a workaround I'm using set intersection: `node._._` instead of `node._`

I find that  [recurse](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Recurse_.28n.2C_w.2C_r.2C_bn.2C_bw.2C_br.29) filters would be a bit more cumbersome compared to `>` when recursing down from a relation.

**Comment by mmd-osm** [comment]
Thanks, `node._._;` is even better. I think the QL parser has an issue here, as the following XML variant works just fine.

```XML
<osm-script>
  <union into="_">
    <id-query ref="11" type="relation"/>
    <recurse type="down"/>
  </union>
  <print mode="count"/>
  <query into="_" type="node">
    <item set="_"/>
  </query>
  <print mode="count"/>
</osm-script>
```

**Comment by mmd-osm** [comment]
I'm inclined to fix this via the following change in the else branch starting in map_ql_parser.cc:1499

```C
  TStatement* statement = 0;
  if (clauses.size() == 0)
  {
[...]

//    else
//      statement = create_item_statement< TStatement >(stmt_factory, from, query_line_col.first);
    else
    {
      statement = create_query_statement< TStatement >
          (stmt_factory, type, into, query_line_col.first);
      TStatement* substatement = create_item_statement< TStatement >(stmt_factory, from, query_line_col.first);
      statement->add_statement(substatement, "");
    }
```

**Comment by mmd-osm** [comment]
@zstadler : I deployed this fix now to the dev instance for further testing:

http://overpass-turbo.eu/s/gsr

Maybe you can try this and some related queries (like `( ._; >;)`, etc.).

**Comment by zstadler** [comment]
I've re-run the same query with the workarounds removed, and the results are the same. This included examples like
```
(node._._;
 - (node._(user:zstadler);););
```
Thanks!

**Comment by mmd-osm** [comment]
BTW: when testing in overpass turbo, please make sure to use the dev instance instead of overpass-api.de as a server. That's: `http://dev.overpass-api.de/api_mmd/` or use the embedded `{{data:` tag as shown in the shortlink above.

`node._._;` will also work on overpass-api.de, but `node._;` will not at this time...

**Comment by zstadler** [comment]
Yes, I've used the dev instance, from the shared URL.
The results on the dev server without the workaround are equal to the results with the workaround on the production server when setting `[date:"2016-05-15T00:00:00Z"]`
