### ISSUE TITLE
Attic output for deleted objects sometimes do not provide all OSM keys

### ISSUE THREAD

**Issue by pierzen** [drolbr/Overpass-API#276]
Adiff query to reproduce the problem
[out:xml] [adiff:"2015-07-04T00:00:00Z","2015-10-04T00:00:00Z"];
node(6.33728,1.45046,6.34266,1.46014);
out meta;

Attic output of deleted objects for this query do not always contain version, timestamp, changeset and uid for some of the deleted objects, while these variables are available on the OSM API 0.6.

Example of Adiff output
1. Variables content identical to OSM API
<action type="delete">
<old>
  <node id="3059328603" lat="6.3399564" lon="1.4552982" version="1" timestamp="2014-09-04T14:06:08Z" changeset="25227385" uid="1731253" user="keepright! ler"/>
</old>
<new>
  <node id="3059328603" visible="false" version="2" timestamp="2015-08-21T01:16:03Z" changeset="33473885" uid="632960" user="hermann106"/>
</new>
</action>

2. Some variables missing while available on the OSM API
<action type="delete">
<old>
  <node id="3059328609" lat="6.3415915" lon="1.4546882" version="1" timestamp="2014-09-04T14:06:08Z" changeset="25227385" uid="1731253" user="keepright! ler"/>
</old>
<new>
  <node id="3059328609" visible="false"/>
</new>
</action>

OSM API
See http://www.openstreetmap.org/api/0.6/node/3059328609/history

**Comment by mmd-osm** [comment]
I can reproduce this on overpass-api.de, but not on my own instance (//dev.overpass-api.de/api_mmd/):

```XML
<action type="delete">
<old>
  <node id="3059328609" lat="6.3415915" lon="1.4546882" version="1" timestamp="2014-09-04T14:06:08Z" changeset="25227385" uid="1731253" user="keepright! ler"/>
</old>
<new>
  <node id="3059328609" visible="false"/>
</new>
</action>
```

mmd instance on dev:

```XML
<action type="delete">
<old>
  <node id="3059328609" lat="6.3415915" lon="1.4546882" version="1" timestamp="2014-09-04T14:06:08Z" changeset="25227385" uid="1731253" user="keepright! ler"/>
</old>
<new>
  <node id="3059328609" visible="false" version="2" timestamp="2015-08-21T01:16:03Z" changeset="33473885" uid="632960" user="hermann106"/>
</new>
</action>
```
Unfortunately, Roland's db on the dev instance has the same issue:

```XML
<action type="delete">
<old>
  <node id="3059328609" lat="6.3415915" lon="1.4546882" version="1" timestamp="2014-09-04T14:06:08Z" changeset="25227385" uid="1731253" user="keepright! ler"/>
</old>
<new>
  <node id="3059328609" visible="false"/>
</new>
</action>
```

Not sure where this comes from.

**Comment by drolbr** [comment]
I'm not able to reproduce to issue.

The moost likely root cause of the issue is that the indexes in the attic map file do not match the indexes of the actual objects. I was able to observe that in older versions. But not with the most recent code.

I'll keep this bug open until we have rebuilt the database and not seen again the issue.

**Comment by drolbr** [comment]
After rebuildingthe data from minute diff 1,200,000 to minute diff 2,000,000, the issue did not reappear. Now I'm sure that the fix is sufficient.

I'll now prepare the next release and rebuild the database with that.
