### ISSUE TITLE
Ajax error when running queries on Mexico and USA

### ISSUE THREAD

**Issue by abautis** [drolbr/Overpass-API#284]
An error occured during the execution of the overpass query!

Request rejected. (e.g. server not found, request blocked by browser addon, request redirected, internal server errors, etc.)

Error while parsing the data (parsererror).

[out:json][timeout:250]{{data:overpass,server=http://dev.overpass-api.de/api_mmd/}};
// fetch area “Mexico” to search in
{{geocodeArea:Mexico}}->.searchArea;
// gather results
(
  // query part for: “Highway”
  way["highway"](area.searchArea);
);
// print results
out body;

> ;
> out skel qt;

Can anyone help me with this? I am trying to get highway information for Mexico and USA in the Overpass Schema

**Comment by mmd-osm** [comment]
Unable to reproduce here. Mexico returns an 865MB file when downloading via `curl` from command line.

**Comment by abautis** [comment]
How do I reproduce that query in curl?

**Comment by mmd-osm** [comment]
in overpass turbo, you simply get the link via "Export" -> "raw data directly from Overpass API". 

```
curl -H 'Accept-Encoding: gzip,deflate' http://dev.overpass-api.de/api_mmd/interpreter?data=%5Bout%3Ajson%5D%5Btimeout%3A250%5D%3B%0A%0Aarea%283600114686%29-%3E.searchArea%3B%0A%2F%2F%20gather%20results%0A%28%0A%20%20%2F%2F%20query%20part%20for%3A%20%3CE2%3E%3C80%3E%3C9C%3EHighway%3CE2%3E%3C80%3E%3C9D%3E%0A%20%20way%5B%22highway%22%5D%28area.searchArea%29%3B%0A%29%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B%0A%0A%0A%0A%0A
```

**Comment by abautis** [comment]
@mmd-osm  will this work also for the US or should i go by state?

**Comment by mmd-osm** [comment]
Sorry, no idea. Dev instance runs on hard disks and is not really meant for public downloads for that size. Maybe try single states first.

**Comment by abautis** [comment]
Okay what if i just want Trunk,Primary,Secondary,Motorway and Tertiary tags in Highways. Do you think it will handle this?

**Comment by mmd-osm** [comment]
Yes, if you adjust your query accordingly. Start with a small region and see how it works.

Please keep in mind that this Github site is mainly used as issue tracker for software bugs and enhancement requests. General HOWTO topics are best suited for one of the community help sites listed on the Wiki page:

https://wiki.openstreetmap.org/wiki/Overpass_API#Community:_where_can_I_get_help.3F

Thanks for your understanding.
