### ISSUE TITLE
Overpass keeps old data, even after updated timestamp

### ISSUE THREAD

**Issue by TitanFighter** [drolbr/Overpass-API#286]
There is such query: http://overpass-turbo.eu/s/gHt
Timestamps are quite fresh (1 day old):
`<meta osm_base="2016-06-08T13:00:02Z" areas="2016-06-07T04:53:03Z"/>`

The 1st area shows:
```
 <area id="2430717714">
    <tag k="addr:postcode" v="93704"/>
    <tag k="boundary" v="administrative"/>
    <tag k="is_in" v="Луганська обл., Україна"/>
    <tag k="koatuu" v="4424555102"/>
    <tag k="name" v="Знам’янка"/>
    <tag k="name:en" v="Znamianka"/>
    <tag k="name:ru" v="Знаменка"/>
    <tag k="name:uk" v="Знам’янка"/>
    <tag k="place" v="village"/>
  </area>
```
Area id shows that this is way 30717714
Check this way on OSM: http://www.openstreetmap.org/way/30717714 and see that this line was removed 10 days ago and if we check history of chages, we can find that information from area's tags relates to the old\removed record.

Edited:
The same situation with the:
1) node 337587463 and its way 30718706
2) node 337588045 and its way 30719499

**Comment by mmd-osm** [comment]
This is same as #285, right? If so, please close this one and add this as comment to #285.

**Comment by TitanFighter** [comment]
Done
