### ISSUE TITLE
Letsencrypt certificate not valid for www

### ISSUE THREAD

**Issue by grischard** [drolbr/Overpass-API#288]
The TLS certificate for overpass-api.de was renewed yesterday.

The previous certificate was valid for both https://overpass-api.de and https://**www**.overpass-api.de. The new certificate isn't valid for www.

This breaks clients that made calls to https://www.overpass-api.de and generates obscure warnings which cause developer sadness.

Workaround: update clients to call https://overpass-api.de

**Comment by drolbr** [comment]
Thank you for reporting the issue. As it is an operations problem, I would prefer to have it at the operations page: http://wiki.osm.org/wiki/Overpass_API/status

However, I had requested the wrong certificate. Please try again whether it works now.

**Comment by grischard** [comment]
Perfect 👍

I wasn't sure where to report this, I'll know about that page for next time!
