### ISSUE TITLE
Language conversion broken?

### ISSUE THREAD

**Issue by malenki** [drolbr/Overpass-API#289]
The [convert form](http://overpass-api.de/query_form.html) translates this working query ([overpass turbo link](http://overpass-turbo.eu/s/gRy)):

```
[date:"2014-09-20T07:20:07Z"];
( node({{bbox}}); <; >; );
out meta;
```
into this not-working¹ query ([overpass turbo link](http://overpass-turbo.eu/s/gRz)): 

```
<osm-script date="2014-09-20T07:20:07Z">
  <union into="_">
    <recurse from="_" into="_" type="up"/>
    <recurse from="_" into="_" type="down"/>
  </union>
  <print e="" from="_" geometry="skeleton" limit="" mode="meta" n="" order="id" s="" w=""/>
</osm-script>
```

¹ "received empty dataset"

**Comment by mmd-osm** [comment]
Cannot reproduce here. Did you replace `{{bbox}}` by actual coordinates? Overpass API has no idea about those overpass turbo specific syntax enhancements and simply ignore this invalid syntax.

```C
[date:"2014-09-20T07:20:07Z"];
( node(50.91933597943467,13.3435620367527,50.92012393299067,13.345497250556946); <; >; );
out meta;
```

Result:
```C
<osm-script date="2014-09-20T07:20:07Z">
  <union into="_">
    <bbox-query e="13.345497250556946" into="_" n="50.92012393299067" s="50.91933597943467" w="13.3435620367527"/>
    <recurse from="_" into="_" type="up"/>
    <recurse from="_" into="_" type="down"/>
  </union>
  <print e="" from="_" geometry="skeleton" limit="" mode="meta" n="" order="id" s="" w=""/>
</osm-script>
```

**Comment by malenki** [comment]
Darn, mea culpa…
Recently I used Overpass Turbo seldom and forgot about that "problem" and the query export feature. Thank you for the hint.

**Comment by TheFive** [comment]
But it would be very nice for all, that are not so experienced with overpass, to have a language converter, that supports overpass and uMap bboxes :-)
