### ISSUE TITLE
Area creation doesn't finish

### ISSUE THREAD

**Issue by geohacker** [drolbr/Overpass-API#290]
#I'm creating overpass areas and this doesn't seem to get to this [line in the script](https://github.com/drolbr/Overpass-API/blob/master/src/bin/rules_loop.sh#L42). I had to up the memory as well as the timeout of the queries but every 24 hours, the query restarts with no error. The area index and the file sizes are continuously growing. Some area queries return results, many doesn't. I have been running this for over a week. 

The area status is always 2 days behind.

@mmd-osm @drolbr - do you have thoughts on what I should try? or am I missing something?

**Comment by geohacker** [comment]
The logs keep going:

```
After 23h55m16s: in "make-area", part 0, on line 257. Stack: 5374693 of 5758586
After 23h55m31s: in "make-area", part 0, on line 257. Stack: 5376324 of 5758586
After 23h55m46s: in "make-area", part 0, on line 257. Stack: 5378253 of 5758586
After 23h56m1s: in "make-area", part 0, on line 257. Stack: 5380576 of 5758586
After 23h56m16s: in "recurse", part 0, on line 255. Stack: 5382658 of 5758586 0 of 1
```

**Comment by mmd-osm** [comment]
This doesn't really sound like a bug or enhancement request - at least on the instances I know, the area creation finishes in 13.5 hours (v0.7.52 on SSD). Maybe remove all of your area files, restart the dispatcher and start from scratch. Performance also highly depends on your I/O subsystem and available CPU resources. 

I'd suggest to discuss this on the overpass dev ML as this is really more of a HOWTO and close this issue: http://listes.openstreetmap.fr/wws/info/overpass

**Comment by geohacker** [comment]
Hey @mmd-osm - that's true, sorry will move this to the mailing list. I should be doing something wrong really, have tried restarting from a fresh database couple of times to see anything in the logs. 

Let me write up some notes and post on the mailing list. Thank you.

**Comment by mmd-osm** [comment]
We had similar reports of runtimes >24h (actually 26h) in the forum. All that was needed to get it running was to increase the timeout in the area rules file.
