### ISSUE TITLE
Cannot query low-id nodes by their id

### ISSUE THREAD

**Issue by tyrasd** [drolbr/Overpass-API#295]
An id-query for low-id nodes (e.g. [`node/1`](http://www.openstreetmap.org/node/1) – OverpassQL: [`node(1);out;`](http://overpass-turbo.eu/s/hfB)) currently doesn't return any data. On the other hand, such nodes can be found just fine using a normal [bbox](http://overpass-turbo.eu/s/hfC) query and are also returned in [recursion statements](http://overpass-turbo.eu/s/hfE).

This used to work until very recently and is now broken on all of the 3 public Overpass API instances. Currently, node ids < approx. 1 400 000 are affected. A (probably not so) wild guess: could this be related to us just actually [breaking the 2^32 bit node-id mark](http://textual.ru/64/) (maybe the minutely-update script is overriding some not-yet 64-bit ready index)?

**Comment by mmd-osm** [comment]
> This used to work until very recently and is now broken on all of the 3 public Overpass API instances. 

Confirmed. `node(1);out;` still works on my instance (last updated 2016-05-15T00:00:00Z).

Can you send a prio high email to Roland? I think this issue needs immediate attention, before the next clone database is created.

**Comment by tyrasd** [comment]
> Can you send a prio high email to Roland?

OK

**Comment by drolbr** [comment]
Fixed in 3b73df21fa9d0bce47668cd30da9cc77a02475c9 . Deployed on dev.overpass-api.de, other instances will follow as soon as possible.

**Comment by mmd-osm** [comment]
@drolbr : can you please also do a quick cross-check, if your branch `backend_compression_map` is not affected by this issue?

I would assume, it is ok as it is right now, just wanted to be sure.

**Comment by mmd-osm** [comment]
Announcement: http://permalink.gmane.org/gmane.comp.gis.openstreetmap.overpass/275
