### ISSUE TITLE
CSV output 

### ISSUE THREAD

**Issue by filip55** [drolbr/Overpass-API#303]
Hello,

when I run this code on overpass turbo
> [out:csv(::id, place, name, population, "name:it", official_name)];
area[name="Grad Vodnjan"]->.a;
(
  node["place"~"city|town|village|hamlet"](area.a);
);
out center;

I get output with normal characters, but when I try to export as raw data directly from Overpass API, which I open with Firefox or Excel, I get data with characters like this 

> Å¡, Å¾, Å etc.

**Comment by mmd-osm** [comment]
Did you select UTF8 charset in Firefox/excel?
>
>

**Comment by filip55** [comment]
I think that I have this option enabled by default in firefox/excel, because when I open file with notepad and save as with UTF-8 encoding, everything works fine, so I think that overpass api don't save file with UTF8 encoding.

**Comment by mmd-osm** [comment]
This is how the result looks like when importing in Excel (UTF-8 must be specified!)

![27-07-2016 10-40-47](https://cloud.githubusercontent.com/assets/5842757/17169237/dbe5c68c-53e6-11e6-9bcd-5d4021373339.png)

And here in Firefox: also explicit setting the charset to utf-8 is mandatory.

![27-07-2016 10-41-23](https://cloud.githubusercontent.com/assets/5842757/17169236/dbe5085a-53e6-11e6-874e-32c5562881ed.png)
