### ISSUE TITLE
Overflow problem with node id output in csv format?

### ISSUE THREAD

**Issue by FrakGart** [drolbr/Overpass-API#304]
When outputting node id's in a csv result format I think they are being treated as 32 bit rather than 64.

For example:

http://overpass-turbo.eu/s/hGR

**Comment by mmd-osm** [comment]
Thanks for reporting this issue.

Bug is in https://github.com/drolbr/Overpass-API/blob/master/src/overpass_api/frontend/print_target.cc#L1005

**Comment by mmd-osm** [comment]
Same issue for custom output: http://overpass-api.de/api/interpreter?data=[out:custom];node(4294967296);out;
