### ISSUE TITLE
Libosmium based update_database prototype

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#307]
Branch  https://github.com/mmd-osm/Overpass-API/tree/update_libosmium introduces a [Libosmium](https://github.com/osmcode/libosmium) based replacement for _Osm_Updater_ to add native osm.[pbf](http://wiki.openstreetmap.org/wiki/PBF_Format) and osm.bz2 processing capabilities to `update_database`.

Due to the better abstraction provided by libosmium''s handler interface, the code looks somewhat cleaner. Also we get a nice speed up due to removal of unnecessary XML processing and internal parallel processing in libosmium.
## Runtime comparison
- Initial database load, including meta - Planet file Aug 18 2016 (file size 35 GB) 

| Processing step | Baseline 0.7.52 | +LZ4/[parallel db update](https://github.com/drolbr/Overpass-API/issues/281) | +Libosmium-based |
| --- | --- | --- | --- |
| Finished Nodes | 07:38 | 04:35 | 02:33 |
| Finished Ways | 12:21 | 05:29 | 04:40 |
| Finished Relations | 00:28 | 00:16 | 00:08 |
| **Total Runtime (in hours)** | **20:27** | **10:20** | **07:21** |

Runtime for _ways_ depends mostly on _get_existing_skeletons_ and _compute_geometry_, so speeds ups are not that large in that area.
## Compile options

Manually specifying Include directories and linker flags still necessary for this prototype.

On Ubuntu 16.04 I used:

```
sudo apt-get install libosmium2-dev libbz2-dev
configure --enable-lz4 CXXFLAGS="-std=c++11 -O2 LDFLAGS="-lpthread -lbz2"
```
## Open topics
- `osm_element_count` / `flush_limit` may need some adjustments to limit memory consumption 
- calling `set_id_deleted` is still untested.

**Comment by mmd-osm** [comment]
To speed up processing for ways, see this parallel processing option for lookup_missing_nodes: https://github.com/mmd-osm/Overpass-API/blob/3ae1a3ed614afb04545ab841cb9770e74c1923bb/src/overpass_api/osm-backend/way_updater.cc#L570-L640

**Comment by mmd-osm** [comment]
Implemented in https://github.com/mmd-osm/Overpass-API, closing here.

**Comment by estadtherr** [comment]
It would be nice to have this feature merged into the main Overpass-API repository. Is there a reason the issue was closed without the fix being merged?
