### ISSUE TITLE
contains and intersects BBOX

### ISSUE THREAD

**Issue by Skippern** [drolbr/Overpass-API#309]
I am looking for a simple way to get relations (boundary relations) with a simple search. Currently I test the BBOX against a list of squares, and when test return true start testing against boundary relations that intersect with the square. To be able to do this test globally I would need to make squares covering the entire globe.

Instead, it could be done in a simple query: ```contain;relation["type"="boundary"]["admin_level"="2"](BBOX);out ids``` or similar syntax would give only the national border relations intersecting or containing the BBOX.

Have looked through documentation and cannot find anything actually covering my needs.

**Comment by mmd-osm** [comment]
Did you already check out the concept of area, namely `is_in;` and `rel(pivot)` in the documentation? Also, I don't really understand your use case. Can you explain what kind of problem you're trying to solve?

**Comment by Skippern** [comment]
```rel(pivot)``` sounds like something I must study closer.

I am testing GPX files recursively against boundary relations to identify the locations each GPX trace passes, the first test is against country (```admin_level=2```), and depending on recognised countries, test continues recursively on admin_levels depending on rules for each country.

The problem is to identify the countries without having to do too many tests.

You can see the code I work on (and belonging issues) at http://github.com/Skippern/gpxupload

**Comment by mmd-osm** [comment]
Can you check the following issue: https://github.com/drolbr/Overpass-API/issues/253 

I think your use case sounds a lot like that one, especially the description on GIS Stackexchange mentioned there.

**Comment by Skippern** [comment]
Sorry for a bit double posting, same kind of problem, I was actually looking for that one, but couldn't find it and thought for a moment my memory had failed me....

**Comment by mmd-osm** [comment]
Ok, great. Can you close this issue, then?

**Comment by Skippern** [comment]
Duplicate of #256
