### ISSUE TITLE
Patch in backend_compression_map branch needs to be merged in master - Follow-up #215

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#310]
The respective patch is crucial to avoid segmentation faults :warning:, which happen during database update - see #215 for details: https://github.com/drolbr/Overpass-API/commit/2cb8e9634ca9fa9cbf17c967731aaec86e82c038

However, as all relevant tickets are already closed, I'm creating a dedicated issue now for better visibility.

We need the following patch in random_file_index.h, otherwise we'll get some segmentation faults during database updates later.

```C
--- a/src/template_db/random_file_index.h
+++ b/src/template_db/random_file_index.h
@@ -210,7 +210,7 @@ inline Random_File_Index::Random_File_Index
        uint32 void_index_size = void_blocks_file.size("Random_File:11");
        Void_Pointer< uint8 > index_buf(void_index_size);
        void_blocks_file.read(index_buf.ptr, void_index_size, "Random_File:15");
-       for (uint32 i = 0; i < void_index_size/sizeof(uint32); ++i)
+       for (uint32 i = 0; i < void_index_size/8; ++i)
          void_blocks.push_back(*(std::pair< uint32, uint32 >*)(index_buf.ptr + 
        empty_index_file_used = true;
       }

```

**Comment by drolbr** [comment]
Thank you for the reminder.

Patched in 2aef49b6fe76df1de7988acb3fddebeac801b095
