### ISSUE TITLE
Incorrect node id in CSV output results

### ISSUE THREAD

**Issue by zstadler** [drolbr/Overpass-API#311]
The result of [looking for node 4299683052](http://overpass-turbo.eu/s/i3R)
```
[out:csv(::id, ::otype; true; "," )];
node (4299683052);
out;
```
is node 4715756
```
@id,@otype
4715756,1
```
XML or JSON output formats provide correct results

**Comment by mmd-osm** [comment]
That's a duplicate of https://github.com/drolbr/Overpass-API/issues/304

**Comment by zstadler** [comment]
Thanks!
