### ISSUE TITLE
Around and radius variable

### ISSUE THREAD

**Issue by AllroadsNL** [drolbr/Overpass-API#312]
I was searching to find out a string, how I can search for nodes with the same tag that are close to each other.

The problem in OSMdata is that on a highway with a ford=yes, 3 nodes with ford=yes where tagged for 1 ford

Possible tagging right and wrong.
1 ford, 1 node tagged.
1 ford, 1 way tagged, this is better if gives the exact spot where the ford begins and end.
1 ford, 1 way and 1 node, node on crossing waterway, this could also be done.
1 ford, 1 way and 3 nodes, begin middle end of the ford, Wrong, 3 nodes suggest that there are 3 fords
1 ford, 3 nodes begin middle en of the ford.  Wrong, 3 nodes suggest that there are 3 fords.

Why is it tagged with 3 nodes, because people want in there gps (garmin) a warning, when there is a ford coming. This warning they do NOT get on a way tagged with ford=yes
Tagging for the render.

Now I want to find these spots.
Where 2 or 3 nodes are close to each other. But the way is not split or did not have a highway with ford=yes tagging.

Overpass situation example
http://overpass-turbo.eu/s/i6lI
It also select the single ford=yes, this one should not be selected, excluded.

I did see this page:
http://osmlab.github.io/learnoverpass/en/docs/filters/around/

```
(
node[ford=yes]({{bbox}});
node(around:50)[ford=yes];  
);
```
I believe that the single node is selected because radius=0  0 meter is the single point.

Is/could it be possible to select a radius between  two meter values.
Or is there a method to exclude 0

**Comment by mmd-osm** [comment]
A few hints:

* Changing those at large scale might be considered a mechanical edit. Discuss this first with the community!
* Your question would be better suited for [Help OSM](https://help.openstreetmap.org), as it is neither a bug report nor a feature request


Now, if I got your question right, you want to find nodes with ford=yes, which basically are not crossing a waterway. How about:

```C
[bbox:{{bbox}}];
(node[ford=yes]({{bbox}}) - (way[waterway];node(around:0)[ford=yes]));
out meta;
```

**Comment by AllroadsNL** [comment]
Thanks for the hints.
Mechanical edit;
I know, what a mechanical edit is. First, knowing, where a problem is. That was the intention of the search ford. Second, the edit depends of the problem if it could be done by mechanical or only by hand. A decision for later.

Ford search;
That is a way of search, but not every node ford=yes is set on a waterway, because the waterway is not yet drawn in, JOSM complains also, validation. Most people first like to draw in roads and set only the ford on the road.


Feature request:
Ford was only used as a example. Could also be used for other situation with tags.
Not only as a node on a way. Also for only a node.

> A radius of 0 can be used for a way intersection test on outer/inner points.

My request is of radius between to meters could be used.
(around:1-50)  ore even use a decimal (0.5-50)
or a code that 0 meter is excluded.

**Comment by mmd-osm** [comment]
> My request is of radius between to meters could be used.
> (around:1-50) ore even use a decimal (0.5-50)
> or a code that 0 meter is excluded.

You can use the difference statement(` -  `) for this purpose as shown above. Approach would be:
query all nodes within radius 50m   MINUS  all nodes within radius 1m (or even with radius 0).

**Comment by drolbr** [comment]
Please try [this query](http://overpass-turbo.eu/s/i7q).

It is not really fast (15-30 seconds) but it does the job. More precisely: It finds all nodes that are less then 30 meters (see line 4 of the query) away from another node tagged as ford.

**Comment by AllroadsNL** [comment]
Thanks, i am not a code man, just my first steps, to find some data, I want.  With this last query, I must dig in to it, do some reading, how this is done. 

Maybe this topic is now going the way, less code is better. To understand and make it more usable for the bigger group, who not are so much into codes.

It looks so logic.
To give in some radius possibilities.
A few more digits.
That was my approach, at first.
Then here is it right place, I believe.

Not sure, if there where, coding solutions.
I keep it in mind to ask there and tag it. For coding solutions.

I leave it open for a few days and the close it if there is no discussion anymore.

**Comment by mmd-osm** [comment]
@AllroadsNL : can you at least validate the results of that last query and state if they meet your requirement, if if not, what kind of issues you see?  You don't have to understand it.

Just a clear:
*  (a) Yes, it's perfectly ok, let's close this issue, or
*  (b) No, because of ... (state some reason here) ... 

Again the reminder: If you're interested in community discussions , please head for [Help OSM](https://help.openstreetmap.org). There's a much larger audience here, which you will never find in a bug tracking system.

**Comment by mmd-osm** [comment]
btw: if you like you can close the ticket right away and re-open it, if you feel the need for it. There will be no further discussion from my side as well.
