### ISSUE TITLE
casting & alignment

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#316]
Placeholder for discussion on void\* → uint32 (et al.) casting and related alignment issues.

See also:
- [EXP36-C. Do not cast pointers into more strictly aligned pointer types](https://www.securecoding.cert.org/confluence/x/tgAV)
- https://github.com/mmd-osm/Overpass-API/commit/ffaa9348da68320ed397a35a7ef85f06136f5efe
- 50d2e9c5b488f802c8fdbdeaaf381567e4059447

**Comment by drolbr** [comment]
Note that the C-Standard does not apply here (in a strict sense). It is all about C++, and that is a standalone standard (despite the often-used term "C/C++").

Nonetheless, we should end up with an approach that is standard conforming as well as works with at least GCC and LLVM.

**Comment by mmd-osm** [comment]
Note: there's a similar guideline available for C++ as well: [link](https://www.securecoding.cert.org/confluence/display/cplusplus/VOID+EXP56-CPP.+Do+not+cast+pointers+into+more+strictly+aligned+pointer+types). I just referes back to EXP36-C, as it fully covers the issue for C++ as well.

**Comment by mmd-osm** [comment]
test-bin/file_blocks crashes on g++ 5.4.0 with `-O3`, but works fine with `-O3 -fno-tree-vectorize`

```
This block of read tests is complete.
** Test the behaviour for a file with one entry - part 1

Program received signal SIGSEGV, Segmentation fault.
0x000000000040ba6a in IntIndex::to_data (data=0x636725, this=<optimised out>) at ../../src/test-bin/../template_db/file_blocks.test.cc:51
51	      *(uint32*)(((uint8*)data) + 4*i) = 4*i/3;
```


```
   0x000000000040ba49 <+233>:	punpckldq %xmm0,%xmm1
   0x000000000040ba4d <+237>:	pmuludq %xmm3,%xmm1
   0x000000000040ba51 <+241>:	punpckhdq %xmm0,%xmm0
   0x000000000040ba55 <+245>:	pmuludq %xmm3,%xmm0
   0x000000000040ba59 <+249>:	movdqa %xmm1,%xmm6
   0x000000000040ba5d <+253>:	shufps $0xdd,%xmm0,%xmm6
   0x000000000040ba61 <+257>:	movdqa %xmm6,%xmm0
   0x000000000040ba65 <+261>:	psrld  $0x1,%xmm0
=> 0x000000000040ba6a <+266>:	movaps %xmm0,-0x10(%rax)
   0x000000000040ba6e <+270>:	cmp    %r11d,%r10d
   0x000000000040ba71 <+273>:	ja     0x40ba30 <prepare_block(void*, std::__cxx11::list<IntIndex, std::allocator<IntIndex> > const&)+208>
   0x000000000040ba73 <+275>:	add    %r14d,%ecx
   0x000000000040ba76 <+278>:	cmp    %r14d,%edx
```

**Comment by mmd-osm** [comment]
Implemented in https://github.com/mmd-osm/Overpass-API, closing here.
