### ISSUE TITLE
Can't run some queries (they run out of memory)

### ISSUE THREAD

**Issue by naoliv** [drolbr/Overpass-API#319]
It seems that it's not possible to run some queries:

    An error occured during the execution of the overpass query! This is what overpass API returned:
    runtime error: Query run out of memory using about 2048 MB of RAM.

For example:
http://overpass-turbo.eu/s/iwN

    [out:json][timeout:900];
    {{geocodeArea:são paulo}}->.searchArea;
    (
      way["highway"](user:"Gabriel Vilela")(newer:"{{date:3 weeks}}")(area.searchArea);
    );
    out body;
    >;
    out skel qt;

Or
http://overpass-turbo.eu/s/iwO

    [out:json][timeout:900];
    {{geocodeArea:Brasil}}->.searchArea;
    (
      way["name"~"^Ilha "]["shop"!~".*"]["amenity"!~".*"]["building"!~".*"]["place"!="islet"]"place"!="island"](area.searchArea);
      relation["name"~"^Ilha "]["shop"!~".*"]["amenity"!~".*"]["building"!~".*"]["place"!="islet"]"place"!="island"](area.searchArea);
    );
    out body;
    >;
    out skel qt;

Is it possible to do something about this, please?

**Comment by mmd-osm** [comment]
You need to set the maxsize parameter, e.g. `[maxsize:800000000]` for the first query.

**Comment by mmd-osm** [comment]
@naoliv : again the reminder: if your question is answered, kindly close this ticket.

**Comment by naoliv** [comment]
Oh, really sorry about this.
Thank you very much!
