### ISSUE TITLE
New print mode: versioned_body

### ISSUE THREAD

**Issue by westnordost** [drolbr/Overpass-API#325]
This is a feature request.

Currently, of the two "complete" print modes, only...
**body** (default)
```
<way id="265899736">
    <nd ref="3939287164"/>
    <nd ref="3990883782"/>
    <nd ref="3990883781"/>
    <tag k="highway" v="residential"/>
</way>
```
**meta**
```
<way id="265899736" version="2" timestamp="2016-02-05T18:26:32Z" changeset="37025725" uid="1205786" user="westnordost">
    <nd ref="3939287164"/>
    <nd ref="3990883782"/>
    <nd ref="3990883781"/>
    <tag k="highway" v="residential"/>
</way>
```
...are defined. Perhaps there could be a print mode in between body and meta that includes just the version?

**versioned_body** (or named repos, osm, ... see below)
```
<way id="265899736" version="2">
    <nd ref="3939287164"/>
    <nd ref="3990883782"/>
    <nd ref="3990883781"/>
    <tag k="highway" v="residential"/>
</way>
```

**This is my use case:**
I want to make changes to the map data I retrieve from Overpass and upload these changes directly to OSM via the Api 0.6. The only additional data that is necessary for this beyond what is in "body" is the version number.
Why use Overpass at all to retrieve map data to work on? Because the application I program is a sparse editing tool that should not download all the data there is but only certain data, i.e. all roads that have no names etc. (think MapRoulette)

**Comment by mmd-osm** [comment]
I wonder what exactly your intention was to have reduced meta data. Was it just saving some space or maybe something else?

I did some tests on a random .osm file (file size 5MB) and removed parts of the meta data as suggested. While this reduced the file size of the original file by about 35%, only a mere 12% in savings was left when using gzip compression on both files. 

If you're not already using compression today, I'd suggest to enable that first.

**Comment by westnordost** [comment]
Well, not so much about saving space in the result set, but from the notion that a query that selects less data from the database is also be lighter on the hardware (faster, less memory). Overpass still has to collect all this redundant meta data from the database, the query to the DB won't be compressed. I want my app to be as light on the server's resources as possible.

Also, how much space is saved depends on the type of element selected. In a query that returns only nodes, body+version would be roughly 50% of the size of meta uncompressed.

Anyway, I found out about the `geom` print mode yesterday though and using `print meta geom;` instead of `(._;>;);print meta;` saved me about 90% of data size (uncompressed) already, so I don't mind this being closed if you think another print mode is not worth the implementation effort.

With compression you mean HTTP compression right?

**Comment by mmd-osm** [comment]
>  the notion that a query that selects less data from the database is also be lighter on the hardware (faster, less memory)

I see. In that case there's not really much of a difference, as the version number is already part of the meta data. So from a reading data from disk perspective, that wouldn't make a whole lot of a difference.

> I want my app to be as light on the server's resources as possible.

Well, that depends on both the number of requests and the complexity of each query. It's difficult to assess this point without further details.

> With compression you mean HTTP compression right?

Yes, exactly.

**Comment by westnordost** [comment]
Okay, I'll close this if you don't mind. The gain seems to be too minimal.
