### ISSUE TITLE
Multiple node versions returned - Possible DB corruption?

### ISSUE THREAD

**Issue by nchidsey** [drolbr/Overpass-API#326]
My organization has a local instance of Overpass (v0.7.51), which has been working for over a year, but recently we discovered that queries were returning incorrect results.  An example query:

```
[out:xml];  
node(min_lat,min_long,max_lat,max_long);   
out meta;    
```

Such queries now return:
- nodes outside the bbox
- multiple nodes with the **same** id/version/timestamp/changeset, but different coordinates (the coordinates look like two successive versions on the public OSM server)

The public Overpass server does not exhibit these issues.

**Comment by mmd-osm** [comment]
Please see this announcement: http://permalink.gmane.org/gmane.comp.gis.openstreetmap.overpass/275 

Your database is probably corrupted by the same bug and cannot be used anymore. Make sure to first update to the most recent version 0.7.53 (this is a mandatory step!) and proceed with either db clone or initial load.

**Comment by drolbr** [comment]
I'm not sure whether the bug applies. Nonetheless I would suggest to update the software, reload the database and see whether the issue appears again.

It could be also some hiccup in the update process or one of the other bugs that have been fixed in 0.7.53.

**Comment by nchidsey** [comment]
Software now updated and cloned.  So far so good.  We'll keep an eye out.
Thanks for the help.

**Comment by mmd-osm** [comment]
@nchidsey : can you close this issue in the meantime? You can always reopen it later, if needed. Thanks.
