### ISSUE TITLE
No CORS headers on https://overpass-api.de/api/xapi?

### ISSUE THREAD

**Issue by ahocevar** [drolbr/Overpass-API#328]
Not sure if this is the right place to report, but wasn't the above API supposed to return Acces-Control-Allow-Origin headers? It seems it stopped to do so recently.

**Comment by ahocevar** [comment]
Example request: https://overpass-api.de/api/xapi?map?bbox=6.638488769531234,46.777492763768294,6.641235351562484,46.77937368205562

**Comment by mmd-osm** [comment]
xapi?map is blocked at the moment, see this announcement: https://lists.openstreetmap.org/pipermail/talk/2016-September/076825.html

**Comment by ahocevar** [comment]
Ok thanks, that explains it.
