### ISSUE TITLE
Index rare/infrequent roles

### ISSUE THREAD

**Issue by d1g** [drolbr/Overpass-API#329]
In addition to #97, please add an index on 

* "admin_centre" role
* "via" role
* "from" role
* "to" role

background/why in https://wiki.openstreetmap.org/wiki/Automated_edits/Jojo4u

>  The alternative of using the admin_centre role of boundary relations needs pre-processing: An overpass query on all admin_level=2 borders runs longer than 3 minutes (stopped it at this point) while a overpass on all capital=yes node runs in seconds.

**Comment by jojo4u** [comment]
I have to retract that statement in the wiki. It was because of bbox not because of indizes. The following query gets all country border relations and admin_centres and is fast:
```
[out:xml];
(
  relation["admin_level"="2"]["type"="boundary"]["boundary"="administrative"];
  node(r:"admin_centre");
);
out meta;
```
The following query adds bbox like the wizard does and is very slow even if zoomed out to whole world.
```
[out:xml];
(
  relation["admin_level"="2"]["type"="boundary"]["boundary"="administrative"]({{bbox}});
  node(r:"admin_centre");
);
out meta;
```

**Comment by mmd-osm** [comment]
I've already recommended to remove the `{{bbox}}` part in this forum post [link](http://forum.openstreetmap.org/viewtopic.php?pid=612628#p612628) last week, exactly to avoid this performance issue.

**Comment by jojo4u** [comment]
d1g is coming from another [thread]( http://forum.openstreetmap.org/viewtopic.php?id=55959) where this information was not added.

**Comment by mmd-osm** [comment]
OK, I see. Are we good to close this issue then, as there's a reasonable workaround available?

**Comment by jojo4u** [comment]
I'm ok with it

**Comment by mmd-osm** [comment]
BTW: If anyone's looking for admin centres in the current bbox and stumbles across this issue, the following approach would be an option:

```
relation["admin_level"="2"]["type"="boundary"]["boundary"="administrative"];
node(r:"admin_centre");
node._({{bbox}});

out meta;
```
