### ISSUE TITLE
Compact loses ",i" in regex, so case-insensitive matches become case-sensitive if compacted 

### ISSUE THREAD

**Issue by jim-snyder-grant** [drolbr/Overpass-API#330]
Gave this to convert_form at http://overpass-api.de/convert_form.html and asked for compact overpass QL.
  ```
[bbox:42.433,-71.5,42.534,-71.384];    
way[highway="path"][name~"yellow",i];
 (._;>;);
out;
```
The output lost the",i" and thus the case-insensitive search became case-sensitive (returning an empty set):
`[bbox:42.433,-71.5,42.534,-71.384];way["highway"="path"]["name"~"yellow"];(._;>;);out body; `

**Comment by mmd-osm** [comment]
We have some more candidates with similar issues:

##  Key Regex
* `way[highway="path"][~"name"~"yellow"];`
* `way[highway="path"][~"name"~"yellow",i];`

Both are converted to `way["highway"="path"][~"yellow"];`

**Comment by jim-snyder-grant** [comment]
I agree with @mmd-osm  comments - will close this & follow  #188
