### ISSUE TITLE
Queue queries when rate limit is exceeded

### ISSUE THREAD

**Issue by Rudloff** [drolbr/Overpass-API#331]
Hello,

Would it be possible to have an option so that when I want to run a query and I already have two other queries running, it queues the new one (just keep the HTTP connection open and wait for the other two to finish) instead of returning a 429 error? Or would that use too much resources?

**Comment by mmd-osm** [comment]
I think you should evaluate `/api/status` and rather do the queuing on your end.

**Comment by drolbr** [comment]
Thank you for the suggestion. The server already does so. It holds queries up to 15 seconds.

If you think this does not work, then please tell me details of your use case. I will then check whether there is unexpected behaviour.
