### ISSUE TITLE
db update - download minutely, hourly, daily diffs as needed

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#336]
See: https://github.com/openstreetmap/operations/issues/121#issuecomment-259126369
A lot of the times I have noticed people doing it I suspect they are catching up render servers or nominatim servers rather that overpass, but they let them get six months out of date and then try and catch them up using minutely diffs rather than reimporting or using daily diffs to do most of the catch up.

**Comment by drolbr** [comment]
As we know from the Augmented Diffs discussion the various sources of diff do not necessarily match up properly.

As I would prefer people to start by cloning anyway, I don't think I would devote effort to develop any sophisticated handover between the various diff series.
