### ISSUE TITLE
Can't run some queries (they time out)

### ISSUE THREAD

**Issue by SergeFranchois** [drolbr/Overpass-API#337]
Hello

I'm hosting my own Overpass server, set up as detailed here:
http://wiki.openstreetmap.org/wiki/Overpass_API/Installation

Some area queries appear problematic.
The OSM data I tried are :  planet, europe and belgium.

```
[root@....]# osm3s_query
encoding remark: Please enter your query and terminate it with CTRL+D.

[out:json][timeout:90000000][maxsize:8000000000];
area(3600052411) -> .myArea;
(
  relation["boundary"="administrative"]["admin_level"="6"](area.myArea);
) ;
(._;>;);
out geom;

runtime error: open64: 0 Success /osm3s_v0.7.53_osm_base Dispatcher_Client::request_read_and_idx::timeout
```

This query seems to use a lot of memory. The server has 28GB of RAM and 4 cores.
Even though i hint the server with a large timeout, it times out anyway within a minute or so.

How can i configure the Overpass server to pull through?

**Comment by mmd-osm** [comment]
I could successfully run this query on the public instance:

```
[maxsize:200000000];
area(3600052411) -> .myArea;
relation["boundary"="administrative"]["admin_level"="6"](area.myArea);
(._;>;);
out geom;
```

Can you check this on your instance as well?

**Comment by SergeFranchois** [comment]
I tried your query (w/o the directives).  Then I get this

`runtime error: Query run out of memory using about 8192 MB of RAM.`

What public instance did you try it on? https://overpass-api.de ? 

Thanks for looking into this!

**Comment by mmd-osm** [comment]
Yes, I tested this on overpass-api.de.

**Comment by SergeFranchois** [comment]
Ok, I wonder now what is different on my server with the public one.
Are their any tweaks needed on the server to avoid the constraints (timeout, memory)? 
Where is the 8GB RAM limitation coming from; I have a 28GB server so I don't understand why i hits that limit.
Thanks again

**Comment by mmd-osm** [comment]
The dispatcher has some command line arguments to set its limits:

```
  --space=number: Set the memory limit for the total of all running processes to this value in bytes.
  --time=number: Set the time unit  limit for the total of all running processes to this value in bytes.
  --rate-limit=number: Set the maximum allowed number of concurrent accesses from a single IP.
```

As this Github issue tracker is for bug reports and enhancement requests only, I'd like to ask you to follow up any operations related questions on the Overpass Dev Mailing List: http://listes.openstreetmap.fr/wws/info/overpass

**Comment by mmd-osm** [comment]
Issue can be closed, fix is in https://github.com/drolbr/Overpass-API/commit/412a33f9d653691340d4d69bb76dd260fcf212e4

**Comment by mmd-osm** [comment]
@SergeFranchois : as you've already started a follow up on the Overpass ML, and this issue here doesn't require any further action, I'd kindly ask you to close this issue. Thanks.
