### ISSUE TITLE
out:pbf

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#339]
See announcement on ML: http://gis.19327.n8.nabble.com/PBF-output-prototype-available-for-testing-td5884534.html

**Demo: overpass turbo with PBF support** [link](http://overpass-turbo.eu/turbo/build/pbf/?q=LyoKVGhpcyBzaG93xIZhbGwgbW91bnRhaW7EhihwZWFrcykgxJcgdGhlIERvbG9taXRlcy4KWcSSxJBheSB3YcSUxKNvIHVzxKbEpMSmInpvxKsgb8SUxL1kYcSVIiBidXR0xYkuID0-CiovCgpbxJJ0OnBiZl07xZ0vL8SHxJxyY2jEo8SlIGFyxJzFiGbFsMSmxKhsxKzErnMKxbPEnAogIFtwbGFjZT3FtGdpxYldxoLGhCLGjMaObjp0ecSbIj0ixJHEk8SVxJdfxoBhIsaQxoNbIm5hbWU6ZW7GmyLFusSrxK3Er8alxacKxakgZ2V0xbLEjiDEm8SdxIbEosWCxbLFtGEKKMaRbm9kZcaRW8aqdHVyxI09x4JrxqYgKMajKca4xrphZGTErcaVxI1seSzEh8SJd8W4xYjFkmzEl8Smb8W3x4bGowrFtMaHdMaVx5HGhsaIxorGlMaPx5HGk2XGjcWJxpfGmWXGscaexJTElm7GoseIxqXIg8aqxqzGrsawxpzGs8W8xrbFpgo-xafGg8efCsWgxJDGvWHGuHt7xYzElTpvdmVycGFzcyzFgHLIrnI9aMWTcDrFqcePdi7IrcivyLHIsy1hcGkux48vyYhpX21tZC99fQ&c=BOkTqxG9wJ)

JOSM support for Overpass API + PBF format: https://josm.openstreetmap.de/changeset/11916/josm

**Comment by philipgriggs** [comment]
is there any progress getting this from the dev server and onto `overpass-api.de`?

**Comment by mmd-osm** [comment]
Implemented in https://github.com/mmd-osm/Overpass-API, closing here.
