### ISSUE TITLE
Dispatcher: event based processing

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#340]
The following prototype replaces the poll based dispatcher by an event based implementation using libevent. Dispatcher now responds within 0,2ms and consumes no CPU time at all when no request are being processed. One of the main use cases is clearly support for mobile scenarios with a very large number of very small requests.

Combined with FastCGI and [Index file caching](https://github.com/drolbr/Overpass-API/commit/469ff37613fd38c73e649d06a60411c4573bab82), the dispatcher can now handle around 500 requests per second on the dev instance (very simple query for amenity nodes in a small bbox), instead of about 30 requests/s on api_drolbr. Also, we can achieve response times in the range of 15ms-70ms, like in the following example: http://overpass-turbo.eu/s/kaT 

![perf](https://cloud.githubusercontent.com/assets/5842757/20454477/44611bac-ae42-11e6-82cd-1d0d967f7be6.png)

Relevant changes: https://github.com/mmd-osm/Overpass-API/commit/c81e9ae748fb9ebd47343aa83ce0bfb5c764f8e5

Changes to dispatcher protocol:
* Removed initial packet to transmit PID - this can be determined via `getsockopt(client_fd, SOL_SOCKET, SO_PEERCRED, ...` (not very portable, though! For FreeBSD we need to keep this part)
* Dispatcher clients: instead of sending multiple uint32 messages, several uint32 are combined into one single message (see Dispatcher_Client::request_read_and_idx) as an example

Prototype was tested with read and write db options.

Interactive Demo: http://umap.openstreetmap.fr/de/map/postbox-overpass-api-dev-server-demo_112819#12/49.0209/8.3858

---

Some ideas for configure.ac for libevent detection & `--enable-libevent` configure option:

* https://git-wip-us.apache.org/repos/asf?p=mesos.git;a=blob;f=configure.ac;h=7a18c89854c1f42bec09f067579b72114fb8ec1d;hb=HEAD#l1179
* https://github.com/torproject/tor/blob/master/configure.ac#L472-L583

**Comment by arungowtham** [comment]
Hi @mmd-osm ,
                        The change seems great! , may i know when this prototype will be released for production usage.

**Comment by sreeramvuppala** [comment]
Hi @mmd-osm ,

Do you have an email address where I could reach out? I would like to know the existing options to enable the above feature in a docker.

**Comment by mmd-osm** [comment]
@sreeramvuppala : the above feature is still in prototype status, i.e. it is not meant for general use outside of the core team. Due to lack of capacity there's currently no working Docker image avaialble. Sorry for the inconvenience.

**Comment by sreeramvuppala** [comment]
@mmd-osm thank you for the update.

**Comment by mmd-osm** [comment]
Further tests in 2017:

Test case: [out:json];node(61634591);out; with node id continuously increasing. 32 parallel processes via jmeter, run on server (no network overhead), minutely updates + delta area update active.

![grafik](https://user-images.githubusercontent.com/5842757/29888246-94636b2e-8dc0-11e7-8540-a0a2a2741c9f.png)

![grafik](https://user-images.githubusercontent.com/5842757/29888256-9def8646-8dc0-11e7-8f42-92e884c1dfc7.png)

![grafik](https://user-images.githubusercontent.com/5842757/29888306-c42c8de0-8dc0-11e7-9352-5b889a6e8c8e.png)

![grafik](https://user-images.githubusercontent.com/5842757/29888310-c91a0c88-8dc0-11e7-91bd-a62696c14c55.png)

![grafik](https://user-images.githubusercontent.com/5842757/29888317-cdbe5a14-8dc0-11e7-9d1c-9ac5268235eb.png)

**Comment by mmd-osm** [comment]
https://github.com/mmd-osm/Overpass-API/commit/d5e90893ef92f166eb0428954aa0b90a73deb042 implements the same idea using epoll_*. Although it is linux only, this won't introduce additional third library dependencies.

**Comment by dovka** [comment]
Guys, sounds very exiting! When can we expect it in the general release?
Any plans for multiple dispatcher workers?

We use v0.7.55 overpass API with high volume of requests and unfortunately the maximum we can get on m4.xlarge instance is 130 requests per second.

Over that we start getting 502 bad gateway from our nginx.
Nginx configuration is sound and the only bottleneck is the single dispatcher process.

Would really appreciate any feedback!
Thank you,

**Comment by mmd-osm** [comment]
@dovka : having multiple dispatchers of the same type is not supported on architecture level and that’s quite difficult to change. This issue is about making one dispatcher scale much better first. What’s the throughput you’re trying to achieve on your platform?

**Comment by dovka** [comment]
Dear Roland,
thank you very much for the quick answer.
I want to thank you for the impressive product - we are very happy using overpass API for our project,
just hit a snag trying to scale it.
I wasn't able to find much info on dispatcher tuning, if you can point me in the right direction,
I'd really appreciate it.
We run our overpass service on m4.2xlarge, which has 8 cores and 32G of RAM.
It gets runs 130 requests per second without errors, 140 requests per second already starts showing 502 bad gateway, while consuming only 15% of the CPU available.

Configuration details are here:
https://stackoverflow.com/questions/53950297/nginx-fcgiwrap-throws-502-bad-gateway-at-high-request-rate

Appreciate your help!
David

**Comment by mmd-osm** [comment]
By the way, no Roland here, Roland is @drolbr.

There’s not much you can do in terms of tuning the dispatcher in 0.7.55. Better scalability can only be achieved via a fix in the source code.

Again my question: how many requests per second do you want to achieve?

**Comment by dovka** [comment]
Sorry for the mix up :)
If I'm using 15% of CPU with 140 requests/second, it is natural to hope to scale this server to 900-1000 requests per second.

We currently work around the problem by using 8 times smaller instance t2.medium.
So we run 8 instances instead of one, however this is more expensive because DB has to be duplicated for each node.

**Comment by mmd-osm** [comment]
Yes that makes sense. Once the fix has been released I would expect 1500-2000 small queries per second on an 8 core system, though I would recommend to use more than 32GB main memory in that case.

Are you updating your database via update_from_dir? If not, you could probably use a central directory for all database files and symlink each single file to a local directory, and run the dispatcher on the local directory. This will NOT work when updating the database every minute as the local dispatcher will see inconsistent data and your interpreter binary will probably crash in that case.

**Comment by dovka** [comment]
Great!
Any idea when it might be released?
We load custom map data via update_database, always a complete load.
Wouldn't risk on the shared db storage - might be cheaper but easy to create a bottleneck.

Thank you very much for your answers - 
very timely and helpful :)

**Comment by mmd-osm** [comment]
Implemented in https://github.com/mmd-osm/Overpass-API, closing here.
