### ISSUE TITLE
Can not connect to rambler.ru server

### ISSUE THREAD

**Issue by CrazyBean** [drolbr/Overpass-API#341]
--2016-11-22 20:55:32--  http://overpass.osm.rambler.ru/cgi/xapi_meta?*[bbox=-92.06,34.09,-91.77,34.3]
Resolving overpass.osm.rambler.ru... 81.19.69.32
Connecting to overpass.osm.rambler.ru|81.19.69.32|:80... failed: Operation timed out.
Retrying.

The server can not be connected. If I try to connect the remote server on Ubuntu system, it will show connection failed error. If I try it on Mac system, it will show the above error.

**Comment by mmd-osm** [comment]
That's a known issue. Please see this status page: http://wiki.openstreetmap.org/wiki/Overpass_API/status

Kindly request to close this issue, Github is only used for software bugs and enhancement requests. It is not intended to report operational issues.

**Comment by mmd-osm** [comment]
btw: please switch to one of the other instances for the time being.

**Comment by CrazyBean** [comment]
Could you give me the address of one of the other instance? Thanks

**Comment by ImreSamu** [comment]
>Could you give me the address of one of the other instance?

see  public visible instances: 
http://wiki.openstreetmap.org/wiki/Overpass_API#Introduction
