### ISSUE TITLE
out geom: relations without ways'  nodes in json mode

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#348]
`out geom;` for relations used to return all ways' nodes in the json response. This is no longer the case for `out_csv_finetuning` branch on //dev.overpass-api.de/api_deriveds/

```
[out:json];
rel(6221517);
out geom;
```

Before:

![grafik](https://cloud.githubusercontent.com/assets/5842757/21072700/85b1b3e8-becb-11e6-8acf-ba8ef65690a3.png)

After:

![grafik](https://cloud.githubusercontent.com/assets/5842757/21072705/a16d9d54-becb-11e6-83dc-b75994cb89b1.png)

**Comment by drolbr** [comment]
Fixed in 2e061689adac952e6b9d29ed382c4bcc1d2e467f

However, out:json does not output a useful diff format at the moment. I think it never has, although the kind of nonsense changed.
