### ISSUE TITLE
Live data in Overpass using Docker Container

### ISSUE THREAD

**Issue by gerbsen** [drolbr/Overpass-API#362]
hello,
I've installed the overpass-api on my dev server. everything is working fine for now. could you please tell me if it is possible to auto-insert osm changesets? and if so, how?

cheers,
daniel

**Comment by gerbsen** [comment]
I found a better Docker Container here: https://github.com/Frankkkkk/docker-overpass-api

It's a shame that this is at the bottom of a mile long readme file.

**Comment by mmd-osm** [comment]
At this time, Docker is not officially supported yet, so we have basically no idea, what Docker container or documentation you are refering to in this issue. There's an enhancement request out there: https://github.com/drolbr/Overpass-API/issues/318. However, it is for Roland to decide, if a Docker image will ever become part of the official release. 

Please direct all issues regarding Docker images to the respective owner for the time being.
