### ISSUE TITLE
No error when querying adiffs with json output format

### ISSUE THREAD

**Issue by tyrasd** [drolbr/Overpass-API#363]
When running an augmented diff query with the output format set to json, one doesn't get warning or error message, even though adiffs aren't (yet?) supported in the json output format. Instead, one get "normal looking" OSM-JSON data. (I think this may also affect other output formats.)

**Comment by drolbr** [comment]
Fixed in e1ff7dbddc2b3b3f551b6b6322ab454aa2097fe1
