### ISSUE TITLE
Ability to filter by version

### ISSUE THREAD

**Issue by baditaflorin** [drolbr/Overpass-API#369]
Now, i can get from overpass all of my edits that i did in one day. 
http://overpass-turbo.eu/s/nmW

But if i want to filter to see just the new edits (version=1) or if i want to see just the older relations that i have modified, and not added today, i cannot. 

It would be useful to be able to filter by version number.

**Comment by mmd-osm** [comment]
That's in fact a duplicate of #367. Hence, could you please close this issue and follow up on the other issue I mentioned?

**Comment by mmd-osm** [comment]
Implemented in https://github.com/drolbr/Overpass-API/issues/219
