### ISSUE TITLE
count_members() can't take arguments

### ISSUE THREAD

**Issue by grischard** [drolbr/Overpass-API#376]
I'd like to find multypolygons with more than one outer member. `count_members(r:outer) > 1` would be perfect if it worked.

**Comment by mmd-osm** [comment]
The following query should do, although it's a bit complicated:

```C
[bbox:{{bbox}}];
rel[type=multipolygon];
foreach -> .a (
  way(r.a:outer);
  way._(if:count(ways) == 2);
  rel.a(bw);
  out;
);  
```

**Comment by grischard** [comment]
Oh yes! Thank you!

**Comment by somehundred** [comment]
For those who try this query but encounter that no data is visually displayed, add `geom` after `out` to fix it. The query becomes like this:

```
[bbox:{{bbox}}];
rel[type=multipolygon];
foreach -> .a (
  way(r.a:outer);
  way._(if:count(ways) > 1);
  rel.a(bw);
  out geom;
);  
```
