### ISSUE TITLE
13 Permission denied /osm3s_v0.7.54_osm_base

### ISSUE THREAD

**Issue by ChrissW-R1** [drolbr/Overpass-API#377]
After installing the Overpass API on a CentOS server and importing the whole world, I got the following issue on every request to the /api/interpreter

Error: runtime error: open64: 13 Permission denied /osm3s_v0.7.54_osm_base Dispatcher_Client::1

Both files on /osm3s/data/db/ and /dev/shm/ were created by the service with the permissions 0666. On shutdown the service these files will removed. So every seems right on this site.

Any idea, what's wrong in my configuration?

**Comment by mmd-osm** [comment]
This might be something centos specific, like SElinux being active, which
would block some kernel calls for security reasons.

Better ask on some centos forum, why shm_open failed with return code 13.
Don't forget to also check apache log files.

Never seen this issue on Debian or FreeBSD.

Sorry, I guess you need to investigate this on your own.


ChrissW-R1 <notifications@github.com> schrieb am Di. 14. März 2017 um 08:53:

**Comment by olearytd** [comment]
I'm having the same issue, set selinux to permissive and did a restart but having the same problem.

Going to try turning it off completely and test but I don't really want to do that as its not advisable

**Comment by mmd-osm** [comment]
@olearytd : please keep us posted on your progress. If possible, can you attach a system trace using strace, which illustrates the issue?

**Comment by olearytd** [comment]
so I got this working, it might a combination of selinux since I still have my server set to `permissive` but I changed the db directory location to inside my build directory

build/db

And that seemed to clear up any permission issues I had

**Comment by ibexmonj** [comment]
I am seeing the same issue. 

I set selinux to permissive. Any clues on how to proceed here ?

Mar 31 10:12:41 localhost.localdomain systemd[1]: Starting Overpass API dispatcher daemon...
Mar 31 10:12:41 localhost.localdomain systemd[1]: Started Overpass API dispatcher daemon.
Mar 31 10:12:41 localhost.localdomain dispatcher[2321]: File_Error Address already in use 98 /home/osm/overpass/data/db//osm3s_v0.7.52_osm_base Unix_Socket::4
Mar 31 10:12:41 localhost.localdomain dispatcher[2322]: File_Error No such file or directory 2 /osm3s_v0.7.52_osm_base Dispatcher_Client::1

**Comment by olearytd** [comment]
It's your database location. Mine was also in my home directory and was getting this issue. 

To get around this, I built overpass in /usr/local/ 

And then built the database inside /usr/local/overpass/build/db/

This fixed my permission issue

**Comment by ibexmonj** [comment]
@olearytd 

                I changed the install dir to "/home/osm/overpass" and the data dir to "/home/osm/data/db". Still running as user root while i was testing in my VM ;) 

Anyways, got it to work after changing 2 things:
1. remove the osm file  in the data/db dir.
2. change selinux to permissive. 


Btw, i do not have a build dir ? All i have is data and bin. Am i missing something ?

Sorry if I am coming across as a noob. I am helping set this up for someone else and im not too familiar with overpass.

Here is my fpm command i used:

 /usr/local/bin/fpm -s dir -t rpm -n overpass-api -v 0.7 --iteration 52 --exclude bin/.dirstamp --exclude bin/.libs --after-install post-install --after-remove post-remove --prefix /home/osm/overpass bin/

**Comment by mmd-osm** [comment]
> To get around this, I built overpass in /usr/local/
> And then built the database inside /usr/local/overpass/build/db/

The recommended way is to specify your target directory via `configure --prefix=...` and do a `make install` afterwards (probably you need sudo as well for that). There's really no need to build the binary in /usr/local and keep the source directory later on.

See http://wiki.openstreetmap.org/wiki/Overpass_API/Installation

@ibexmonj : before continuing you should really update to 0.7.53. The version 0.7.52 you're using has known issues with 64 bit node ids.

**Comment by ibexmonj** [comment]
@mmd-osm 
            Appreciate the info on the package. I see a 0.7.54, perhaps i should get that ? 

Also, here are the steps i followed from the Wiki:

1. ./configure CXXFLAGS="-O3" --prefix=/home/osm/overpass
2. /usr/local/bin/fpm -s dir -t rpm -n overpass-api -v 0.7 --iteration 52 --exclude bin/.dirstamp --exclude bin/.libs --after-install post-install --after-remove post-remove --prefix /home/osm/overpass bin/

One quirk was, I had to move the `overpass-api.sevice` file in the bin/ dir and then run the fpm command or else it was not being packaged.  It was not something that was obvious from the Wiki instructions.

**Comment by mmd-osm** [comment]
Current release would be 0.7.54: http://dev.overpass-api.de/releases/osm-3s_v0.7.54.tar.gz -it is still quite new, and has a two known issues wrt CSV output and one wrt `/api/convert` endpoint. If you don't need those, you should be good to go with 0.7.54.

I wouldn't use `CXXFLAGS="-O3"` but rather ` CXXFLAGS="-O2"` at this time, as some compilers (e.g. gcc5) produce AVX optimize code which segfaults due to unaligned memory access.

Regarding `fpm` I'm afraid I cannot really recommend anything, as I'm not familiar with CentOS specifics.

**Comment by ibexmonj** [comment]
no worries. Appreciate the input here @mmd-osm

**Comment by ChrissW-R1** [comment]
I could solve this issue by set selinux to permissive and set extended rights to the db directory and /dev/shm

Thanks all for the hints.
