### ISSUE TITLE
cannot convert query to ql format anymore

### ISSUE THREAD

**Issue by tyrasd** [drolbr/Overpass-API#378]
[originially reported by Giovanni Cascafico on talk-it: https://lists.openstreetmap.org/pipermail/talk-it/2017-March/057760.html]

On http://overpass-api.de/query_form.html, it's not possible to convert xml queries to (pretty or compact) ql format anymore (converting from ql to xml seems to still work):

* http://overpass-api.de/api/convert?data=%3Cosm-script%3E%3C%2Fosm-script%3E&target=compact 
* http://overpass-api.de/api/convert?data=%3Cosm-script%3E%3C%2Fosm-script%3E&target=mapql

the error message reads:

    Unknown argument: --dump-pretty-map-ql

**Comment by tyrasd** [comment]
Maybe it's just a simple typo, since `osm3s-query` seems to expect a [`--dump-pretty-ql` parameter](https://github.com/drolbr/Overpass-API/blame/a3ab379733cbf89835a1722204d7a5fe459209aa/src/overpass_api/dispatch/osm3s_query.cc#L102)?

**Comment by mmd-osm** [comment]
Further patch: https://github.com/drolbr/Overpass-API/commit/5e354095db578a69836f120df27e72458fecc946 removes `-map` everywhere
