### ISSUE TITLE
(Multi)polygon fixing effort

### ISSUE THREAD

**Issue by joto** [drolbr/Overpass-API#380]
There is a major effort going on to fix broken (multi)polygons in OSM and also to finally get rid of *old-style* multipolygon relations. This will hopefully lead to simpler and more efficient software. There is no immediate need for you to change anything in Overpass, but I would expect there to be opportunities to simplify your code and generally make life easier for you once this effort is successful.

I wanted to make you aware of the effort and get you involved in the discussions. We'd also appreciate it if you can support this effort in any way. Find all the details at http://area.jochentopf.com/. We are coordinating with other software project through our issue osmlab/fixing-polygons-in-osm#23.

**Comment by drolbr** [comment]
I'm sorry for the late answer. On first look, Overpass API is agnostic to the polygon tagging style. Hence, I had postponed the response. On a second look, Overpass API does depend on the tagging style in the areas rules. But those work anyway only with new style polygons. Hence, there is probably nothing to do.

I will leave this issue open as an information channel until the meta-issue is closed.

**Comment by drolbr** [comment]
The meta-issue has in the meanwhile succeeded.
