### ISSUE TITLE
Timeout returns empty result instead of error

### ISSUE THREAD

**Issue by erabrahams** [drolbr/Overpass-API#382]
Using the Overpass Python API, a query with a short timeout (1-30s) returns an empty result object instead of any error; for example, a 504 Gateway Timeout (which seems like the logical exception).

For example, the query:
```
[out:xml][timeout:10];
area["name"="France"]->.searchArea;
(
node["amenity"="embassy"](area.searchArea);
way["amenity"="embassy"](area.searchArea);
relation["amenity"="embassy"](area.searchArea);
);
out center;
```
performed like so:
`result = overpy.Overpass().query(query))`
returns an empty list [] for each of the following:
```
print(result.get_nodes())
print(result.get_ways())
print(result.get_relations())
```
instead of raising a gateway timeout. Examining the underlying .query() function, this code, pulled out of the overpy source:
```
try:
    f = urlopen("http://overpass-api.de/api/interpreter", query)
except HTTPError as e:
    f = e
response = f.read(4096)
while True:
    data = f.read(4096)
    if len(data) == 0:
        break
    response = response + data

print(response)
print("\nf.code: "+str(f.code))
```
returns:

```
b'<?xml version="1.0" encoding="UTF-8"?>\n<osm version="0.6" generator="Overpass API">\n<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>\n<meta osm_base="2017-03-17T15:40:02Z" areas="2017-03-17T06:44:02Z"/>\n\n<remark> runtime error: Query timed out in "query" at line 1 after 2 seconds. </remark>\n\n</osm>\n'

f.code: 200
```

thus seems to indicate that the error is actually of type _exception.OverpassUnknownContentType(content_type)_, and is being handled by the line
```
if content_type == "application/osm3s+xml":
                return self.parse_xml(response)
```
which of course returns an empty result. 

This interaction suggests that Overpass is not correctly identifying the problem when a short-term timeout occurs. For longer thresholds (~300s), the appropriate 504 error is returned.

**Comment by mmd-osm** [comment]
Please report issues with the Python wrapper here: https://github.com/mvexel/overpass-api-python-wrapper

**Comment by erabrahams** [comment]
I don't think this is a problem with the API, though.

**Comment by mmd-osm** [comment]
There's "Overpass API" and "Overpass API python wrapper". Which one are you talking about?

**Comment by erabrahams** [comment]
The regular API.

**Comment by mmd-osm** [comment]
> I don't think this is a problem with the API, though.
     ^^^^^

> The regular API.

So this looks like, you're reporting the issue in the wrong place, then.

**Comment by erabrahams** [comment]
I considered that, but the reason I posted it here is that I believe the error is on the Overpass end. The error code returned by Overpass on a timeout does not match with what is expected.

**Comment by mmd-osm** [comment]
Please see this thread on error handling: https://github.com/drolbr/Overpass-API/issues/94

If you receive a `<remark>` in your response, this really indicates an error. HTTP status codes are not the only approach to signal error conditions. If this is not handled properly in the python wrapper, then the python wrapper needs to be fixed.

**Comment by erabrahams** [comment]
Interesting. Yeah that sounds like what is going on, I will bring that up over there. Thanks for your help!

**Comment by mmd-osm** [comment]
Follow up issue: https://github.com/DinoTools/python-overpy/issues/62

Kindly request to close this issue then. Thanks!
