### ISSUE TITLE
HowTo: Apply and remove state change files

### ISSUE THREAD

**Issue by ChrissW-R1** [drolbr/Overpass-API#388]
Is there a possibility to apply the OSC files and remove them after a successful import?

If I use the daemons to download and apply all changes, the required disk space will rapidly increasing!

**Comment by mmd-osm** [comment]
Im afraid that's not supported out of the box. You need to adjust the respective shell scripts on your own according to your requirements.

**Comment by ChrissW-R1** [comment]
Ok, but in my opinion this could be a very useful feature for the future...

**Comment by mmd-osm** [comment]
Correction: you should take a look at fetch_osc_and_apply.sh. I think it does exactly what you plan to do.

**Comment by ChrissW-R1** [comment]
Nice, but if I understand the code correctly, this script doesn't support the *meta=attic option*, right? Only *meta=yes* or no meta.

**Comment by mmd-osm** [comment]
Right. The script hasn't been updated in a while and doesn't cover yet attic mode. However there's no technical reason to keep it that way. If you like you can provide a pull request to include attic support for this script.

**Comment by ChrissW-R1** [comment]
Ok, I added this function to the script.

See #390
