### ISSUE TITLE
Timeout for large query

### ISSUE THREAD

**Issue by gerbsen** [drolbr/Overpass-API#389]
hey there,
I'm trying to do the following query on my own and the public endpoint (overpass-api.de). Strangly it's working in the web gui but not via POST in my code

    [maxsize:12147483648][timeout:3600][out:json]
    [bbox:47.2701115,5.8663425,55.0815,15.0418962];
    (
      node['tourism'='hotel'];
      way['tourism'='hotel'];
    );
    out center;

I always receive this:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
      <meta http-equiv="content-type" content="text/html; charset=utf-8" lang="en"/>
      <title>OSM3S Response</title>
    </head>
    <body>
    
    <p>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.    </p>
    <p><strong style="color:#FF0000">Error</strong>: runtime error: open64: 0 Success /osm3s_v0.7.54_osm_base     Dispatcher_Client::request_read_and_idx::timeout. The server is probably too busy to handle your request.
     </p>
    
    </body>
    </html>

I also tried to fiddle around with `--time` and `--space` params for the dispatcher but then I get error messages during startup (file not found).

cheers,
daniel

**Comment by mmd-osm** [comment]
> I also tried to fiddle around with --time and --space params for the dispatcher but then I get error messages during startup (file not found).

That's basically the correct thing to do: your query is requesting too much memory which the dispatcher does not allow with the default setting. However, you cannot provide `--time` and `--space` parameters during statup! You first have to start the dispatcher without those parameters, and then call dispatcher again, providing `--time` and/or `--space` parameters. You can check the result afterwards by calling `dispatcher --status`.

**Comment by gerbsen** [comment]
hey there, thanks for the update! Could you elaborate why I need to do that in that way? Also I'm using a dockerized version of this, not quite sure how to incorporate this there..

**Comment by mmd-osm** [comment]
Well, as mentioned, the maxsize 12147483648 corresponds to 12GB. That's too much for the default, that's way the query won't get executed. Maybe try a smaller maxsize first, or a smaller bounding box.

**Comment by gerbsen** [comment]
hey @mmd-osm, I now tried your suggestions but they did not work out. I've started overpass as always and then called the dispatcher again as you suggested.

    root@f49249c56193:/Overpass-API# src/bin/dispatcher --time=86000 --space=8000000000
    root@f49249c56193:/Overpass-API# src/bin/dispatcher --status
    Number of not yet opened connections: 0
    Number of connected clients: 63
    Rate limit: 0
    Total available space: 8000000000
    Total claimed space: 6442450944
    Average claimed space: 10830905827
    Total available time units: 86000
    Total claimed time units: 400
    Average claimed time units: 1217
    Counter of started requests: 995
    Counter of finished requests: 990
    202 358 0 4294967296 0 1491894153
    202 1962 2886809089 536870912 100 1491894451
    202 1958 2886809089 536870912 100 1491894450
    202 1957 2886809089 536870912 100 1491894450
    202 1964 2886809089 536870912 100 1491894451
    pending 1918
    pending 1966
    pending 1967
    pending 1968

But still the server simply drops the query after a certain amount of time (less than a minute) with:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
      <meta http-equiv="content-type" content="text/html; charset=utf-8" lang="en"/>
      <title>OSM3S Response</title>
    </head>
    <body>
    
    <p>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.    </p>
    <p><strong style="color:#FF0000">Error</strong>: runtime error: open64: 0 Success /osm3s_v0.7.54_osm_base     Dispatcher_Client::request_read_and_idx::timeout. The server is probably too busy to handle your request.
     </p>
    
    </body>
    </html>

Also I don't understand why this is happening, this query is the only one that is running on the server. Why does overpass quit so easy? Is there a way to debug this more precisely, I mean the error message for me, at least, is not that specific.

Anyway, thanks for your promt help so far! Daniel

**Comment by gerbsen** [comment]
Okay, I think I didn't follow your orders precisely enough :)

What I do now:

1. Start overpass with the params "twice"

    $BINDIR/dispatcher --osm-base --meta --db-dir=$DBDIR &
    $BINDIR/dispatcher --time=86000 --space=8000000000

2. Increase request timeouts for my nginx reverse proxy

    proxy_connect_timeout       300;
    proxy_send_timeout          300;
    proxy_read_timeout          300;
    send_timeout                300;

3. Query without any size restriction:

    [timeout:3600][out:json]
    [bbox:47.2701115,5.8663425,55.0815,15.0418962];
    (
        node['amenity'='pub'];
        way['amenity'='pub'];
    );
    out center;

So, it seems to be working now. Anyway, is there  document outlining the overall architecture of Overpass? We want to use this in our company quite a bit and I would like to know more about it.

**Comment by drolbr** [comment]
I'm sorry for the delay. I took that as a bug report from the headline and did not realize it is a question. I'm usually responding more reliably for questions on the [mailing list](http://listes.openstreetmap.fr/wws/info/overpass).

A starting point would be [html/technical_overview.html](https://overpass-api.de/technical_overview.html)

What me puzzles more is that the dispatcher in the above log thinks that it had a queue of 63 clients. You see the pids in the subsequent lines: 358, 1962, 1958, 1957, and 1964 are actively operating on the database, and the long list starting with "pending 1918", "pending 1966" is waiting for an execution slot. Is it intended to run lots of copies in parallel?

**Comment by gerbsen** [comment]
Hey, thanks for the reply. I did configure this quite some time ago, and it currently works. :) I really can't remember the details. If that's okay I will reopen if the problem occurs. Cheers, Daniel
