### ISSUE TITLE
Parallel clone generation

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#392]
I want to propose an option to have parallel processing for clone db generation. 

Rationale: 
* Cut down clone generation from 6+ hours to 2 hours (possibly much faster on SSD), reducing overall transaction duration.
* Distribute CPU load for compression/decompression across several cores
* Less hassle to turn zlib db into lz4 db (https://github.com/drolbr/Overpass-API/pull/334)
* Better support for more ad-hoc, on-demand style clone generation

Code: https://github.com/mmd-osm/Overpass-API/blob/3ae1a3ed614afb04545ab841cb9770e74c1923bb/src/overpass_api/osm-backend/clone_database.cc

-> needs parameter to control # of parallel processes. At this time, it's hardcoded to 4.

That's in fact very similar to [this logic](https://github.com/mmd-osm/Overpass-API/blob/feature/parallel_database_update/src/overpass_api/osm-backend/parallel_proc.h) -> reuse possible after merging.

Measurements on dev instance: (source=zlib clone files, no concurrent updates)

```
Target compression LZ4:
---------------------------------------------------------
2017-04-28 08:26:42 [1186] read_idx_finished 1420.
2017-04-28 08:26:42 [1420] read_idx_finished() end
2017-04-28 08:26:42 [1420] 
-- clone database --
2017-04-28 10:21:00 [1420] read_finished() start 1044680
2017-04-28 10:21:00 [1186] read_finished of process 1420.
2017-04-28 10:21:00 [1420] read_finished() end

Target compression zlib:
---------------------------------------------------------
2017-04-28 11:14:40 [1186] read_idx_finished 10503.
2017-04-28 11:14:40 [10503] read_idx_finished() end
2017-04-28 11:14:40 [10503] 
-- clone database --
2017-04-28 13:21:39 [10503] read_finished() start 1044686
2017-04-28 13:21:39 [1186] read_finished of process 10503.
2017-04-28 13:21:39 [10503] read_finished() end
```

**Comment by drolbr** [comment]
I'm more stunned by the fact that clone generation is consuming significant CPU time. It should consist only of seek-read-write. Do you have an idea where the process spends CPU time?

**Comment by mmd-osm** [comment]
Yes, that's all because of decompressing blocks and later compressing them again.

**Comment by mmd-osm** [comment]
(Needs at least c++11)

**Comment by mmd-osm** [comment]
Implemented in https://github.com/mmd-osm/Overpass-API, closing here.
