### ISSUE TITLE
Return just a list of changesets & their IDs

### ISSUE THREAD

**Issue by DaveF63** [drolbr/Overpass-API#393]
Hi
Unsure if this is a help or feature request.

Is there a way to return a list of changesets & their IDs within a bbox & a specified time frame?

I'm aware I can retrieve multiple changeset IDs from all entities & then filter unique IDs using something like XSL/Xpath, but I'm wondering if there's a direct method.

**Comment by mmd-osm** [comment]
Yes, that's supported via the OSM API (not Overpass API!): https://wiki.openstreetmap.org/wiki/API_v0.6#Query:_GET_.2Fapi.2F0.6.2Fchangesets

**Comment by DaveF63** [comment]
That answers my Q. Thanks
