### ISSUE TITLE
Use trigram index for fast regexes?

### ISSUE THREAD

**Issue by RicoElectrico** [drolbr/Overpass-API#404]
This was used in Google Code search. There could be a potential for very nice improvements when matching a regex.
[Regular Expression Matching with a Trigram Index or How Google Code Search Worked ](https://swtch.com/~rsc/regexp/regexp4.html)

I think even a rudimentary support (middle, left, right + case insensitive matching) would be great.

**Comment by mmd-osm** [comment]
Can you provide a query example where you have issues with regex today?

**Comment by SwiftFast** [comment]
The CPU of the overpass server is always idle. Disk speed is the bottleneck. 

From a State of the Map 2013 presentation:
![1](https://user-images.githubusercontent.com/28669244/26977324-20349c44-4d30-11e7-832b-e2858741dcae.png)

**Comment by mmd-osm** [comment]
@SwiftFast : that's really totally outdated. Server moved to SSD in the meantime, compression was added. CPU is almost always 100% busy.

https://overpass-api.de/munin/localdomain/localhost.localdomain/index.html#system

**Comment by SwiftFast** [comment]
Oh. Good to know. Thanks!

**Comment by RicoElectrico** [comment]
@mmd-osm The idea of a trigram index has been also implemented in C (`pg_trgm` module for Postgres).
The good thing about `pg_trgm` is that indexes build an order of magnitude faster than `btree`.

Interesting to know that regexes are not a bottleneck. So what is? I would kill for a proper documentation. I also searched some time ago to see how a query planner works in Overpass, but didn't find any info. I was interested in it because sometimes i have a feeling that rearranging `[...]` clauses yields different execution times.

**Comment by mmd-osm** [comment]
> So what is? 

Depends on your query. In most cases compression and overall CPU load play an important role. And there's a number of improvements waiting in this repo.

>  I was interested in it because sometimes i have a feeling that rearranging [...] clauses yields different execution times.

@SwiftFast mentioned the same in a recent forum post, and I was a bit skeptic if that's really the case. So, it's a good time to look at some examples maybe. `building=yes` and `addr:street=Arminiusstraße` have vastly different selectivity (447256 vs. 1) to illustrate the difference.


Test 1:

```C
[bbox:52.35169916280845,12.951507568359375,52.62597778718711,13.811187744140625];
way[building=yes]["addr:street"="Arminiusstraße"];
out geom ;
```

Test 2:

```C
[bbox:52.35169916280845,12.951507568359375,52.62597778718711,13.811187744140625];
way["addr:street"="Arminiusstraße"][building=yes];
out geom ;
```

Test 3:

```C
[bbox:52.35169916280845,12.951507568359375,52.62597778718711,13.811187744140625];
way["addr:street"="Arminiusstraße"][building];
out geom ;
```

Query 1 + 3 are quite fast (500ms/167ms), Query 2 is much slower (10s). I'm pretty sure that this behavior is not documented as such, and there's no recommendation to use a specific sequence.

**Comment by SwiftFast** [comment]
I did not mention the ordering itself yielded different results, I merely wondered if it does have an effect. 

> I would kill for a nice documentation

I agree performance-related documentation is lacking :(

**Comment by mmd-osm** [comment]
I added two recommendations to #314 to run query 2 in 5 seconds. Some relevant example queries  by @RicoElectrico involving regular expressions would also be good. Pg_trgm also needs lots of rework as it depends on Postgres which we don't have here.
