### ISSUE TITLE
Problem with areas

### ISSUE THREAD

**Issue by dotevo** [drolbr/Overpass-API#411]
Hello,

I'm not sure this bug. I want to get all "playground"=* inside the "leisure"="playground".
In that case I have an empty result:
http://overpass-turbo.eu/s/q9W

But when I want to get "playground"=* inside the any "leisure" it is working fine
http://overpass-turbo.eu/s/q9X

But from pivot I have data of park... not the playground.

Can anybody help my? How can I solve it?

BR,
Adam

**Comment by mmd-osm** [comment]
Problem here is that your playground doesn't have a name, hence area creation job on the server won't create an area for it. There's nothing you can do about it unfortunately, unless you set up your own instance and adjust area creation rules, or convince Roland to adjust area creation rules on overpass-api.de accordingly.

```C
way({{bbox}})["leisure"="playground"];
out geom;
map_to_area;
out;
```

**Comment by dotevo** [comment]
Is there another possibility to do something like this? To get all nodes with playground tag in playground.

**Comment by mmd-osm** [comment]
Not in one query. The only option today is to fetch all nodes with lat/lon values for your playground, and then run a second query via a `(poly: ...)` filter.

**Comment by dotevo** [comment]
Sounds like a good workaround. Thank you.

**Comment by mmd-osm** [comment]
(Duplicate of https://github.com/drolbr/Overpass-API/issues/77)

**Comment by mmd-osm** [comment]
ok, if your question is answered now, could you please close this issue? Thanks!

**Comment by dotevo** [comment]
Of course.
