### ISSUE TITLE
Add .md5 checksum to each clone file

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#420]
Like planet.openstreetmap.org and download.geofabrik.de alrady do, add a `.md5` checksum to each single clone file when creating those files, and check for correct checksums after download.

Bit errors in the db files can lead to extremely hard to analyze crashes later, so it's essential that the  clone download does not introduce such errors.

**Comment by drolbr** [comment]
The compression does already do the bit checks. Zlib has an integrated CRC32 check. And I suppose, LZ4 has a similar mechanism.

**Comment by mmd-osm** [comment]
Yes, that's right. Howver, if you download 170GB data from dev.overpass-api.de/clone, you want to make sure that all files are correct before using the database.

Relying on the CRC32 checks would mean that you would have to wait for random crashes when using the database later on, which is really inconvenient.

**Comment by mmd-osm** [comment]
Another point: currently, only bin files are compressed via zlib, while map files are uncompressed and don't have any checksum at all. Any corruption here would go unnoticed and could possibly trigger  segmentation faults. Same applies to all .idx files, regardless of bin or map.

IMHO, some sort of external checksum for clone downloads is really indispensable.
