### ISSUE TITLE
Area-based queries are slow, but can be replaced by pivot

### ISSUE THREAD

**Issue by dimashi** [drolbr/Overpass-API#424]
This query should return all states in US:
query 1:
```
[out:json];
area(3600148838)->.us;
rel(area.us)[admin_level=4];
out body; 
```
but it is so slow that times out. This modification makes it work pretty well:

query 2:
```
[out:json];
area(3600148838)->.us;
rel(pivot.us);
rel(r)[admin_level=4];
out body; 
```
I do not know details of how it is implemented, but if area-based queries are slow, I think it should be possible to do pivoting in the query engine itelf, so that original query rel(area.us) gets converted to rel(pivot.us); rel(r).
I assume (and hope) that query 1 and query 2 return the same results :)

**Comment by mmd-osm** [comment]
> I assume (and hope) that query 1 and query 2 return the same results :)

Unfortunately, that's not the case, they're very different semantically.

**Comment by dimashi** [comment]
"very different semantically" - does it mean they will return different set of relations?
yes, I already learned that I can use rel(148838); and in general I am trying to avoid using areas now: performance, and I saw several cases when areas are not calculated.

**Comment by mmd-osm** [comment]
> "very different semantically" - does it mean they will return different set of relations?

Exactly. Query 1 returns 171 relations, Query 2 only 51.

**Comment by dimashi** [comment]
I see. Logically I want to get objects "contained" in the parent object, but "containment" can be established with direct reference (parent relation references child relation) or geometric containment. Getting child references is fast, but I am at mercy of OSM editors establishing them. I am lucky that US rel references has all the US states, but US state rel does not reference its counties. This query to get Vermont counties returns nothing, unless rel is converted to area to do geometric search: 
```
[out:json];
rel(60759);
// map_to_area;
rel(r)[admin_level=6];
out qt;
```
Is it correct understanding of the OSM data? If so, please close this issue, it was just my lack of knowledge.
