### ISSUE TITLE
complete: endless loop with derived objects

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#427]
Creating derived objects in a complete loop seems to be a nice way to trigger 100% cpu utilization until the timeout kicks in.

```C
[timeout:1200];
complete(
   make dummy;
);
```

Not sure, if it really makes sense to support derived objects in a complete statement.

**Comment by drolbr** [comment]
Fixed in 64a59ac919ff805ab8d0932eb0900154b76627fb

complete has got a limit for the number of loops. This solves a broader group of problems than special rules for make.
