### ISSUE TITLE
munin: osm_db_request_count - use dispatcher status instead

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#428]
I'm testing a large number of requests per second and noticed that the count_queries.sh script starts getting expensive. Also, both .dot files in the database directory keep growing with one dot per query.

![grafik](https://user-images.githubusercontent.com/5842757/29884674-74e32f48-8db4-11e7-8c39-c0ec58ef8b33.png)

Proposal is to use the dispatcher status information instead for osm_db_request_count, and stop using count_queries.sh.

```
STATUS=`/srv/osm3s/bin/dispatcher --osm-base --status`   # adapt directory

STARTED=$(echo $STATUS | sed 's/.*Counter of started requests: \([0-9]*\).*/\1/')
echo "overpass_request_started.value $STARTED"

COMPLETED=$(echo $STATUS | sed 's/.*Counter of finished requests: \([0-9]*\).*/\1/') 
echo "overpass_request_completed.value $COMPLETED"
```

Result in munin looks ok:

![grafik](https://user-images.githubusercontent.com/5842757/29884789-d5f3ee8a-8db4-11e7-85c3-10b88b6a0ba2.png)

**Comment by drolbr** [comment]
Fixed in d7bb5f892889e17400f5de2434b7ba3bd2b20db0
