### ISSUE TITLE
Sometimes getting a HTML response

### ISSUE THREAD

**Issue by westnordost** [drolbr/Overpass-API#431]
It seems that very rarely when doing a valid overpass query, the overpass server (using the public one) will return some HTML document instead of a proper JSON/XML/CSV response. The HTTP response code is OK 200, though.

I cannot give any more details about the content of the HTML response because I only found out that this happens sometimes because I get crash reports from users of [StreetComplete](https://github.com/westnordost/StreetComplete), whose Overpass response parser always expects the response to be valid XML and thus fails parsing something like:
```
<head>
  <meta charset="UTF-8">
etc...
```
 (meta is not closed)

So, if it is to be expected that on certain circumstances, the server will answer with HTTP 200 but return a HTML, it should be documented that it does. Perhaps while the service is down because of maintenance work? (Though, there'd be a HTTP error code for that.)
And, well, if it is not, then it seems to be a bug.

**Comment by mmd-osm** [comment]
I think for further analysis it would be extremely useful if you could provide at least a timestamp when the query was executed. 

The response snippet you mentioned doesn't appear as such in the Overpass source code, i.e. this may be something Apache as a webserver returns, though I wonder why you get a HTTP 200 code. Do you see a way to get the full response for further analysis, rather than a very short extract only?

**Comment by westnordost** [comment]
Well, I could implement to catch the exception at this point and include the whole response in the reported stack trace, but that wouldn't go live until a month or so. The short snippet is something I derived from this item on the stack trace:
`org.xmlpull.v1.XmlPullParserException: expected: /meta read: head (position:END_TAG </head>@22:8 in java.io.InputStreamReader@e3f7ff8) ` (XML parser expects the <meta> tag to be closed)

But, if there isn't anything like this in the Overpass code, I also suspect that there was something with the server temporarily. If this happened more often (which it doesn't seem to), I would get a lot more bug reports about this.
So, I guess this can be filed as a hickup of the server and not as a problem of the overpass program, feel free to reopen if you think otherwise. For my app, I will just implement to treat an invalid response the same as a connection problem or a 5xx error.
