### ISSUE TITLE
Error decompresing osm-3s_v0.7.54.tar.gz

### ISSUE THREAD

**Issue by jfisbein** [drolbr/Overpass-API#433]
The file osm-3s_v0.7.54.tar.gz at http://dev.overpass-api.de/releases/osm-3s_v0.7.54.tar.gz is producing an error when I try to decompress it:
```
gzip: stdin: invalid compressed data--crc error
gzip: stdin: invalid compressed data--length error
```

**Comment by mmd-osm** [comment]
Should be resolved in the meantime.

**Comment by jfisbein** [comment]
Solved. Thanks!
