### ISSUE TITLE
Empty Indonesia border by overpass api

### ISSUE THREAD

**Issue by Solodkiy** [drolbr/Overpass-API#436]
I tried get Indonesia border by query

[out:json][timeout:60];(relation["ISO3166-1"="ID"]);out body;>;out meta qt;
on http://www.overpass-api.de/query_form.html but got empty elements list. Other countries works fine. What I am doing wrong?

**Comment by mmd-osm** [comment]
See http://www.openstreetmap.org/relation/304751 - your query looks for ISO3166-1 = ID which does not exist.

Please note that this issue tracker is mainly intended for Software bugs or enhancement requests. help.openstreetmap.org might be a much better place for such questions.

Kindly request to close this issue, if this answers your question. Thanks.
