### ISSUE TITLE
Odd behavior with complex (large area + many tag filter) queries and timeouts

### ISSUE THREAD

**Issue by bdon** [drolbr/Overpass-API#437]
I've been seeing some odd behavior when issuing very large queries, example query attached:

[complex_query.txt](https://github.com/drolbr/Overpass-API/files/1319051/complex_query.txt)

This queries for nodes, ways recursing down, and relations recursing doubly down, with ~50 tag filters for each entity type, for a bounding box that encompasses Kenya.

If I issue the query with only ONE of the entity types (e.g. only nodes, only ways or only relations) within the resource limits of our own Overpass instance - a response begins streaming within 1-5 minutes of issuing the query. Great. I can also see the query in the `api/status` endpoint.

Issuing the complete query shows up in `api/status` for roughly 10 minutes, and then it disappears from the `api/status` list. Our HTTP client library then blocks forever on the socket connection, never receiving a response. It doesn't seem like this query is exceeding some resource limit as usually when that happens we get a response like `: runtime error: open64: 0 Success /osm3s_v0.7.54_osm_base Dispatcher_Client::request_read_and_idx::timeout. The server is probably too busy to handle your request. `. So this seems like a different failure mode. 

The same query with all 3 entity types and all tag filters works fine when the area is smaller. 

I have explored the possibility that this is related to something between the overpass dispatcher and our HTTP client, such as nginx and fastcgi. But both those have been configured with appropriately long timeouts as well.

**Comment by mmd-osm** [comment]
Hi,

thanks for reporting this issue. 

I ran a very first test on dev instance (post 0.7.54) via command line tool osm3s_query. Overall, the query has a very high memory consumption, and possibly gets aborted by the OS (limit is set by a call to setrlimit). At least osm3s_query doesn't abort, though requires a bit more than 4GB of memory.

Once the query disappears from /api/status, can you check, if `ps -efax` still shows a running `interpreter` process, or did that process also die? What about error messages in the nginx log?

Can you try, if osm3s_query works for you? Probably you need to further increase maxsize,
assuming the dispatcher limits have been increased to accomodate that memory requirement. 


```
/usr/bin/time -v /opt/osm-3s/v0.7.54/bin/osm3s_query < q1 > q1.res
encoding remark: Please enter your query and terminate it with CTRL+D.
After 0h0m42s: in "query", part 1, on line 9. Stack: 0 of 0 0 of 13998
After 0h1m0s: in "query", part 4, on line 15. Stack: 0 of 0 0 of 31830
After 0h1m17s: in "query", part 1, on line 22. Stack: 0 of 0 0 of 36867
After 0h1m32s: in "query", part 1, on line 30. Stack: 0 of 0 0 of 42285
After 0h1m47s: in "query", part 4, on line 39. Stack: 0 of 0 0 of 58448
After 0h2m2s: in "query", part 4, on line 52. Stack: 0 of 0 0 of 63574
After 0h2m21s: in "query", part 4, on line 60. Stack: 0 of 65817 0 of 0
After 0h2m37s: in "query", part 8, on line 63. Stack: 0 of 65817 0 of 1261
After 0h2m52s: in "query", part 4, on line 67. Stack: 0 of 65817 0 of 4534
After 0h3m8s: in "query", part 1, on line 72. Stack: 0 of 65817 0 of 143852
After 0h3m33s: in "query", part 1, on line 76. Stack: 0 of 65817 0 of 144934
After 0h3m48s: in "query", part 4, on line 80. Stack: 0 of 65817 0 of 571229
After 0h4m17s: in "query", part 1, on line 81. Stack: 0 of 65817 0 of 571240
After 0h4m53s: in "query", part 1, on line 85. Stack: 0 of 65817 0 of 2473245
After 0h5m8s: in "query", part 4, on line 98. Stack: 0 of 65817 0 of 2475214
After 0h5m23s: in "query", part 4, on line 111. Stack: 0 of 65817 0 of 2475445
After 0h5m38s: in "recurse", part 0, on line 113. Stack: 0 of 2541367
After 0h5m53s: in "query", part 8, on line 128. Stack: 0 of 23767922 0 of 644
After 0h6m8s: in "query", part 8, on line 147. Stack: 0 of 23767922 0 of 1924
After 0h6m25s: in "recurse", part 0, on line 169. Stack: 0 of 23769852
After 0h9m46s: in "print", part 0, on line 170.
	Command being timed: "/opt/osm-3s/v0.7.54/bin/osm3s_query"
	User time (seconds): 420.78
	System time (seconds): 16.28
	Percent of CPU this job got: 74%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 9:47.78
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 4260376   <------ !!!
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 25
	Minor (reclaiming a frame) page faults: 3706065
	Voluntary context switches: 7281
	Involuntary context switches: 32123
	Swaps: 0
	File system inputs: 2174920
	File system outputs: 8972968
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0


```

Resulting file size: 4,4 GB (!) - this is also quite large. 

-rw-rw-r-- 1 mmd mmd 4475101915 Sep 20 21:02 q1.res



BTW: I noticed one issue in one of the regular expressions: `[leisure~'stadium,\ swimming\ pool,\ pitch,\ sport_centre']`, should probably read `[leisure~"stadium|swimming|pool|pitch|sport_centre"]`

**Comment by bdon** [comment]
@mmd-osm thanks for these tips, the query does succeed after 6-7 minutes using `osm3s_query`. And it doesn't seem to consume more than 1-2GB of memory. Investigating further

**Comment by bdon** [comment]
@mmd-osm something else interesting i've noticed is that the query `[maxsize:4294967296][timeout:3200];(node(-5.30934543391,33.5092889281,5.31018690969,42.3862420531);<;>>;>;);out meta;` succeeds via the API very quickly, in about one minute. This query's result set should be a superset of the complex one above, but doesn't reach any resource limits. 

There are other queries that fail with the error `<meta osm_base="2017-09-24T10:17:02Z"/>\n', '\n', '<remark> runtime error: Query run out of memory using about 9216 MB of RAM. </remark>` but again the complex query pasted above doesn't show any error message

**Comment by bdon** [comment]
@mmd-osm the `interpreter` process with the corresponding PID no longer appears in `ps -efax` once the query disappears from the `api/status` list. 

nginx error logs only show the line

    2017/09/25 22:58:12 [warn] 67#0: *17956 an upstream response is buffered to a temporary file /var/lib/nginx/fastcgi/5/62/0000000625 while reading upstream, client: <clientip>, server: localhost, request: "POST /api/interpreter HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "<serverip>:6080"

which does not seem erroneous

**Comment by bdon** [comment]
I have not been able to reproduce this issue outside of our production environment, so it is likely related to resource exhaustion on our specific machine and unlikely to do with Overpass. closing this issue for now, thanks.

**Comment by bdon** [comment]
FYI: this issue was not related to overpass at all and resolved by switching to a `libcurl` based HTTP client.
