### ISSUE TITLE
Issue with syntax for set difference

### ISSUE THREAD

**Issue by ltog** [drolbr/Overpass-API#439]
Not sure, if this is the right place to ask. Sorry if not!

The page https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Difference mentions the following syntax for the set difference:

    (statement_1; - statement_2;)[->.result_set];

Overpass Turbo then however complains:

    parse error: ';' expected - '[' found.

Shouldn't the squared brackets be removed such as in the third code block of https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Difference ?

      (node[name="Foo"]; - node(50.0,7.0,51.0,8.0);)->.a;

That would then result in what I believe should be written in the Wiki:

    (statement_1; - statement_2;)->.result_set;

**Comment by mmd-osm** [comment]
Don't take the squared brackets literally, they're meant to indicate an optional part of the syntax and are not part of the actual syntax used by Overpass API. Don't just remove them on the wiki, otherwise the notion of being optional gets lots.

**Comment by ltog** [comment]
@mmd-osm : Thank you for the quick reply. I made two changes in the wiki as you've proposed.
