### ISSUE TITLE
Query working using "osm3s_query" but not using "interpreter"

### ISSUE THREAD

**Issue by lucari93** [drolbr/Overpass-API#441]
Hi,
I have installed an Overpass-API instance configured with hourly updates and the Apache web server.
I'm currently having a problem: if I run a query using `osm3s_query `(even without specifying $DB_DIR), it works without any problems but if I run the same query using the `interpreter ` through the Apache server, it always fails.

Looking at `top` I can see that the `interpreter` process uses the usual amount of CPU and MEMORY for a period that lasts more or less the time of executing the query with "osm3s_query" but then it continue to keep the MEMORY occupied without using CPU at all. At a certain point terminates without giving any response to the client (the connection remains opened). 

After that, I find this error `[Thu Oct 12 15:31:33.665322 2017] [cgid:error] [pid 12369:tid 140489428813568] (110)Connection timed out: [client ***.***.***.***:54026] AH02550: Failed to flush CGI output to client` in the Apache error.log file.

A query that causes this problem is for example:
```
(
  node["natural"="peak"]["name"];
  node["natural"="volcano"]["name"];
);
out geom meta;
```
This problem is not present when I run queries that return a smaller amount of data

Thanks a lot  for the support

**Comment by mmd-osm** [comment]
Similar: #437

**Comment by lucari93** [comment]
I've already analyzed the issue that you've suggested to me. 

In my case the output of the query that I've put in the previous message is only 130MB and the memory consumed by `osm3s_query` or `interpreter` is the same and is only 450MB.
Is it possible that such a query gets aborted by the OS? And why only when done using `interpreter`?

I can not figure out the difference between running the query with `osm3s_query` or `interpreter`.

Thanks a lot.

**Comment by mmd-osm** [comment]
`interpreter` is created as a CGI process by Apache, and depending on timeout settings, it may get killed. One such reason could be that it takes too much time for `interpreter` to start sending any bytes.

How much time does it take you to run the query via `osm3s_query`?

**Comment by lucari93** [comment]
The query takes around 30/40 minutes to be executed with  `osm3s_query`.

I've set in Apache VirtualHost `Timeout 7200`.

Does the `interpreter `start sending data while they are collected or only at the end of the query?

Thanks.

**Comment by mmd-osm** [comment]
> The query takes around 30/40 minutes to be executed with osm3s_query.

Ok, takes less than 2 minutes here on more recent branch: http://overpass-turbo.eu/s/sk1

> Does the interpreterstart sending data while they are collected or only at the end of the query?

The `out` statement triggers the output, before that is just data collection which takes some time.

**Comment by lucari93** [comment]
I've currently installed version 0.7.54.
Where can i find the code of the branch that you linked in the previous message?
The database is the same or must be reimported?

Thanks

**Comment by mmd-osm** [comment]
Ah, sorry forgot to mention that it's still in development and not yet released... will take some time till it's officially available.

**Comment by mmd-osm** [comment]
Is this issue now resolved on your end? If so, can you please close it. Thanks!

**Comment by lucari93** [comment]
Yes, I think that is a problem of web server or network. Thanks.
