### ISSUE TITLE
A time like "24:60:60" is accepted by the date() and is_date() evaluators

### ISSUE THREAD

**Issue by zstadler** [drolbr/Overpass-API#442]
It seems that the implementation allows a time of "24:60:60" which is equivalent to one hour, one minute and one second on the next day.

Ref:
- [Validity check for date()](https://github.com/drolbr/Overpass-API/blob/350cf560956c669171b949b162f239b55936e1a8/src/overpass_api/statements/unary_operators.cc#L283-L284)
- [Validity check for is_date()](https://github.com/drolbr/Overpass-API/blob/350cf560956c669171b949b162f239b55936e1a8/src/overpass_api/statements/unary_operators.cc#L356-L357)

I would expect "23:59:60" to be the maximal time of day to allow for [leap seconds](https://en.wikipedia.org/wiki/Leap_second) too.

**Comment by gappleto97** [comment]
The 24 part is accepted in some locales. Admittedly not many, but that part is probably a valid timestamp.

**Comment by drolbr** [comment]
Fixed in adf6aa73149ab2ddd99ca8b286c15f7602687a53
