### ISSUE TITLE
Constant 100% CPU load for osm3s_query process

### ISSUE THREAD

**Issue by gerbsen** [drolbr/Overpass-API#443]
Hello,
I'm experiencing some odd behaviour (I think) with `osm3s_query`. There is a process: `./osm3s_query --progress --rules` which has 100% (1 core) CPU load all the time. I'm running the docker version provided by [@Frankkkkk](https://github.com/Frankkkkk/docker-overpass-api). Replication url is set to `http://planet.osm.org/replication/hour`. I reinstall this last week so the source should be pretty recent.
Any ideas?
Cheers, daniel

**Comment by mmd-osm** [comment]
Please try again with the most recent released version: https://dev.overpass-api.de/releases/osm-3s_v0.7.54.10.tar.gz

**Comment by gerbsen** [comment]
Thanks for the quick reply! Currently I'm running the master branch?! Do you think the error (if it is one) was introduced later this year? What I'm trying to say, does it make sense to go back in time with the code?

**Comment by mmd-osm** [comment]
The most recent coding is in the minor_issues branch, the Docker image you're running doesn't reflect that. In any case, only use a released version, not just some random Github commit.

**Comment by gerbsen** [comment]
Sorry, I just rechecked what the current docker image does: (I thought I remembered it checked out master, must have mixed this up)

```
...
RUN git clone https://github.com/drolbr/Overpass-API.git
WORKDIR /Overpass-API
#Checkout latest version
RUN git checkout $(git describe --abbrev=0 --tags)
...
```

So I'm already running the latest version. What does this process actually do?

FYI I do have lot's of these log messages: 

```
After 0h30m35s: in "make-area", part 0, on line 29. Stack: 379285 of 861720
After 0h30m50s: in "make-area", part 0, on line 29. Stack: 383704 of 861720
After 0h31m5s: in "recurse", part 0, on line 27. Stack: 388180 of 861720 0 of 4
```

**Comment by gerbsen** [comment]
What do you mean with `perf top`?

**Comment by mmd-osm** [comment]
> So I'm already running the latest version.

I'm afraid, that's not correct. You're running commit 33884f4cab6181b39323c83c57feb3470ebd45f2, which is dated Mar 6, 2017. The "tags" is not being used, you the approach taken in the Docker file doesn't work. Sorry. Forget the comment "Checkout latest version", it's misleading and incorrect.

> What do you mean with perf top?

See https://linux.die.net/man/1/perf-top

**Comment by gerbsen** [comment]
> perf-top
```
Samples: 172K of event 'cycles', Event count (approx.): 56966675545
Overhead  Shared Object               Symbol
  32.89%  liblz4.so.1.7.1             [.] LZ4_decompress_safe
   9.40%  osm3s_query                 [.] 0x0000000000039b10
   2.58%  [kernel]                    [k] copy_user_enhanced_fast_string
   1.93%  libstdc++.so.6.0.21         [.] std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare
   1.89%  libc-2.23.so                [.] malloc
   1.52%  osm3s_query                 [.] 0x000000000007db41
   1.44%  osm3s_query                 [.] 0x000000000007daa3
   1.26%  liblz4.so.1.7.1             [.] LZ4_compress_fast_extState
   1.14%  libc-2.23.so                [.] free
   0.87%  libstdc++.so.6.0.21         [.] std::_Rb_tree_increment
   0.85%  libstdc++.so.6.0.21         [.] std::_Rb_tree_insert_and_rebalance
   0.79%  libstdc++.so.6.0.21         [.] std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign
```
>Are you running a planet or extract?

I'm running a planet file.

> You're running commit 33884f4

I'm gonna change that to the releaase you linked before. By the way, where would I download this? The release page only shows: osm3s-v0.7.54 not osm-3s_v0.7.54.10

**Comment by mmd-osm** [comment]
Ok, perf top looks good so far, running this process for the whole planet will take at least 8-11 hours, depending on your hardware.

> By the way, where would I download this?

https://dev.overpass-api.de/releases/ would be the right place. And yes, the release page is outdated :(

**Comment by gerbsen** [comment]
What process should take 8-11 hours? The import is done and I can query the service. This has to be some update that is run all the time.

**Comment by mmd-osm** [comment]
That's the area creation job running as `./osm3s_query --progress --rules`

See http://wiki.openstreetmap.org/wiki/Overpass_API/Areas

**Comment by mmd-osm** [comment]
Ok, as this is neither a bug report nor an enhancement request, I'd suggest to close this issue.

**Comment by gerbsen** [comment]
Yes. Thank you for your help! Really appreciate it!
