### ISSUE TITLE
Problem with disabling meta information

### ISSUE THREAD

**Issue by gerbsen** [drolbr/Overpass-API#446]
Hey,
We are running the docker image provided by @Frankkkkk. I tried to disable the meta data generation since we just don't need it and it costs lots of disk space by:

`$BINDIR/init_osm3s.sh $DBDIR/planet.osm.bz2 $DBDIR $EXECDIR --meta=no`,
`$BINDIR/fetch_osc_and_apply.sh $REPLICATE_SERVER --meta=no &` and 
`$BINDIR/dispatcher --osm-base --db-dir=$DBDIR &`

But this seems to be either ignored or misinterpreted:

```
Will run dispatcher
File /overpass_DB/nodes_meta.bin present. Please use parameter --meta
File /overpass_DB/ways_meta.bin present. Please use parameter --meta
File /overpass_DB/relations_meta.bin present. Please use parameter --meta
File /overpass_DB/user_data.bin present. Please use parameter --meta
File /overpass_DB/user_indices.bin present. Please use parameter --meta
Will run diff fetcher
/Overpass-API/bin/fetch_osc_and_apply.sh: line 125: $DB_DIR/fetch_osc_and_apply.log: ambiguous redirect
mkdir: cannot create directory '/osm3s_v0.7.54_osm_base': Permission denied
/Overpass-API/bin /overpass_DB
cat: File_Error: No such file or directory
cat: No: No such file or directory
cat: such: No such file or directory
cat: file: No such file or directory
cat: or: No such file or directory
cat: directory: No such file or directory
cat: 2: No such file or directory
cat: /osm3s_v0.7.54_osm_base: No such file or directory
cat: 'Dispatcher_Client::1/replicate_id': No such file or directory
/Overpass-API/bin/fetch_osc_and_apply.sh: line 137: $DB_DIR/fetch_osc_and_apply.log: ambiguous redirect
File error caught: 2 No such file or directory /osm3s_v0.7.54_osm_base Dispatcher_Client::1
```

Is there any way to achieve what I want?

**Comment by mmd-osm** [comment]
There's a check in place which prevents the dispatcher from starting without --meta, if there are already meta-related files in your database directory. If you really don't want meta, you should remove those files from your database directory.

@breki wrote a guide to run everything without meta. Maybe you can use this as a reference to adjust your docker image: http://wiki.openstreetmap.org/wiki/User:Breki/Overpass_API_Installation

```
File /overpass_DB/nodes_meta.bin present. Please use parameter --meta
File /overpass_DB/ways_meta.bin present. Please use parameter --meta
File /overpass_DB/relations_meta.bin present. Please use parameter --meta
File /overpass_DB/user_data.bin present. Please use parameter --meta
File /overpass_DB/user_indices.bin present. Please use parameter --meta
```

**Comment by gerbsen** [comment]
Thank you for your quick answer as always! The trick was to write:

`$BINDIR/init_osm3s.sh $DBDIR/planet.osm.bz2 $DBDIR $EXECDIR` instead of `$BINDIR/init_osm3s.sh $DBDIR/planet.osm.bz2 $DBDIR $EXECDIR --meta=no` to not generate meta infos.
