### ISSUE TITLE
Add a 'length' operator to filter on length of a segment/track

### ISSUE THREAD

**Issue by pietervdvn** [drolbr/Overpass-API#448]
Would it be possible to add a 'length' operator, to make filtering on the length of a segment/track possible?

E.g.

        way[length>1]

would filter away all tracks that are less then 1m.

The tag `length` and `total_length` are not used in OSM according to taginfo.

If someone points out where to add this feature, I might add it in myself.

**Comment by mmd-osm** [comment]
This feature is already implemented and will be available with the next release.

**Comment by pietervdvn** [comment]
Oohhh! <3

Thanks a lot!

**Comment by mmd-osm** [comment]
Duplicate of https://github.com/drolbr/Overpass-API/issues/237
