### ISSUE TITLE
querying for areas inside an area?

### ISSUE THREAD

**Issue by szymond** [drolbr/Overpass-API#45]
I'd like to extract information about areas inside areas (e.g. to get information about regions in country). I am trying to run something like this:

```xml
<query type="area">
  <area-query ref="3600049715"/>
  <has-kv k="admin_level" v="4"/>
</query>
<print/> 
```

And it returns all areas (not limited to specified region). More or less the same query (but about nodes):
```xml
<query type="node">
  <area-query ref="3600049715"/>
  <has-kv k="shop" v="kiosk"/>
</query>
```
works fine. Is there a problem with API or I am doing something wrong?

**Comment by mmd-osm** [comment]
@szymond : area in area support is available via the [`map_to_area` statement](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Map_way.2Frelation_to_area_.28map_to_area.29)  (still a bit experimental at this point in time). The wiki page also provides a number of use cases + example to get you started.

If you're happy with this approach, I would suggest to close this ticket.

**Comment by szymond** [comment]
@mmd-osm : Thanks. I've briefly looked at provided examples, but I can't seem to find there information how to prepare a query which would return areas which are inside of selected area. Could you give an example of such query?

**Comment by mmd-osm** [comment]
Please compare 

```C
area[name="Köln"];                     // selected area
rel(area)[name="Innenstadt"];    // find relations in selected area
map_to_area;                             // convert relations to areas
out meta;                                    // print areas
```

vs. 

```C
area[name="Innenstadt"];
out meta;
```

The first query will return the "Innenstadt" of Cologne, the second one returns all 36 "Innenstadt" areas worldwide.

**Comment by jotpe** [comment]
Wow, its already done, didn't know it. Great job!

**Comment by dimashi** [comment]
It works, but it's very slow. This query timed out after 3 min:

area["ISO3166-1"="US"][admin_level=2];
rel(area)["name"="Georgia"]["border_type"="state"];
map_to_area;

This is not exactly the same (does not return area), but uses area intersection. It is also slow, but at least does not time out:

(area["ISO3166-1"="US"][admin_level=2]; )->.country;
(area["name"="Georgia"]["border_type"="state"])->.state;
node["name"="Atlanta"](area.country)(area.state)

**Comment by mmd-osm** [comment]
@dimashi : you should make your query as restrictive as possible to start with. If you're unsure how administrative boundary tagging is done in the US, please get in touch with the US community for further assistance.

```
area["ISO3166-2"="US-GA"][boundary=administrative];
node[name="Atlanta"](area);
out;
```

**Comment by dimashi** [comment]
@mmd-osm: I am not looking for a one-off query that will work for Atlanta, Georgia, but trying to find generic solution that will work in any country. Contacting > 200 OSM communities does not sound feasible. I actually found performant solution: geocode City, Region, Country with Google, get lat/lon, then use overpass is_in(lat, lon) which works fast and returns all the areas I need. But using google defeats OSM purpose :)

**Comment by mmd-osm** [comment]
There's also nominatim, if you need geocoding on OSM data.

**Comment by dimashi** [comment]
Agree, I could use that. But we deviated from the topic of the thread. My point was that performance of new api for "areas inside area" is very poor as compared to an older API that intersects areas.

**Comment by mmd-osm** [comment]
Not sure what you mean by _an older API that intersects areas_ Can you maybe elaborate a bit?

**Comment by dimashi** [comment]
Yes, I see, my example was mangled.

'''
(area["ISO3166-1"="US"][admin_level=2]; )->.country;
(area["name"="Georgia"]["border_type"="state"])->.state;
node["name"="Atlanta"][place](area.country)(area.state)
'''
I am finding Atlanta in intersection of country and state, which is not exactly the same as area inside area but similar, state inside country. This query is not fast, but it does not time out.

**Comment by mmd-osm** [comment]
Is this how your query looks like?

```
area["ISO3166-1"="US"][admin_level=2] ->.country;
area["name"="Georgia"]["border_type"="state"]->.state;
node["name"="Atlanta"](area.state)(area.country);
out;
```

**Comment by dimashi** [comment]
yes, thank you!

**Comment by mmd-osm** [comment]
>  This query is not fast, but it does not time out.

Yes, interesting approach. I don't see obvious downsides at the moment.

On the main instance, the query takes around 15s, on the development instance 3-4s: http://overpass-turbo.eu/s/ogN

**Comment by dimashi** [comment]
The downside for me is that 15 sec is not really acceptable, and it probably overloads server. I thought about caching city areas, i.e. cache map {(City, Region, Country), (OSM city area ID)}, and then use city area by ID to find things inside that area. But my workaround query does not return area, it returns node (or way, or rel). New syntax would allow me to cache area, but I guess US polygon is too big.
