### ISSUE TITLE
Operator for selecting first or last node along a way

### ISSUE THREAD

**Issue by 1ec5** [drolbr/Overpass-API#451]
Often when working with `oneway` ways or [directional tags](https://wiki.openstreetmap.org/wiki/Forward_%26_backward,_left_%26_right), such as `*:forward` and `*:backward`, I need to find the first or last node of a way based on its position in the node list of the way. It isn’t always possible to accomplish the same query by checking the tags on connecting ways. For example:

* If I want to find every `highway=motorway_link` way that [represents a motorway entrance ramp](http://www.openstreetmap.org/way/500825480), it isn’t enough to check whether the way shares a node with a non-motorway, because so could a `highway=motorway_link` way [representing an _exit_ ramp](http://www.openstreetmap.org/way/528183147).
* If I want to find every way in a dual carriageway that leads to an intersection with a `highway=residential` way, but not those that lead _from_ such an intersection, I need to consider the ways connected to the _last_ node in the way, but not the first node or any other node. (My use case is to compute the lengths of turn lanes, so I can assume that the way ends at the intersection.)

In these cases, I’d like to be able to explicitly retrieve the first or last node of the way. Perhaps `first()` and `last()` operators:

```js
way["highway"="motorway_link"];
node(w).last();
```

**Comment by dmanzer95** [comment]
I have various use cases where I would also benefit from this

**Comment by mmd-osm** [comment]
(This was implemented in version 0.7.56, documentation is still pending)

**Comment by mmd-osm** [comment]
Documentation is available here now: http://dev.overpass-api.de/blog/total_0_7_56.html#memberpos

**Comment by mmd-osm** [comment]
@1ec5 : since this feature is available since a while, it might be a good time to close this issue. Thanks!

**Comment by 1ec5** [comment]
Thanks for the reminder!
