### ISSUE TITLE
Import fails with index inconsistent error

### ISSUE THREAD

**Issue by gerbsen** [drolbr/Overpass-API#452]
Hey,
I've started the import like this:

`$BINDIR/init_osm3s.sh $DBDIR/planet.osm.bz2 $DBDIR $EXECDIR`

I'm using an adapted version of the Dockerfile provided by Frankkkk and the most recent version v0.7.54.10 but I'm now getting the error

`Reorganizing the database ...File error caught: 384 Unknown error 384 /overpass_DB/nodes.0c.bin File_Blocks::read_block: Index inconsistent`

Any ideas?

**Comment by mmd-osm** [comment]
Please make sure to us the latest version in your docker image: https://dev.overpass-api.de/releases/osm-3s_v0.7.54.12.tar.gz

There were some recent fixes for --meta=no and that Dockerfile is know to be outdated.

**Comment by gerbsen** [comment]
I've done as you suggested and tried with 0.7.54.12 but I get this error now :(

```
Reading XML file ... elapsed node 311610878. Flushing to database ...... done.
Reorganizing the database ...terminate called after throwing an instance of 'std::runtime_error'
  what():  LZ4_decompress_safe failed
/Overpass-API/bin/init_osm3s.sh: line 44:    99 Broken pipe             bunzip2 < $PLANET_FILE
       100 Aborted                 (core dumped) | $EXEC_DIR/bin/update_database --db-dir=$DB_DIR/ $META $COMPRESSION
```

**Comment by mmd-osm** [comment]
Did you delete all database related files in your database directory before starting a new full import? Otherwise already existing files might screw up the import, in case they're already corrupt.

**Comment by gerbsen** [comment]
Yes, I've started with a clean folder and a planet file downloaded yesterday.

**Comment by mmd-osm** [comment]
Do you see the same error when running on a small extract, or without the --meta=no flag?

**Comment by gerbsen** [comment]
I've switched to another more [up-to-date and absolutely awesome docker image](https://github.com/wiktorn/Overpass-API/blob/master/README_Docker.md) and adjusted that to my needs. No everything is working as expected. Thank you for your help!
