### ISSUE TITLE
Union 2 or more queries to one

### ISSUE THREAD

**Issue by davittorosyan** [drolbr/Overpass-API#459]
Please, one more question about union
I Have this query

```
area["name"="London"];
node(area)["amenity"="bar"]->.all;
( .all; - ._;);
(._;);
out;
```

**but for less queries to overpass server i want to join more categories to one query, 
I think this should be like this** 
`node(area)["amenity"="bar" || "amenity"="restaurant"]->.all;
`

but i have error there.

can you please show me true syntax?

**Comment by mmd-osm** [comment]
I'd like to remind you that this issue tracking is primarly used for bug reports or enhancement requests.

help.openstreetmap.org would be a good place for your questions.

Thanks!

**Comment by davittorosyan** [comment]
@mmd-osm  Thank you
