### ISSUE TITLE
allow querying by object area/way length

### ISSUE THREAD

**Issue by matkoniecz** [drolbr/Overpass-API#464]
Usecase example: finding mistagging like https://www.openstreetmap.org/way/222795099#map=19/52.51666/13.41946&layers=N or excluding them in program processing OSM data (I wanted to add this functionality in StreetComplete).

**Comment by mmd-osm** [comment]
I believe we already have an issue for this, so marking as duplicate.

**Comment by matkoniecz** [comment]
I thought about two cases: way is closed, filtering by area is available and second: way is not closed and length is available

**Comment by mmd-osm** [comment]
A closed way doesn’t necessarily imply an area in an Overpass sense, e.g. if there’s no name tag...

**Comment by mmd-osm** [comment]
Future syntax for non-closed ways with a certain min length will look as follows:

```
way(if:!is_closed() && length() > 10);
out geom;
```

Check out the following example: http://overpass-turbo.eu/s/wGT

As there's really nothing left to do here, kindly request to close this issue. Thanks!

**Comment by matkoniecz** [comment]
Thanks! Is it feasible to allow filtering by size (area) of closed way - like buildings, lakes etc?

**Comment by mmd-osm** [comment]
I don't recall if Roland already implemented such a function for area sizes, will cross check.
