### ISSUE TITLE
OpenStreetMap import will break if links aren't updated before May 7

### ISSUE THREAD

**Issue by grischard** [drolbr/Overpass-API#466]
http://planet.openstreetmap.org is available over https, and will [start redirecting to https on 2018-05-07](https://github.com/openstreetmap/operations/issues/200).

Your project recommends curl in full_installation.html, which [will not follow redirects by default](https://davidwalsh.name/curl-follow-redirects).

Would it please be possible to update all files from `http://planet.openstreetmap.org` to `httpS://planet.openstreetmap.org` before then?

Ideally, would it be possible to make all requests to openstreetmap.org over https?

**Comment by mmd-osm** [comment]
Well, curl is only mentioned as a possible alternative in the documentation, you would have to manually adjust all scripts first to hit this issue. Nevertheless, it would probably make sense to adjust all links to https.

**Comment by Marc-marc-marc** [comment]
what did you think about my PR #475 to fix this ?

**Comment by Marc-marc-marc** [comment]
in addition to uncommented PR #475, this issue have been fixed with commit 3528a418d8561fff9e12fb94fc800553d28c36ec
the issue can therefore be closed
