### ISSUE TITLE
/app/bin/init_osm3s.sh: line 44:    11 Broken pipe

### ISSUE THREAD

**Issue by Jern97** [drolbr/Overpass-API#468]
I'm constantly having this error when I'm trying to import Belgium:

`Reading XML file ... elapsed node 2689644801. Flushing to database ...... done.
Reading XML file ... finished reading nodes. Flushing to database ..terminate called after throwing an instance of 'File_Error'
/app/bin/init_osm3s.sh: line 44:    11 Broken pipe             bunzip2 < $PLANET_FILE
        12 Aborted                 | $EXEC_DIR/bin/update_database --db-dir=$DB_DIR/ $META $COMPRESSION`

I've tested with Monaco (much smaller size) and that worked fine. I've also tested on multiple machines but got the same error. This is what i typed into the docker container:

` docker-machine create default --virtualbox-cpu-count "4" --virtualbox-memory "12000" --virtualbox-disk-size "60000"`

Ram and disk size should be plenty, since I'm only importing a small country (I suppose).
Next step is giving the machine the rights:

`docker-machine env default`
`eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env default)`

Now i run the image provided by wiktorn:

`docker run \
  -e OVERPASS_META=no \
  -e OVERPASS_MODE=init \
  -e OVERPASS_PLANET_URL=http://download.geofabrik.de/europe/belgium-latest.osm.bz2 \
  -e OVERPASS_DIFF_URL=http://download.openstreetmap.fr/replication/europe/belgium/minute/ \
  -e OVERPASS_PLANET_SEQUENCE_ID=2884687 \
  -v /big/docker/overpass_db/:/db \
  -p 12345:80 \
  -i -t \
  --name overpass_belgium wiktorn/overpass-api`

It proceeds to pull the image from dockerhub and download the planet file.
After that it starts reading the XML file and the error occurs. As I said, I tried with small countries and they worked great. The line `terminate called after throwing an instance of 'File_Error'` isn't always present but the rest is.

Any help is much appreciated.

**Comment by mmd-osm** [comment]
ping @wiktorn

**Comment by wiktorn** [comment]
By default Docker image uses gz compression.

I didn't have any problems with creating Nominatim instance for Poland which has similar size as Belgium. It uses ~30GB of disk and my virtual machine has 16GB of memory allocated.

@Jern97 Maybe you can check `/big/docker/overpass_db/` for any errors in logfiles?

**Comment by Jern97** [comment]
I don't think i can access that because the container is doesn't want to run (Exited (134) error).  I already have a Nominatim running running of Belgium and that was also not a problem. The issue is also not only present in your image. I've tried every single docker image for overpass I could find online and they all produce the same error. That's what made me believe it's something with overpass in general. I've also monitored RAM en disk usage while it's loading the data and it stays at acceptable levels.

**Comment by mmd-osm** [comment]
@wiktorn : which exact overpass Version did you include in your docker image? We had an issue with meta=no in September 17, so I’d definitely recommend to use the very latest 0.7.54.xx version available on dev.overpass-api.de/releases

**Comment by Jern97** [comment]
I've tried with meta=yes and got the same result. I've managed to export the container to a .tar file but i don't see any log files in the /db directory.

**Comment by mmd-osm** [comment]
@Jern97 : did you clean up /big/docker/overpass_db/ before starting a new import?

**Comment by Jern97** [comment]
I always removed and created a new docker-machine so I assume that directory is wiped?

**Comment by mmd-osm** [comment]
Your mapping a local directory into a docker container, so that may not be the case. The database itself resides outside of the container iirc.

**Comment by wiktorn** [comment]
Database is mapped to local directory here:
`/big/docker/overpass_db/:/db`

So you should find your database in `/big/docker/overpass_db`.

As for the version, I'm basing it on what is in master branch - so it will be 4cc57fbb124b491abee850f1687a7e8dcb722fc0

**Comment by mmd-osm** [comment]
Taking the master branch is a pretty bad idea, all the bug fixes are in a different (Minor_issues) branch!

**Comment by Jern97** [comment]
I'm on windows and i don't see the `/big/docker/overpass_db/`  directory anywhere. (sorry if i'm missing something elementary here)

**Comment by wiktorn** [comment]
@Jern97 and btw: I'm running Poland Nominatim instance in Docker container.

@mmd-osm But those fixes weren't released yet? 

@Jern97 You should look inside the virtual machine that is running docker container.

**Comment by wiktorn** [comment]
@Jern97 You can try with docker image `wiktorn/overpass-api:minor_issues` - this includes the fixed @mmd-osm is mentioning.

**Comment by Jern97** [comment]
Yes, i'll give that a try. It's my understanding that if I remove a docker-machine that i remove the entire VM? So if I create a new docker-machine each time I try to run it, it should be clean?

**Comment by mmd-osm** [comment]
@wiktorn : just ignore what you see on GitHub. Roland has a different build process and puts released versions on dev.overpass-api.de as I mentioned before.

**Comment by Jern97** [comment]
When I try to run the minor_issues image:
`Error response from daemon: manifest for wiktorn/overpass-api:minor_issues not found.`

**Comment by wiktorn** [comment]
@Jern97 It's still building:
https://hub.docker.com/r/wiktorn/overpass-api/builds/

(strange that it takes so much time)

@mmd-osm Would be great to know, which branch to track though.

**Comment by Jern97** [comment]
It didn't solve the problem unfortunately it still says:
`Reading XML file ... elapsed node 2689644801. Flushing to database ../app/bin/init_osm3s.sh: line 44:    11 Broken pipe             bunzip2 < $PLANET_FILE
        12 Killed                  | $EXEC_DIR/bin/update_database --db-dir=$DB_DIR/ $META $COMPRESSION`

I also monitored RAM usage and it doesn't get above 70%.

**Comment by mmd-osm** [comment]
That’s a different error message now, and killed looks more like an out of memory condition.

**Comment by Jern97** [comment]
I tried doing the regular install on a VM running Ubuntu and everything went flawlessly. So i'll be using that instead. Thanks for help!

**Comment by mmd-osm** [comment]
> @mmd-osm Would be great to know, which branch to track though.

@wiktorn : again, please refer to the released versions on dev.overpass-api.de/releases **only**. In your Docker image, you've merged the current new_features branch, which hasn't been released yet. It is still in development, might contains bugs, etc.

To an average user your Docker image looks like an official build, but it isn't, and it makes it very hard to chase bugs later on, as nobody has an idea, what they're really looking at in the Docker image.

**Comment by mmd-osm** [comment]
Official releases are not meant to be merged, you just download the tar.gz file, compile it, and you're done. Builds are created via `make dist`, where all of the irrelevant stuff gets removed, also the directory structure in the build will differ. The hash value of the last commit included in the build is part of the version string in settings.cc.

**Comment by wiktorn** [comment]
@mmd-osm Ok, I changed the way Docker images are created:
https://hub.docker.com/r/wiktorn/overpass-api/~/dockerfile/

For some older versions I had some problems with building so not all historical versions are available, but I guess that nobody would like to run such old Overpass

**Comment by mmd-osm** [comment]
@wiktorn : great, thanks a lot. 

> For some older versions I had some problems with building 

Yes, that may very well be the case. Roland changed the whole process for 0.7.54 iirc. If you come across any issues with released versions, don't hesitate to create an issue for it on this repo.

**Comment by wangai** [comment]
@JeroenGar @wiktorn 

Its a memory issue, I solved it by allocating 4G swap before importing a 303Mb partial planet file. (I tried allocating 2G without success)

`$ sudo fallocate -l 4G /swapfile`
`$ sudo chmod 600 /swapfile`
`$ sudo mkswap /swapfile`

#### Server specs
1vCPU
2G ram
25G SSD

**Comment by developez** [comment]
I got the same issue running docker.

```
docker run \
  -e OVERPASS_META=yes \
  -e OVERPASS_MODE=init \
  -e OVERPASS_PLANET_URL=http://download.geofabrik.de/europe/spain-latest.osm.bz2 \
  -e OVERPASS_DIFF_URL=http://download.openstreetmap.fr/replication/europe/spain/minute/ \
  -e OVERPASS_RULES_LOAD=10 \
  -v /mnt/vol_2_elastik_data/overpass-api-db:/db \
  -p 12345:80 \
  -i -t \
  --name overpass_spain wiktorn/overpass-api
```

![image](https://github.com/drolbr/Overpass-API/assets/1931408/e670dc07-b9d4-4468-81af-b085fd0ce91e)

**Comment by zackfuchtel** [comment]
try 64bit, eg: docker buildx build --platform linux/arm64/v8...
