### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by anroesti** [drolbr/Overpass-API#472]
Consider the following two queries:

    node[name="Langmauerstrasse"]->.a;
    node[name].a;

vs

    node[name="Langmauerstrasse"]->.a;
    node[name]->.b;
    node.b.a;

The performance difference is vast.

If the implementation on the server were to "inline" the variable declaration of `b` and thus notice that the first restriction (the one for `a`) also applies, less data would need to be fetched.

Has this idea already been considered?

**Comment by mmd-osm** [comment]
Not sure if I understand your example. It is expected that `node[name]->.b;` currently runs on the whole planet and produces lots of data.  Can you share a real world example, where this is an issue?

**Comment by anroesti** [comment]
I understand that `node[name]` will obtain lots of data when the query is run on its own (that's the point of the example). However, performance could be improved if the next line in the query was considered, which imposes another restraint on which data to select (`name=Langmauerstrasse`).

In other words, if you go back from the output value, all filters applied to the end result may also be applied to intermediate results to improve performance and reduce strain on the server.

I do not have a real-world example as I am only just getting started with building my application; I was just surprised your implementation does not do this optimization.
