### ISSUE TITLE
Negative way-ids result in weird ways reffering to one node

### ISSUE THREAD

**Issue by anselmstordeur** [drolbr/Overpass-API#474]
I modified a working planet file in JOSM (`JOSM/1.5 (13500 en)`). 

Resulting in new ways looking like this: 
```xml
<way id='-42024' action='modify'>
   <nd ref='-42022' />
   <nd ref='-42023' />
   <nd ref='-42025' />
   <nd ref='-42031' />
   <nd ref='-42027' />
   <nd ref='-42022' />
   <tag k='ref' v='Confidential data' />
 </way>
```
I bzipped the file and it is read by the overpass api.

When I request the ways via browser they look like this:
```json
{
  "type": "way",
  "id": 4294925272,
  "nodes": [
    18446744073709509000,
    18446744073709509000,
    18446744073709509000,
    18446744073709509000,
    18446744073709509000,
    18446744073709509000
  ],
  "tags": {
     ref: "Confidential data"
  }
}
```

The id is way too high. And the nodes are all the same and the id are too high too.

**Comment by mmd-osm** [comment]
Overpass API does not support negative object ids. Please change them to positive numbers first before loading.

**Comment by anselmstordeur** [comment]
I just did and it worked, but when I reopen the file with JOSM I get `Missing attribute 'version' on OSM primitive with ID 38980`. I checked the diff and it was the first ID where I removed the negation symbol. 

The data is not really Confidential, but not relevant for the question.

**Comment by mmd-osm** [comment]
Well, that's an issue with JOSM then, right? You need to add a fake version id = 1.

Maybe you should take a look at different OSM file formats for further details. https://wiki.openstreetmap.org/wiki/OSM_XML, and https://wiki.openstreetmap.org/wiki/OsmChange, if you're planning on processing updates.

For such general questions, please refer to help.openstreetmap.org, as they're outside the scope of this Overpass issue tracker.

**Comment by anselmstordeur** [comment]
Okay. Thank you.
