### ISSUE TITLE
{{date:X hours}} provides unwanted milliseconds

### ISSUE THREAD

**Issue by goldfndr** [drolbr/Overpass-API#477]
I tried the query `way["highway"="residential"](newer:{{date:24 hours}})({{bbox}});` but it  gives a Query Error:

>...
>Error: line 10: static error: The attribute "than" must contain a timestamp exactly in the form yyyy-mm-ddThh:mm:ssZ.

If one removes the quotation mark after *residential*, one can see that the {{date:24 hours}} is providing a date with milliseconds (e.g. "2018-04-11T10:24:13.510Z") that the *newer* filter apparently doesn't like.

**Comment by mmd-osm** [comment]
`{{date:24 hours}}` is an overpass turbo specific extension, it has nothing to do with Overpass API where you raised this issue.

Please close this issue and file a new one in the overpass turbo repository instead: https://github.com/tyrasd/overpass-turbo/issue

**Comment by goldfndr** [comment]
Ok, thanks.

**Comment by goldfndr** [comment]
Apparently it's discussed/worked around in https://github.com/tyrasd/overpass-turbo/issues/360 (`(newer:"{{date:24 hours}}")`)
