### ISSUE TITLE
Query that used to work is now broken and requires different syntax

### ISSUE THREAD

**Issue by gboeing** [drolbr/Overpass-API#480]
Up until a couple weeks ago, [this query](http://overpass-api.de/api/interpreter?data=[out:json][timeout:180];((way[%22building%22](40.74382349,-73.99157670,40.75283071,-73.97973311);(._;%3E;););(relation[%22building%22](40.74382349,-73.99157670,40.75283071,-73.97973311);(._;%3E;);));out;) always executed successfully and returned all the building footprints within the bounding box. As of today, it no longer works and returns an error instead.

If I now update the [query to this](http://overpass-api.de/api/interpreter?data=[out:json][timeout:180];((way["building"](40.74382349,-73.99157670,40.75283071,-73.97973311);(._;>;););(relation["building"](40.74382349,-73.99157670,40.75283071,-73.97973311);(._;>;);););out;) it now works successfully again (the only change is adding another semicolon before the second-to-last closing parenthesis).

Has something changed in the API to explain this?

**Comment by mmd-osm** [comment]
It has always been documented to require a semicolon but never enforced by the server. This has changed with release 0.7.55 now.

**Comment by gboeing** [comment]
Thanks @mmd-osm

**Comment by mmd-osm** [comment]
There's another update by @drolbr on https://github.com/openstreetmap/openstreetmap-website/issues/1843#issuecomment-387196549:

> I'm sorry. If was of course not intended to break things. However, the omission of the semicolon never was intended as valid syntax. And I never checked that that worked and that anybody used that. I'm sorry for the inconvenience
