### ISSUE TITLE
Dead, nonfunctioning, code in apply_osc_to_db.sh

### ISSUE THREAD

**Issue by rory** [drolbr/Overpass-API#481]
The [current version of `apply_osc_to_db.sh`](https://github.com/drolbr/Overpass-API/blob/4cc57fbb124b491abee850f1687a7e8dcb722fc0/src/bin/apply_osc_to_db.sh) is weird. It has dead code, which can never be run, and even still is broken.

On [line 170](https://github.com/drolbr/Overpass-API/blob/4cc57fbb124b491abee850f1687a7e8dcb722fc0/src/bin/apply_osc_to_db.sh#L170) it checks the `PRODUCE_DIFF` variable, but on [line 55](https://github.com/drolbr/Overpass-API/blob/4cc57fbb124b491abee850f1687a7e8dcb722fc0/src/bin/apply_osc_to_db.sh#L55) that is set to an empty string, and that variable is never changed. This inner part can never run. A [commit 4½ years ago (`93f7bd4798c`)](https://github.com/drolbr/Overpass-API/commit/93f7bd4798cf1d935e3b744ddc9fbf9fb8fd0e01) changed that.

On [line 94](https://github.com/drolbr/Overpass-API/blob/4cc57fbb124b491abee850f1687a7e8dcb722fc0/src/bin/apply_osc_to_db.sh#L170), (which can never be called), `update_database` is called with a `--produce-diff` argument, but I think that [was removed ~2 years ago in `65eec60`](https://github.com/drolbr/Overpass-API/commit/65eec60a60069add05800f224752957c890b682c)

What's going on? Does this just need a simple clean up, and deletion?

**Comment by rory** [comment]
Sorry, you're right. The version in `minor_issues` doesn't have this issue.

It is a little strange that `master` is so out of sync. :)

**Comment by mmd-osm** [comment]
Quick comment on your wiki update: minor issues branch doesn’t have to be stable, so using it for a fresh install is not really recommended. Also this could change again in the future. The only bullet proof solution at this time is to use released versions on the url I mentioned earlier.
