### ISSUE TITLE
if:count(ways) query

### ISSUE THREAD

**Issue by DaveF63** [drolbr/Overpass-API#489]
Hi
To my mind the routine shouldn't be returning Tottenham Court Road as the count of ways is zero.
What am I missing?

I want to print out any `railway=station` which has a `building=train_station` within 20m of it.

```
nwr[railway=station](51.5150,-0.1371,51.5238,-0.1224)->.Stat;
foreach.Stat->.Elem(
 way(around.Elem:20)[building=train_station]->.xx;
 way.xx(if:count(ways) != 0);
   .xx out count; .Elem out center; 
);
```

[Overpass Link](http://overpass-turbo.eu/s/zWX)

**Comment by mmd-osm** [comment]
I think you need to look at if block statements, because right now .Elem is always returned regardless of the number of ways.

https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#The_block_statement_if

**Comment by DaveF63** [comment]
Thank you for the solution. It works as I wanted.
Although I still don't understand why the` If:count` line is testing:
```
nwr[railway=station](51.5150,-0.1371,51.5238,-0.1224);
foreach(
 way(around:20)[building=train_station];
 way._(if:count(ways) != 0);
   out count; 
);
```
http://overpass-turbo.eu/s/zXG

Note if this line is change to;
`way._(if:count(ways) == 0);`
it amends all the outputs to `<tag k="ways" v="0"/> 
`
I developed my routine from:
https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_API_by_Example#Isolated_Buildings

**Comment by mmd-osm** [comment]
* `way(around:20)[building=train_station];` stores a number of building=train_station way in the default set `._`. if they're no further away than 20m from a single railway=station.
* `way._(if:count(ways) != 0);` uses all the ways in the default inputset `._` and filters this list as a whole based on the filter criterion `(if:count(ways) != 0)`. So if the previous query returned more than 0 ways, all those ways are then again stored in the default inputset `._` -  
If you turn that filter into `(if:count(ways) == 0)`, you would either filter out any existing ways in the inputset, or if there are no ways in the inputset to start with, you would still get zero entries as a result.
* `out count;` always prints the number of nodes, ways and relations in the current default inputset `._` - this is different from `out center;` in the example, which doesn't output anything, if the inputset is empty.

**Comment by mmd-osm** [comment]
If there are no further questions, can you please close this issue? Thanks.

**Comment by DaveF63** [comment]
I was still trying to assimilate your helpful explanation, but... closed.
