### ISSUE TITLE
Return entities with duplicate names

### ISSUE THREAD

**Issue by DaveF63** [drolbr/Overpass-API#491]
Hi
I want to select all `railway=stations` & return any which have the same name.

I've used [This wiki example](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_API_by_Example#Find_relations_with_identical_wikidata_tags_.28since_0.7.54.29) as a starting point.

This is as far as I got:
```
[bbox:{{bbox}}];
nwr[railway=station][name]->.a;
foreach .a -> .b (
  nwr.a(if:t["name"] == b.u(t["name"]))->.d;
);
.d out center;
```
It appears to only return the last found duplicates, so I added a line to try & collect them together:
```
[bbox:{{bbox}}];
nwr[railway=station][name]->.a;
foreach .a -> .b (
  nwr.a(if:t["name"] == b.u(t["name"]))->.d;
  (.d ; .result; ) -> .result;
);
.result out center;
```
But it returns all stations in the bbox.

This [Overpass Example](http://overpass-turbo.eu/s/Acc) would hopefully return New Cross Gate station as well as Greenwich.

----
From the [Union/Set wiki page](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Aggregators) its unclear to me what `u` returns if there are multiple values found.

**Comment by DaveF63** [comment]
Thanks for that. It appears to work, except as I test it I'm getting this almost all the time, even over a small area as per my previous Turbo query:
![image](https://user-images.githubusercontent.com/9528328/42577329-f942b65a-851b-11e8-9c16-f0869a4837a3.png)

As it was only comparing `names` I'm surprised it causes a problem when it checks against itself.

**Comment by mmd-osm** [comment]
>  I'm surprised it causes a problem when it checks against itself.

Pretty. Let's assume you have a list of 5 stations and iterate over each of them. Each time you check if the name occurs in the list of 5 stations. This way, you will always get at least one hit, namely the very same station you're looking at.

The error message means: you're kicking off too many queries, and your quota is exceeded. The query is simply too expensive, just wait a bit.

**Comment by DaveF63** [comment]
Got it, thanks.

>The error message means: you're kicking off too many queries, and your quota is exceeded. The query is simply too expensive, just wait a bit.

I received it the first time I ran it this morning, which is why I mentioned it.
How is this routine overloading my quota? The only call for data is `nwr[railway=station][name]->.a;`, which on its own is easily dealt with. Where is the calculation preformed: Server or Client side?

PS What does 'pretty' mean in this context?

**Comment by mmd-osm** [comment]
> I received it the first time I ran it this morning, which is why I mentioned it.

Hmm. that's interesting. Are behind some kind of proxy. This could be the case for mobile access with NATed internet access. The calculation is always done on the server side, as the client has no idea about the total server load.

**Comment by DaveF63** [comment]
I don't believe so. Standard ISP connection via BT in UK.

>The calculation is always done on the server side, as the client has no idea about the total server load.

I'm getting either the error message above or a time out [300] on ~250 stations. That doesn't seem that many to iterate.

**Comment by mmd-osm** [comment]
Ok, let's try something entirely different then. The following also finds duplicates, but is a whole lot faster:

```
[bbox:{{bbox}}];
nwr[railway=station][name];
for(t["name"]) {
  if(count(nodes) + count(ways) + count(relations) > 1) {
    out geom;
  }
}
```

**Comment by DaveF63** [comment]
OK, much faster, but on rereading the wiki I don't think I'd ever have worked that out. Most For Loops I've encountered are just counters `for x=1 to 8` etc not comparisons.

Some examples in the wiki would be very helpful. Thanks

**Comment by drolbr** [comment]
A [section](http://dev.overpass-api.de/blog/loop_and_group.html#for) of one of the blog posts features the _for_ statement

**Comment by DaveF63** [comment]
Very Helpful. Thanks
