### ISSUE TITLE
How to request quota

### ISSUE THREAD

**Issue by ppKrauss** [drolbr/Overpass-API#498]
I can use other IP, but ideal is to request more quota for my IP... How to request quota?

PS: both, `http://overpass-turbo.eu` and `http://overpass-api.de/api/interpreter?data=` with same error message.

**Comment by mmd-osm** [comment]
If you exceed your quota this means you're sending too many, and/or too expensive quotas. Either wait for some time, switch to another server, or set up your own Overpass instance. As the public servers are shared resources and have a total capacity limit, there's no way to increase your quota without affecting other users.

**Comment by mmd-osm** [comment]
BTW: you have been asked **multiple times** to run your full planet Wikidata analysis on a local planet file instead. You seem to totally ignore those recommendations and keep on posting messages like the following:

https://help.openstreetmap.org/questions/65130/why-http-request-failed

https://gis.stackexchange.com/questions/288751/how-to-generate-a-csv-file-from-overpass-with-id-and-tag-value

This behavior is not acceptable. https://github.com/OSMBrasil/semantic-bridge/issues/2 needs to stop **right now**.

**Comment by ppKrauss** [comment]
Hi @mmd-osm , the  "full planet Wikidata analysis" is not a goal to this year (!), and we need money to run the planet in a server... For now we elected AR, BR, GW (all little-data) and DE (the only big-data).

**Comment by mmd-osm** [comment]
Please download the respective country extract from download.geofabrik.de and use osmium tool to extract those wikidata features instead.

**Comment by ppKrauss** [comment]
@mmd-osm thanks, I will [delete questions](https://help.openstreetmap.org/questions/65130/why-http-request-failed) to avoid other people testing big-data queries...  


-----

Using `apt` in a DigitalOcean's 2 GB Memory / 60 GB Disk / Ubuntu 16.04.3 x64.

```
osmium --version
osmium version 1.3.0

df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           201M   21M  180M  11% /run
/dev/vda1        58G   15G   44G  26% /
...    ...
```
So, lets try the so big Europe with its 18.3 GB of .osm.pbf...

**Comment by ppKrauss** [comment]
Hi @mmd-osm , I installed newer (!), "osmium version 1.7.1 / libosmium version 2.13.1"... 

I am looking for the "recipe" of the query, to obtain a CSV file as `<wikdidata-id,osm_type,osm_id>` as minimal goal.

1. `osmium tags-filter liechtenstein-latest.osm.pbf w/wikidata -o wikidata-in-liechtenstein-latest.osm.pbf` 
2. hum... ?  `osmium show wikidata-in-liechtenstein-latest.osm.pbf`  shows the *osm_type* and *osm_id*  but no Wikidata-ID, that is the tag-value.  ... No Google or [osmium-tool/manual](https://osmcode.org/osmium-tool/manual.html) information about extract datasets.

**Comment by ppKrauss** [comment]
.... Will solve as a **simple XML attribute extraction problem**, instead a "looking for tool and query" problem...  The basic is working (!). Example:

1. `osmium tags-filter germany-latest.osm.pbf nwr/wikidata -o wikidata-in-germany-latest.osm.pbf`
2. `osmium cat -f osm  wikidata-in-germany-latest.osm.pbf -o wikidata-in-germany.osm`
3. so.. now we can test a so basic XML extraction ...<br/>`grep wikidata wikidata-in-germany.osm | wc -l` = 76572<br/>`grep wikidata wikidata-in-germany.osm | uniq -u | wc -l` = 67934

**Comment by mmd-osm** [comment]
You could try the OPL output format - it will return all information for an object in a single line: https://osmcode.org/opl-file-format/

If you really need CSV output, you should probably also take a look at osmconvert: https://wiki.openstreetmap.org/wiki/Osmconvert#Writing_CSV_Files

**Comment by mmd-osm** [comment]
In case there are no further questions please close this issue. Thanks!
