### ISSUE TITLE
SSL certificate of overpass-api.de expired

### ISSUE THREAD

**Issue by PanierAvide** [drolbr/Overpass-API#499]
Hi,
It seems that SSL certificate of overpass-api.de has just expired today, leading web browser into error message and not allowing connexion.
Regards.

**Comment by mmd-osm** [comment]
Please report operation issues only on the Wiki status page: https://wiki.openstreetmap.org/wiki/Overpass_API/status

This repository is only for bug reports and enhancement requests.

**Comment by PanierAvide** [comment]
OK, wasn't aware of this page, thanks for letting me know ;-) As it is already taken in account I'm closing the issue.
/close
