### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by DaveF63** [drolbr/Overpass-API#500]
Hi
I'm finding Overpass's blog very useful, but frustrated that many code example throw an error in OP Turbo. Would it be possible to check & update them please?

Examples:
    `name = set(t[name]),` requires quotation marks around 'name' 
   ` (._; .result)->.result;` requires a semi-colon after the first 'result'

**Comment by mmd-osm** [comment]
There's a dedicated repo for the blog: https://github.com/drolbr/overpass-blog

**Comment by DaveF63** [comment]
Thanks
