### ISSUE TITLE
Reg-ex & '\w?' problem.

### ISSUE THREAD

**Issue by DaveF63** [drolbr/Overpass-API#502]
Hi

Which variant of reg-ex has been implemented?

I'm have trouble getting '\w?' to work as expected, which is to find results if there is, or isn't, a single word character. 

```
[bbox:{{bbox}}]; 
way[highway][ref~"^U.*"];
//way[highway][ref~"^U\w?[0-9]+$"];
out geom;

{{style:
way[ref=U2]{color:green;}
way[ref=UX9]{color:red;}
}}
```

http://overpass-turbo.eu/s/B0H

Note the different refs. Swap to the other reg-ex & for some reason it ignores all UX*.

I've tested the reg-ex externally (in Notepad++) & filters as expected. Is there an alternative to '\w' to use?

**Comment by mmd-osm** [comment]
Posix regex are currently in use. Note that you need to escape the \ backslash by another backslash: \\w

**Comment by DaveF63** [comment]
That works of course, thanks, but I'm struggling to understand why there's a requirement to escape a backslash if it isn't to be searched for. Shouldn't \w' be interpreted as a reg-ex instruction. 
I can't find examples of this; is it a Posix or OP requirement?

**Comment by mmd-osm** [comment]
It's mentioned a couple of times in the Overpass QL documentation:

https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Value_matches_regular_expression_.28.7E.2C_.21.7E.29:

`Please note that in QL you need to escape backslashes`

https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Escaping:

`\\ escapes the backslash`

This kind of escaping is rather typical for C-style strings.

**Comment by DaveF63** [comment]
Ta
