### ISSUE TITLE
Idea: Simplified query syntax

### ISSUE THREAD

**Issue by westnordost** [drolbr/Overpass-API#505]
This post is meant more like a food for thought than as a concrete feature wish.
For StreetComplete, I created a simplified (much less powerful) query syntax which is parsed into proper Overpass QL. For about 80% of all implemented quests, I happily use this syntax because of better readability in the source code and only for the more complex queries, I fall back to Overpass QL.

**Some examples**:

Find all bus stops with no shelter-information:
`nodes tagged ((public_transport=platform and (bus=yes or trolleybus=yes or tram=yes)) or (highway=bus_stop and public_transport!=stop_position)) and !shelter`

Find all restaurant without vegetarian diet information:
`nodes, ways tagged amenity ~ restaurant|cafe|fast_food and name and diet:vegetarian ~ yes|only and !diet:vegan`

The major advantage over OQL is easier readability and the arbitrary nesting of logical `and`s and `or`s.

### I was wondering if you think it would be a good idea to introduce a kind of simplified syntax directly in Overpass as an alternative to the full show.

I think it would greatly increase the accessibility of Overpass and reduce the necessary documentation.

Developing further on the syntax examples given above, even pretty advanced features could find their place in such a query language leaned against natural language. Some more possibilities (not implemented in Streetcomplete):

Find all ways included in "Fahrradroute 6":
  `ways of relations tagged ref="Fahrradroute 6"`

Find all entrances to buildings:
  `nodes of (ways, relations with building) tagged entrance~yes|main`
_(I turned it around here, just as a food for thought)_

Find all bus stops not in any public transport relations:
  `nodes tagged highway=bus_stop not in relations tagged type=route`

Find all buildings without housenumber which do not contain any nodes with housenumber:
  `ways, relations tagged building and !addr:housenumber not containing nodes tagged addr:housenumber`

Find all footways which are likely sidewalks:
  `ways tagged highway=footway around 30m of ways tagged highway~residential|unclassified|`etc

etc...

What keywords there could be would be TBD. But to summarize and extend on the examples. Possible would be:
- `tagged` for starting tag rules
- `of`` to traverse down
- spatial containment in any: `containing`, `inside`
- spatial location to to other elements: `around ... of` 
- `older than`, `newer than` or `changed after` / `changed before` ...
- all keywords can be prepended by `not`

**Comment by mmd-osm** [comment]
Besides Overpass XML and QL, and XAPI via the compatibility layer, this would be like introducing a forth language variant... 

IMHO, it would make more sense to try and include this into the overpass turbo wizard, which to some extent looks quite similar to your proposal.

**Comment by westnordost** [comment]
But who uses still XAPI (and Overpass XML)?

**Comment by mmd-osm** [comment]
Much more people than you could possibly think of. Also, Overpass XML is buried pretty deep in the whole implementation (as it was the first supported format), and is still around in many places even today.

**Comment by mmd-osm** [comment]
In fact, the wizard is a completely standalone library you can use even from command line: https://github.com/tyrasd/overpass-wizard - or - embed into other applications. It's not coupled to overpass turbo in any way.

**Comment by westnordost** [comment]
Interesting. But still, I find this is still everybody brewing their own stew - these "wizards" and ports (including the one in StreetComplete because it is pretty much the same) only exist because the OQL syntax is not that accessible. A more accessible "natural language"-alike syntax would make all this obsolete.

Anyway, I see I can't really enthuse you for the idea, so I will close this.

**Comment by mmd-osm** [comment]
You can still try and discuss this idea with Roland (@drolbr), I'm just trying to assess the overall approach and give you some insights as to where I see some potential issues.

I have to say that I find the idea to have better QL coverage in the wizard very compelling, as it still lacks many of the most recent features. Having some more real world requirements as in the case of StreetComplete can only make it better.

The main issue with another language is also that there's very limited development capacity, many other topics, and as already mentioned, the overall issue of code complexity. Even today, having both QL and XML around is difficult, as they have to be kept in sync, every feature must be implemented to that it becomes usable from both QL and XML, and of course, the QL <> XML conversion also has to cover every new feature.

**Comment by westnordost** [comment]
I understand this, absolutely. In a popular and live product, to keep it working for users takes precedence over innovation, and this is of course also in the best interest of them. This is why I closed it, I reckon the manpower on Overpass is limited.

Maybe the best way to go on about this for someone enthused about a syntax more oriented on natural language (I myself also have not time for this right now) would be to have a separate project that only defines that DSL in an EBNF, supply a parser for that and a compiler into OQL. (I heard there are tools that help to generate a parser for a given EBNF in various programming languages)

**Comment by mmd-osm** [comment]
By the way, the wizard is already DSL based, using PEG.js (and https://en.wikipedia.org/wiki/Parsing_expression_grammar) to generate Javascript code based on https://github.com/tyrasd/overpass-wizard/blob/master/wizard.pegjs
