### ISSUE TITLE
id list does not return all objects when using global setting date

### ISSUE THREAD

**Issue by pierzen** [drolbr/Overpass-API#506]
A query for 16 ways, works ok with current data but returns only 4 ways using [date:"2016-08-16T00:00:00Z"]

query:
[out:xml][date:"2016-08-16T00:00:00Z"]; way(id: 385354616,385354625,389796063,390496488,594952195,594952206,594952207,594952211,594952213,594952214,594952216,594952218,594952222,594952226,594952228,594952250 ); out meta;>;out meta;

**Comment by mmd-osm** [comment]
Ways are not only returned if they existed at the given point in time. As an example, way 594952222 was created in 2018, so it will not be returned by your query.

**Comment by pierzen** [comment]
Oh sorry, my mistake, did a long explanation about how I should have all current data at 2018-08-16. Re-reading, I see 2016 !
