### ISSUE TITLE
The overpass QL converter adds unwanted semicolons to difference block statement

### ISSUE THREAD

**Issue by yaugenka** [drolbr/Overpass-API#507]
E.g. converting this query into pretty overpass QL

`(node(id:243236601,1137172767);-node(1137172767););out;`

produces the following result (note the extra semicolons)

`(`
`  node(243236601,1137172767);;`
`  -`
`  node(1137172767);;`
`);`
`out;`

The same thing happens when you convert to compact overpass QL.

Note that in this one-line query works with overpass turbo well.

**Comment by drolbr** [comment]
Fixed in 499108b0a20d3ad40599ffd03d25b4a031b01cfa
