### ISSUE TITLE
Overpass API double admin_level for one coordinate (is_in)

### ISSUE THREAD

**Issue by mebels** [drolbr/Overpass-API#508]
Overpass API delivers a result with two "admin_level: 4" entries for one coordinate as shown:

http://overpass-api.de/api/interpreter?data=[out:json];is_in(%2253.166591%22,%229.841431%22);out+body;%3E;out+skel;

This leads to filtering problems. How does that happen?

**Comment by mmd-osm** [comment]
This is exactly the same question as posted here: https://gis.stackexchange.com/questions/294221/overpass-api-double-admin-level-for-one-coordinate-is-in

Did you check my comment there?

**Comment by mebels** [comment]
https://help.openstreetmap.org/questions/65695/overpass-api-double-admin_level-for-one-coordinate-is_in
