### ISSUE TITLE
Network name containing & character is not parsed correctly

### ISSUE THREAD

**Issue by miklcct** [drolbr/Overpass-API#511]
In the following web form, when I try to type in `九龍及新界巴士 Kowloon & NT Bus` as the network:

http://www.overpass-api.de/public_transport.html

It returns an empty page.

**Comment by mmd-osm** [comment]
Please provide the full url which is shown after you entered the data and hit submit.

**Comment by miklcct** [comment]
http://www.overpass-api.de/api/sketch-line?network=%E4%B9%9D%E9%BE%8D%E5%8F%8A%E6%96%B0%E7%95%8C%E5%B7%B4%E5%A3%AB+Kowloon+%26+NT+Bus&ref=58X&operator=

**Comment by mmd-osm** [comment]
Seems like a bug in the code. You can try the following for the time being as long as the issue hasn't been fixed.

http://www.overpass-api.de/api/sketch-line??network=%E4%B9%9D%E9%BE%8D%E5%8F%8A%E6%96%B0%E7%95%8C%E5%B7%B4%E5%A3%AB+Kowloon+%26+NT+Bus&ref=58X

**Comment by mmd-osm** [comment]
Actually, this is a duplicate of #397.

Please close this issue, and follow up in #397. Thanks!
