### ISSUE TITLE
Increase default timeout

### ISSUE THREAD

**Issue by pangoSE** [drolbr/Overpass-API#512]
For some reasons every query I tried times out multiple times if timeout is less than 200s.
See also: https://wiki.openstreetmap.org/wiki/Overpass_API/status

**Comment by matkoniecz** [comment]
Can you give specific examples? Anyway, it sounds like a temporary issue.

**Comment by mmd-osm** [comment]
I tried both examples but I cannot reproduce the issue. `place=locality in sweden` took 22s to complete.

Which Overpass API server instance are you running on?

> despite the recent change of default timeout from 25->90s

Which change is that? In JOSM?

**Comment by pangoSE** [comment]
Thanks for the very quick replies. This was also destined for overpass-turbo.
