### ISSUE TITLE
Improve wizard page with hints regex and case-insensitive like in JOSM

### ISSUE THREAD

**Issue by pangoSE** [drolbr/Overpass-API#513]
I suggest adding something like this to help newcomers get started.
I also suggest to include a recommendation about using the API through JOSM to ease working with the data.  

In JOSM the Wizard page now includes this explanation below the input-field:
![skarmavbild vid 2018-10-30 13-33-28](https://user-images.githubusercontent.com/11300782/47718072-bc9d1500-dc47-11e8-96d2-7f14b0c750f2.png)
![skarmavbild vid 2018-10-30 13-33-48](https://user-images.githubusercontent.com/11300782/47718074-bdce4200-dc47-11e8-8ba3-a6da8fa384c9.png)

**Comment by mmd-osm** [comment]
This is the wrong repository, you probably want this in overpass turbo, right?
