### ISSUE TITLE
SSL in API is failing (expired certs)

### ISSUE THREAD

**Issue by jperelli** [drolbr/Overpass-API#515]
Seems that the certificate from letsencrypt expired on november 3 (yesterday). If you need any help, I'm available

![image](https://user-images.githubusercontent.com/1418446/47959746-cbc6ee80-dfca-11e8-9cdc-5cc9b3f68fd2.png)

**Comment by mmd-osm** [comment]
Thanks for the report. Please note that operation issues should be reported on the Wiki page. This issue tracker is only meant for bug reports and enhancement requests.

Meanwhile, the automated certificate renewal job kicked in, so you can simply close this issue without any further action needed.

**Comment by jperelli** [comment]
Awesome, it's working. Sorry for reporting in the wrong place! Thanks!

**Comment by kocio-pl** [comment]
There's a way to make automatic certificate renewal by Let's Encrypt:

https://certbot.eff.org/docs/using.html?highlight=renew#automated-renewals

**Comment by mmd-osm** [comment]
@kocio-pl : that’s exactly what meant above by certificate renewal job.
