### ISSUE TITLE
Overpass returning fewer items when zoomed further out

### ISSUE THREAD

**Issue by DaveF63** [drolbr/Overpass-API#516]
Hi

This query returns around 2000 or so items depending on the size of the browser window. http://overpass-turbo.eu/s/Dr4

If I click once/twice on the 'minus' zoom out button & run again it returns 27. I get the same results if running the query direct from the command line.

What is it filtering out?  If their are too many for OPT to handle, I would usually expect this to timeout & throw an error dialog. Has something in the code changed?

Cheers
DaveF

**Comment by mmd-osm** [comment]
That's a bug, which most likely related to #192.

If you zoom in, you're getting way too many results. This is due to `[!"fhrs:id"]` not getting considered properly. When zooming out, the query is processed in a different way, which means that [!"fhrs:id"] is handled correctly.

**Comment by mmd-osm** [comment]
filter_ids_by_ntags is really unhappy with duplicates in ids_by_coarse_.

**Comment by mmd-osm** [comment]
@DaveF63 : can you try this one? I think the issue should be fixed here: http://overpass-turbo.eu/s/Dyb

**Comment by DaveF63** [comment]
Yes, that sorts it. Thanks
I realise now my routine wasn't returning what I was expecting & so you're correct - The zoomed in version was return the wrong data.

How long does the solution usually take to add to the main server?

**Comment by mmd-osm** [comment]
@DaveF63 : as the issue has been resolved in the meantime, can you please close the issue? Thanks.
