### ISSUE TITLE
Choice of objects colours on the map

### ISSUE THREAD

**Issue by pyrog** [drolbr/Overpass-API#517]
Currently, the color/style is set on object type (node, way, relation).

I would like to select it for a specific tag:

- amenity=fire_station -> red
- amenity=police -> blue
- …

**Comment by mmd-osm** [comment]
This is a question for overpass turbo I guess? Please open a new issue there and close this one. Thank you.

**Comment by pyrog** [comment]
Yes, sorry 🤭
