### ISSUE TITLE
Named sets do not store unions as default set does

### ISSUE THREAD

**Issue by tilusnet** [drolbr/Overpass-API#52]
[Union definition](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#union) describes
{1} `(node[name="Foo"];way[name="Foo"];);`
and
{2} `(node[name="Foo"];way[name="Foo"];)->.a;`
as being equivalent with the exception that the latter stores the result in ".a".

However a test executing
{1} `(._;>;); out;`
and 
{2} `(.a;>;); out;`
for those two cases shows that the two sets are not equivalent.

I suspect they should be?

While trying various commands I found that if named sets are 'reunionised' and redirected to the default set, i.e.
{2'} `((.a);>;); out;`
then the results yielded by case {1} and {2'} are equivalent.

**Comment by mmd-osm** [comment]
@tilusnet : does this answer your question? If there's nothing left to do, could you be so kind and close this issue? Thanks.

**Comment by drolbr** [comment]
Fixed in 5ed2b42e3c17a12137889f6de79081ab981f0518
