### ISSUE TITLE
overpass-api.de blocked in russia

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [drolbr/Overpass-API#520]
I know, the subj is not your problem

https://isitblockedinrussia.com/?host=overpass-api.de
https://isitblockedinrussia.com/?host=www.overpass-api.de

But the easiest way give access from Russia is to switch to another ip.

**Comment by c-e-p-x-u-o** [comment]
https://isitblockedinrussia.com/?host=lz4.overpass-api.de
https://isitblockedinrussia.com/?host=z.overpass-api.de
are also blocked

**Comment by c-e-p-x-u-o** [comment]
178.63.0.0/16 is hetzner subnet, right? Please ask them to provide not blocked ip.

**Comment by mmd-osm** [comment]
This repo is for bug reports and enhancement requests in the software. You're reporting an operations issue.

I think it would be better to do a follow up as described by Roland here and close this issue: http://gis.19327.n8.nabble.com/No-access-to-Overpass-API-td5921900.html

**Comment by c-e-p-x-u-o** [comment]
> Forum opst: https://forum.openstreetmap.org/viewtopic.php?id=65012

I know, I've started this topic. It's about unblocking 178.63.0.0/16 on the russian side, but really I don't believe in this.

**Comment by c-e-p-x-u-o** [comment]
> I think it would be better to do a follow up as described by Roland here and close this issue: http://gis.19327.n8.nabble.com/No-access-to-Overpass-API-td5921900.html

Thank you, I've replied to talk.
