### ISSUE TITLE
make node ::geom not working

### ISSUE THREAD

**Issue by sebkur** [drolbr/Overpass-API#525]
I'm trying the following query (in overpass turbo);

    [out:xml][timeout:25];
    (
      make node a="b", ::id="2", ::geom = pt(1,2), b="c";
    );
    out;

I get this:

    <?xml version="1.0" encoding="UTF-8"?>
    <osm version="0.6" generator="Overpass API 0.7.55.5 2ca3f387">
    <note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
    <meta osm_base="2019-03-05T17:17:02Z"/>

      <node id="2">
        <tag k="a" v="b"/>
        <tag k="b" v="c"/>
      </node>

    </osm>

The node does not have `lat` or `lon` values. Is this a bug?

**Comment by mmd-osm** [comment]
You need to use `out geom;` instead of `out;`

**Comment by sebkur** [comment]
That gives me:

      <node id="2">
        <point lat="1.0000000" lon="2.0000000"/>
        <tag k="a" v="b"/>
        <tag k="b" v="c"/>
      </node>

which is also not what I expect

**Comment by mmd-osm** [comment]
Sorry, I don't have a magic crystal ball here. You need to be more specific.

**Comment by sebkur** [comment]
Also, when I add an existing node like this:

    [out:xml][timeout:25];
    (
      make node a="b", ::id="2", ::geom = pt(1,2), b="c";
      node(27410655);
    );
    out;

I don't need to specify any special options on `out` to display the other node's lat and lon attributes:

    <?xml version="1.0" encoding="UTF-8"?>
    <osm version="0.6" generator="Overpass API 0.7.55.5 2ca3f387">
    <note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
    <meta osm_base="2019-03-05T17:33:02Z"/>

      <node id="27410655" lat="52.5184891" lon="13.4026181"/>
      <node id="2">
        <tag k="a" v="b"/>
        <tag k="b" v="c"/>
      </node>

    </osm>

**Comment by sebkur** [comment]
I would like to get something like `<node id="2" lat="1" lon="2">`

**Comment by mmd-osm** [comment]
Ok, I think you want to read this first: https://github.com/tyrasd/osmtogeojson/issues/94#issuecomment-374192890

**Comment by sebkur** [comment]
I mean the `make` command lets me specify the node's id, its tags, but not its lat and lon, I find that strange

**Comment by mmd-osm** [comment]
That's really by design. Derived elements (that what you get when you use `make`) have a bit of their own logic, so that people won't start applying mass changes to the data and re-upload them to OSM.

**Comment by sebkur** [comment]
Okay, interesting. Maybe `make` is just not the right thing for me to use. What I really would like to do is this:

    [out:csv(::id;false)][timeout:25];
    (
      node({{bbox}});<;>;
    );
    out;

This is the result:

    451986 <--. nodes
    451987
    ...
    6314712492
    6314734052
    459168  <--- ways
    4045243
    4067919
    ...
    673599012
    674216636
    674704975
    27727 <-- relations
    28286
    52459
    390274
    ...

What I was trying to do now, is add artificial way and relation with id 0 as a delimiter between nodes and ways, and ways and relations:

    [out:csv(::id;false)][timeout:25];
    (
      make way ::id=0;
      make relation ::id=0;
      node({{bbox}});<;>;
    );
    out;

However, there result is just this, a single 0 added at the bottom of the output:

    ...
    6655583
    7378232
    7388655
    7392626
    0

Is `make` not intended for such purposes?

**Comment by mmd-osm** [comment]
I think the following should work here:

```C++
[out:csv(::id;false)][timeout:25];
(node({{bbox}});<;>;)->.all;
node.all;out ids;
make x ::id = 0;out;
way.all;out ids;
make x ::id = 0;out;
rel.all;out ids;
```

**Comment by mmd-osm** [comment]
Duplicate of https://github.com/drolbr/Overpass-API/issues/236#issuecomment-290998234

**Comment by sebkur** [comment]
Yeah, that works. Thank you for your quick help!
