### ISSUE TITLE
has-kv with an empty string for v doesn't search for empty tags

### ISSUE THREAD

**Issue by tyrasd** [drolbr/Overpass-API#53]
`<has-kv>` with an empty string for `v` behaves like `<has-kv>` without `v`, thus searching for arbitrary values of the tag rather than searching for empty tags:

http://overpass-turbo.eu/s/ZW

The behaviour for a similar OverpassQL query (`node["k"=""]`) is even more strange:

http://overpass-turbo.eu/s/ZX

**Comment by drolbr** [comment]
Empty keys and values did not play any relevant role again.
