### ISSUE TITLE
area "France Métropolitaine" 3602202162 match objets located outside this area

### ISSUE THREAD

**Issue by Marc-marc-marc** [drolbr/Overpass-API#532]
```
area(3602202162)->.searchArea;
node(id:392089339)(area.searchArea);
out;
```
returne the node 392089339 but this node is not in "France Métropolitaine" (but still in France)

another query with the same issue
```
area(3602202162)->.searchArea;
node[wikidata=Q429770](area.searchArea);
out;
```

**Comment by mmd-osm** [comment]
area(3602202162) corresponds to relation 2202162, while "France Métropolitaine" has relation 1403916:

```
area(3602202162);
rel(pivot);
out geom;
```

Seems like you're using the wrong relation. I don't see any bug here.

**Comment by Marc-marc-marc** [comment]
I started from the query on turbo overpass:
`{{geocodeArea:France Métropolitaine}}->.searchArea;
node(id:392089339)(area.searchArea);
out;`
to simplify, I got the id provided in the overpass-api export
does this mean that nominatim returne the wrong relation for France Métropolitaine, id used by overpass turbo to build the overpass api query ?

**Comment by mmd-osm** [comment]
Yes, it seems the issue is caused by Nominatim + overpass turbo: Nominatim returned two different ids, 2202162 and 1403916, and overpass turbo just picked the first one.

In this case it's probably better to directly specify the area you're interested in, rather than relying on a Nominatim lookup.

area["wikidata"="Q212429"]->.searchArea;

**Comment by Marc-marc-marc** [comment]
I'll use `rel(1403916);map_to_area` but ask a question for nominatim, because everybody who is using overpass-turbo wizard currently have the issue.
Thank you for your analysis, sorry for misdirecting the problem.
