### ISSUE TITLE
Make XML Response deserializable with OsmSharp

### ISSUE THREAD

**Issue by blackboxlogic** [drolbr/Overpass-API#533]
OsmSharp can't parse XML responses from Overpass-API because of the "note", "meta" or any other XmlElements which are not part of the [OsmApi's XML format](https://wiki.openstreetmap.org/wiki/API_v0.6#XML_Format).

Could there be (or is there already) a feature to either
- Omit non-conformant XML elements from the XML response, or
- Move non-conformant elements to be the last XML Elements within the "osm" XmlElement.

Related: https://github.com/OsmSharp/core/issues/76

**Comment by mmd-osm** [comment]
Let’s see if this could be possibly fixed in OsmSharp.

**Comment by blackboxlogic** [comment]
Yep, looks like I solve this by changing how I use osmSharp or my making a pull request there.
