### ISSUE TITLE
Area generation: Add documentation about logs and expected outcomes

### ISSUE THREAD

**Issue by calocan** [drolbr/Overpass-API#534]
The current documentation is not complete enough to troubleshoot area creation.

I've followed the docs and issued these commands:
`nohup $EXEC_DIR/bin/dispatcher --areas --db-dir=$DB_DIR &`
`nohup $EXEC_DIR/bin/rules_loop.sh $DB_DIR &`

I've been trying to generate areas for the better part of week. My latest attempts saw the process timeout after 24 hours as the area files grew to around 4GB each. I increased the timeout in the areas areas.osm3s, cleared the area files in the db directory, and restarted. During this last effort, after about 4 hours the logs stopped showing any progress but areas_blocks.bin is still growing at around 2.9GB.

Can you please briefly note here and in the docs 1) What the logs in nohup.out mean about progress and what am I hoping to see. 2) What approximate size area files to expect when it completes with the full rules. 3) How I know when the areas are actually available to the database--every time I query for areas it returns nothing.

This is where my last log ended. I can't find documentation of what these numbers indicate.

`After 4h5m8s: in "recurse", part 0, on line 27. Stack: 0 of 0 1014653 of 0 0 of 0`

Thanks so much for your great work and let me know if you need me to supply more information.

**Comment by mmd-osm** [comment]
>  I can't find documentation of what these numbers indicate.
> After 4h5m8s: in "recurse", part 0, on line 27. Stack: 0 of 0 1014653 of 0 0 of 0

I think 4h5m8s is clear, line 27 should also be clear (it refers to the current line in the areas.osm3s file that is being executed). `recurse` is the statement in that line, 1014653 is the number of current objects. You can pretty much ignore everything else.

The area file sizes typically depend on the compression method you're using, and they might also change over time. Typically they're in the single digit GB range. The area creation should stop with the last line containing an `</osm>` closing XML tag.

One our production servers, area creation takes a few hours, i.e. quite a bit faster than the 24h you mentioned. Maybe you should check, if you're IO or memory bound, move to some faster SSD based disk, check that the process is not paging etc. If nothing helps, try loading a smaller extract, or remove some rules in areas.osm3s you don't need.

**Comment by calocan** [comment]
Great thanks @mmd-osm. I got it working by setting the timeout beyond 24 hours and it finished in about 30 hours on a decent size ec2 instance.
