### ISSUE TITLE
nw and wr shortcuts

### ISSUE THREAD

**Issue by westnordost** [drolbr/Overpass-API#535]
There is already the shortcut `nwr` to query all the element types with the same filters. This is very handy when elements one intends to search for may be of any of the three element types, to keep the query short.

I propose to add further shortcuts for nodes and ways `nw` and ways and relations `wr`.
Many features are documented in the wiki to be used only on nodes and ways, others are documented to be used only on ways and relations (e.g. many area features). Adding these shortcuts helps keeping the queries for these types of elements short and thus better readable.

**Comment by mmd-osm** [comment]
Commit 6f83224bae8aef3cbd62dabe3ac10cce5090efb9, part of 0.7.56 release.

**Comment by goldfndr** [comment]
query.h has been written as

```
      else if (type == (QUERY_NODE | QUERY_WAY))
        return "nwr";
```

Shouldn't the return be "nw"?

**Comment by mmd-osm** [comment]
Yes, https://github.com/drolbr/Overpass-API/blob/oversized_backend_objects/src/overpass_api/statements/query.h#L103 is incorrect. Care to create a new issue for it?

You shouldn't notice this in normal query, that method is only called when converting queries:
http://lz4.overpass-api.de/api/convert?data=nw%5Bshop%5D(47.209%2C-1.552%2C47.215%2C-1.544)%3B%0A&target=mapql
