### ISSUE TITLE
Nodes without coordinates

### ISSUE THREAD

**Issue by willemarcel** [drolbr/Overpass-API#536]
When executing [this request](http://overpass.hotosm.org/api/interpreter?data=[out:xml][adiff:%222019-08-05T15:05:39Z,%22,%222019-08-05T15:05:41Z%22];(node(bbox)(changed);way(bbox)(changed);relation(bbox)(changed););out%20meta%20geom(bbox);&bbox=-40.8280364,-21.0239989,-40.8092285,-21.0090232), it returns some nodes without coordinates, for example:

```
<member type="way" ref="140066164" role="outer">
      <nd lat="-21.0217444" lon="-40.8092285"/>
      <nd lat="-21.0099036" lon="-40.8062304"/>
      <nd/>
      <nd/>
      <nd/>
      <nd/>
      <nd/>
      <nd/>
      <nd/>
      <nd/>
      <nd/>
      <nd/>
      <nd/>
      <nd/>
    </member>
```

I tested it in two different overpass instances, and I verified the way in OSM has all the 14 nodes. I see some nodes that are outside of the bbox of the changeset. This is the query that gets the changes introduced by this changeset: https://osmcha.mapbox.com/changesets/73029327/

**Comment by mmd-osm** [comment]
The original Achavi query which is also used in osmcha to my knowledge (https://overpass-api.de/achavi/?changeset=73029327&relations=true) cuts off any nodes outside the bounding box that has been provided by the OSM API (see https://www.openstreetmap.org/changeset/73029327). 

I believe you split the boundary along "Rua Grazielle Zeltzer Gazzani"? To my understanding the bounding box should reflect your changes correctly in this case. The correct bbox calculation has been a topic of repeated discussion, and maybe your expectation differs here.

**Comment by willemarcel** [comment]
@mmd-osm thanks for the comment. I used the bbox of the changeset. It's really caused by the bbox filter.
