### ISSUE TITLE
How can I get Apache/interpreter to use more than 50% CPU?

### ISSUE THREAD

**Issue by JamesChevalier** [drolbr/Overpass-API#540]
I'm running Overpass on an m5.4xlarge EC2 instance (16 vCPUs, 64 GiB RAM) and I'm sending _a lot_ of queries to it for e.g. cities within a region, and streets/nodes within a city.
The server nears 50% CPU usage, but that's as high as it'll go. It starts rejecting requests, as if it was completely saturated.

Do you have any suggestions on how I can achieve 100% CPU usage?

I've tried editing `/etc/apache2/mods-enabled/mpm_event.conf`, and while I do see the number of `interpreter` processes increase, the overall CPU usage remains stuck at 50%.

**Comment by mmd-osm** [comment]
Can you check #447 first?

**Comment by JamesChevalier** [comment]
Ah, right, the _error message_ might be helpful. 🤦‍♂ 

```
<p>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</p>
<p><strong style="color:#FF0000">Error</strong>: runtime error: open64: 0 Success /osm3s_v0.7.55_osm_base Dispatcher_Client::request_read_and_idx::timeout. The server is probably too busy to handle your request. </p>
```

My rate limit appears to be off (the server is currently idle; the most recent batch of work finished overnight). Here's the result of `--my-status`:

```
Connected as: 0
Current time: 2019-09-11T11:54:49Z
Rate limit: 0
Currently running queries (pid, space limit, time limit, start time):
```

And the result of `--status`:

```
Number of not yet opened connections: 0
Number of connected clients: 2
Rate limit: 0
Total available space: 12884901888
Total claimed space: 0
Average claimed space: 536870912
Total available time units: 262144
Total claimed time units: 0
Average claimed time units: 900
Counter of started requests: 115086
Counter of finished requests: 114014
pending	17306
pending	17364
```

The fact that it's reporting 2 connected clients is odd. I'm not currently doing any queries against this server. I restarted apache a few times last night while editing `mpm_event.conf`, so maybe I orphaned some processes. I'm unsure if/how I should restart anything to clear those out.

My server's memory usage is minimal (1.27gb used out of 64gb available).
I'm running _up to_ 800 queries at any given moment (80 sidekiq workers spread across a few other servers, each with 10 threads). I'll include two examples of the queries at the end of this comment.

One thing I wonder about is that I compiled/installed Overpass while the instance was an m5.large, and then I resized the instance to m5.4xlarge after realizing it wasn't going to be able to handle the load. Is it possible that there are compile-time settings, determining how many CPU cores / Memory are available?

You've helped me out with Overpass questions elsewhere - directly and indirectly. I'd like to take the opportunity to thank you! 👍 👍 

---

Cities in a region:

```
[timeout:900][out:json];
area['ISO3166-2'~'^US']['admin_level'='4']['name'='Massachusetts'];
(relation['admin_level'~'8'](area););
out geom;
```

Streets in a city:

```
[timeout:900][out:json];
area(3601181614);
(
way(area)
['name']
['highway']
['highway' !~ 'path']
['highway' !~ 'steps']
['highway' !~ 'motorway']
['highway' !~ 'motorway_link']
['highway' !~ 'raceway']
['highway' !~ 'bridleway']
['highway' !~ 'proposed']
['highway' !~ 'construction']
['highway' !~ 'elevator']
['highway' !~ 'bus_guideway']
['highway' !~ 'footway']
['highway' !~ 'cycleway']
['foot' !~ 'no']
['access' !~ 'private']
['access' !~ 'no'];
);
(._;>;);
out;
```

**Comment by mmd-osm** [comment]
The error message `Dispatcher_Client::request_read_and_idx::timeout.` indicates that the client is sending some request to the dispatcher but the dispatcher won't respond in time.

> I'm running up to 800 queries at any given moment (80 sidekiq workers spread across a few other servers, each with 10 threads)

What would be a typical number of queries a dispatcher instance would have to handle in one second? All all of those 800 queries handled by a single dispatcher instance, or did you set up multiple separate databases?

In release 0.7.55, the dispatcher has some known scalability issues (see #340 for discussion). When using such a large number of concurrent requests, it's not unlikely that you're hitting that limit right now. Unfortunately, this cannot be easily fixed by some parameter setting.

**Comment by JamesChevalier** [comment]
> What would be a typical number of queries a dispatcher instance would have to handle in one second?

This is really tough to answer, because of the client-side infrastructure. It's basically a queue with 800 workers, so it depends on when the workers pick the jobs off the queue.
If I don't put a delay on the initial batch of jobs (one job per region, which queries all the cities in that region, then queues up one job for each city - the city job queries for all the streets/nodes in that city) then that initial batch will be a full "800 queries are happening right now" scenario.
Once things are fully kicked off (full queue load of all cities to process) then it depends on how long each city job takes to complete, which is dependent on Overpass query time & street/node record creation time.
Apache has a `/server-status` endpoint that provides some load-related output. I've included that output at the bottom of this comment.

> All all of those 800 queries handled by a single dispatcher instance, or did you set up multiple separate databases?

I only have the one Overpas server running, based on the installation instructions. So I think this means that I've got one dispatcher. Just in case, I'll describe my start-up process... I went through the entire installation process, then I had to shut things down in order to resize the EC2 instance & finally bring everything back online. These are the commands that I ran after starting the server back up:

- `rm -f db/osm3s_v0.7.55_osm_base`
- `nohup bin/dispatcher --osm-base --meta --db-dir="db/" >> osm_base.out &`
- `chmod 666 "db/osm3s_v0.7.55_osm_base"`
- `nohup bin/fetch_osc.sh `cat db/replicate_id` "[http://planet.openstreetmap.org/replication/minute/](http://planet.openstreetmap.org/replication/minute/)" "diffs/" >> fetch_osc.out &`
- `nohup bin/apply_osc_to_db.sh "diffs/" `cat db/replicate_id` --meta=yes >> apply_osc_to_db.out &`
- `rm -f db/osm3s_v0.7.54_areas`
- `nohup bin/dispatcher --areas --db-dir="db/" >> areas.out &`

---

<dl><dt>Server Version: Apache/2.4.29 (Ubuntu)</dt>
<dt>Server MPM: event</dt>
<dt>Server Built: 2019-08-26T13:41:23
</dt></dl><hr /><dl>
<dt>Current Time: Wednesday, 11-Sep-2019 20:09:57 UTC</dt>
<dt>Restart Time: Wednesday, 11-Sep-2019 14:31:55 UTC</dt>
<dt>Parent Server Config. Generation: 1</dt>
<dt>Parent Server MPM Generation: 0</dt>
<dt>Server uptime:  5 hours 38 minutes 2 seconds</dt>
<dt>Server load: 7.48 7.37 6.97</dt>
<dt>Total accesses: 43744 - Total Traffic: 4.4 GB</dt>
<dt>CPU Usage: u3.46 s6.42 cu0 cs0 - .0487% CPU load</dt>
<dt>2.16 requests/sec - 226.7 kB/second - 105.1 kB/request</dt>
<dt>497 requests currently being processed, 53 idle workers</dt>
</dl>

<table rules="all" cellpadding="1%">
<tr><th rowspan="2">Slot</th><th rowspan="2">PID</th><th rowspan="2">Stopping</th><th colspan="2">Connections</th>
<th colspan="2">Threads</th><th colspan="3">Async connections</th></tr>
<tr><th>total</th><th>accepting</th><th>busy</th><th>idle</th><th>writing</th><th>keep-alive</th><th>closing</th></tr>
<tr><td>0</td><td>8260</td><td>no</td><td>31</td><td>yes</td><td>16</td><td>9</td><td>0</td><td>0</td><td>15</td></tr>
<tr><td>1</td><td>13689</td><td>no</td><td>48</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>24</td></tr>
<tr><td>2</td><td>4577</td><td>no</td><td>26</td><td>yes</td><td>11</td><td>14</td><td>0</td><td>0</td><td>7</td></tr>
<tr><td>3</td><td>17362</td><td>no</td><td>39</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>15</td></tr>
<tr><td>4</td><td>8331</td><td>no</td><td>38</td><td>yes</td><td>19</td><td>6</td><td>0</td><td>0</td><td>19</td></tr>
<tr><td>5</td><td>8445</td><td>no</td><td>37</td><td>yes</td><td>23</td><td>2</td><td>0</td><td>0</td><td>15</td></tr>
<tr><td>6</td><td>21498</td><td>no</td><td>0</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>7</td><td>8605</td><td>no</td><td>43</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>19</td></tr>
<tr><td>8</td><td>14828</td><td>no</td><td>39</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>15</td></tr>
<tr><td>10</td><td>15129</td><td>no</td><td>45</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>21</td></tr>
<tr><td>11</td><td>8830</td><td>no</td><td>44</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>20</td></tr>
<tr><td>12</td><td>8938</td><td>no</td><td>40</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>16</td></tr>
<tr><td>14</td><td>9131</td><td>no</td><td>43</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>19</td></tr>
<tr><td>16</td><td>9254</td><td>no</td><td>39</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>16</td></tr>
<tr><td>17</td><td>14702</td><td>no</td><td>45</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>21</td></tr>
<tr><td>18</td><td>14900</td><td>no</td><td>42</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>19</td></tr>
<tr><td>19</td><td>3845</td><td>no</td><td>8</td><td>yes</td><td>3</td><td>22</td><td>0</td><td>0</td><td>3</td></tr>
<tr><td>20</td><td>13752</td><td>no</td><td>45</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>21</td></tr>
<tr><td>21</td><td>15952</td><td>no</td><td>42</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>17</td></tr>
<tr><td>23</td><td>15216</td><td>no</td><td>44</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>20</td></tr>
<tr><td>24</td><td>15296</td><td>no</td><td>44</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>20</td></tr>
<tr><td>26</td><td>15348</td><td>no</td><td>45</td><td>yes</td><td>25</td><td>0</td><td>0</td><td>0</td><td>21</td></tr>
<tr><td>Sum</td><td>22</td><td>0</td><td>827</td><td>&nbsp;</td><td>497</td><td>53</td><td>0</td><td>0</td><td>363</td></tr>
</table>
<pre>WWW_WW_WWW_WWW__W__W_WW_WWWWWWWWWWWWWWWWWWWWWWWWWWW_WW___WW___W_
WWW______WWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWW_WWW_WWW__WW_WWWWWWW
W_WWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.........................WWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWW.........................WWWWWWWWWWWWWWWWWWWWWWWWW.........
................WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWW______W______________W_W_WWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.........................W
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW...............
..........WWWWWWWWWWWWWWWWWWWWWWWWW.............................
................................................................
................................................................
................................................................
................................................................
........................................</pre>
<p>Scoreboard Key:<br />
"<b><code>_</code></b>" Waiting for Connection,
"<b><code>S</code></b>" Starting up,
"<b><code>R</code></b>" Reading Request,<br />
"<b><code>W</code></b>" Sending Reply,
"<b><code>K</code></b>" Keepalive (read),
"<b><code>D</code></b>" DNS Lookup,<br />
"<b><code>C</code></b>" Closing connection,
"<b><code>L</code></b>" Logging,
"<b><code>G</code></b>" Gracefully finishing,<br />
"<b><code>I</code></b>" Idle cleanup of worker,
"<b><code>.</code></b>" Open slot with no current process<br />
</p>

Also, this command:

```
grep "11/Sep/2019:20" /var/log/apache2/access.log | cut -d[ -f2 | cut -d] -f1 | awk -F: '{print $2":"$3}' | sort -nk1 -nk2 | uniq -c | awk '{ if ($1 > 10) print $0}'
```

Produced this response (requests per minute, I believe):

```
582 20:00
1190 20:01
1247 20:02
1198 20:03
1041 20:04
1198 20:05
1166 20:06
1117 20:07
```

**Comment by JamesChevalier** [comment]
Closing this issue, as it's (if I'm understanding correctly) a concurrent-connection limitation in the dispatcher.

While it would be great to have a dispatcher that could reach the scale I was trying to operate at, it didn't really hold me back from completing an enormous amount of work (extracting 167k cities / 11 million streets / 240 million nodes out of 978 regions) in a fairly short amount of time (couple days).
Sidekiq's [automatic retry system](https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry) made it so that I didn't really have to care about failed queries. Next time I have to do this much work, I'll see how your `osm3s_query` suggestion fits into my system. 👍 

Thanks for all your help!
