### ISSUE TITLE
Specific user uses a lot of memory

### ISSUE THREAD

**Issue by taylorsmock** [drolbr/Overpass-API#541]
For whatever reason, overpass uses a lot of memory with the following query (this user _specifically_):

```
[out:xml][maxsize:1973741824][timeout:180];
(
  // uid for Владимир К is 2853561
  node(uid:2853561)(newer:"{{date:1 days}}");
  way(uid:2853561)(newer:"{{date:1 days}}");
  relation(uid:2853561)(newer:"{{date:1 days}}");
);
(._;>;);
out meta;
```

It usually ends up saying something like "runtime error: Query run out of memory using about 4788 MB of RAM". Which is odd, since the `maxsize` parameter should be limiting it to ~1883 MiB.

Note: at the time I ran the query, the specific user only had one (small) changeset in the past 5 days (specifically https://www.openstreetmap.org/changeset/74515486 ). If I use Russian states as a search area, it works as well, and it shouldn't be returning any different information.

**Comment by drolbr** [comment]
Fixed in ab41fea6781a40477910818cb6314d7325274501
The fix will get available on the public instances with the next release.

**Comment by mmd-osm** [comment]
Although the peak memory consumption is now down to 3.9 GB for the following query, I'm getting incorrect results where neither the uid nor the newer timestamp are correct.  Out of 2246 objects returned by the query, 1864 have both an incorrect user id and a timestamp before 2019-12-29.

```
 <node id="299238229" lat="51.5787156" lon="46.1000194" version="3" timestamp="2018-05-25T17:47:26Z" changeset="59277766" uid="7774118" user="RiverBearings"/>
```

Test database: /var/www/clone/2019-12-31/

``` C
[out:xml][maxsize:8973741824][timeout:7200];
(
  // uid for Владимир К is 2853561
  nwr(uid:2853561)(newer:"2019-12-29T00:00:00Z");
);
(._;>;);
out meta;
``` C

**Comment by drolbr** [comment]
Please use

    [out:xml][maxsize:1973741824][timeout:7200];
    (
      // uid for Владимир К is 2853561
      nwr(uid:2853561)(newer:"2019-12-29T00:00:00Z");
    );
    out meta;

That the recurse-down adds extra elements is expected behaviour.

**Comment by mmd-osm** [comment]
Ah, yes, you're right, I completely missed the recurse down towards the end. Sorry for the noise.
