### ISSUE TITLE
Meta-relations(relations containing only relations) not returned

### ISSUE THREAD

**Issue by james2432** [drolbr/Overpass-API#543]
I've also noticed when trying to download data:

relation["type"="route_master"]
Returns nothing: http://overpass-turbo.eu/s/MPB
Where as there are a lot of sub relations in this area that the route_master encompasses: http://overpass-turbo.eu/s/MPE

It's almost as if recursion isn't a thing for determining the location of meta-relations

**Comment by mmd-osm** [comment]
This is expected, and by design. Master relations don’t have any node/way geometry on their own, hence you cannot query them by bounding box. There’s a related question on the Help OSM site with an alternative approach.
