### ISSUE TITLE
Area not returning all objects if their type is listed separately.

### ISSUE THREAD

**Issue by DaveF63** [drolbr/Overpass-API#544]
Hi

Why is this not returning the ways (there are no relations in this example):

Returns 220 0bjects

```
area(3600058437); // Wales
(
 node["ref:crs"](area);
 way["ref:crs"](area);
);
out center;
```
But this does (224):

```
area(3600058437); // Wales
nwr["ref:crs"](area);
out center;
```

I was using this as an example:
https://dev.overpass-api.de/blog/some_tagging_in_pt.html#bus_yn

**Comment by mmd-osm** [comment]
See https://help.openstreetmap.org/questions/20531/overpass-ql-nodes-and-ways-in-area

**Comment by mmd-osm** [comment]
@DaveF63 : can you please close this issue, assuming you have no further questions? Thanks.
