### ISSUE TITLE
Memory leak in Set_With_Context

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#545]
I believe there's a memory leak in Set_With_Context, as none of the geometry stores are deleted in the destructor. This issue becomes quite obvious in a for loop:

![img2](https://user-images.githubusercontent.com/5842757/69093114-19838d00-0a4e-11ea-9bd0-8ad92b2ffaea.png)

![img1](https://user-images.githubusercontent.com/5842757/69093108-17213300-0a4e-11ea-886c-1905539ff007.png)

Query:

```
[out:csv(num,key,len)];
area[name="Saarland"];
way[highway=residential][name](area);
for (t["name"])
(
  make stat num=count(ways),key=_.val,len=sum(length());
  out; 
);
```

Suggested fix would be: https://github.com/mmd-osm/Overpass-API/commit/0608d404a7cf218dccba7d76b51493f15d1a2873

**Comment by drolbr** [comment]
Thank you for the notification.
Fixed in 4abef313da9a4de1fe0b2f8fcd1ffef2ec53ef8a
