### ISSUE TITLE
Potential memory leak in Query_Statement w/ global bounding box

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#547]
I'm suspecting a memory leak in Query_Statement when using a global bounding box.

It seems that parts of `std::vector< Query_Constraint* > constraints` ,   `std::vector< Statement* > substatements` and   `Bbox_Query_Statement* global_bbox_statement` are not being cleaned up in a destructor.

Query_Statement constructor uses the following code, causing those dangling instances:

```
  if (global_settings.get_global_bbox_limitation().valid())
  {
    global_bbox_statement = new Bbox_Query_Statement(global_settings.get_global_bbox_limitation());
    constraints.push_back(global_bbox_statement->get_query_constraint());
  }
```

As a consequence, `Bbox_Filter` class instances with their two range sets for 31/32bit indices will not be removed anymore and contribute to the mem leak.

Query_Statement destructor probably lacks a `delete global_bbox_statement; `here.

Triggers memory leak:

```
[timeout:3600][bbox:53.5, 9.9, 53.6, 10.0];

way[building][!location][layer ~ '^-[0-9]+$'] -> .w1;
rel[building][!location][layer ~ '^-[0-9]+$'] -> .r1;
(.w1; .r1;);
out meta geom;
```

Ok:

```
[timeout:3600];

way[building][!location][layer ~ '^-[0-9]+$'](53.5, 9.9, 53.6, 10.0) -> .w1;
rel[building][!location][layer ~ '^-[0-9]+$'](53.5, 9.9, 53.6, 10.0) -> .r1;
(.w1; .r1;);
out meta geom
```
### tcmalloc / pprof leak analysis:

![mem_leak](https://user-images.githubusercontent.com/5842757/70182083-72585400-16e3-11ea-8de8-f02086f42be2.png)

**Comment by drolbr** [comment]
Thank you for finding the leak.
Fixed in c9a8d2e7400f33a0a5d05205428b15ed3f064989
