### ISSUE TITLE
Regression in nw, wr, and nr as query types

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#550]
Creating an issue for better visibility and tracking:

https://github.com/drolbr/Overpass-API/commit/6f83224bae8aef3cbd62dabe3ac10cce5090efb9#diff-764d539ba86ce43fadd48695d80d27d8R47

      virtual bool can_standalone(const std::string& type)
      { return type == "node" || type == "way" || type == "relation"; }

--> "area" is missing here, it would trigger runtime errors for queries like: `area(3601116270); out;`

**Comment by drolbr** [comment]
Fixed in e0bcb7a4cdcff9a5b8fdfb53bab58ca790f14a0d
