### ISSUE TITLE
Difference statement triggers segfault

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#551]
The following statement triggers a segfault:

```
(._; - ._;);
```

By the way, the error was discovered using a homegrown query generator as fuzzing tool. Haskell FTW.

**Comment by drolbr** [comment]
Fixed in 86b90d3aae49dd083ebb590d588cc4562b918a8a

BTW: A homegrown fuzzing generator for QL sounds really cool. Thank you.
