### ISSUE TITLE
Increase quota for umap

### ISSUE THREAD

**Issue by pangoSE** [drolbr/Overpass-API#555]
Hi. I just created https://umap.openstreetmap.fr/en/map/huts-and-shelters-in-the-world_410556 and find that quite often when I pan the map I get "error: problem response" supposedly because of the quota imposed by overpass-api.de.
I understand that caching requests on umap would be the best solution but that does not currently work, see https://github.com/umap-project/umap/commit/81f6b429bc91321e33ad645fe94531604fbd6313 
WDYT?

**Comment by mmd-osm** [comment]
You can try another Overpass instance for the time being. See the overpass page on the osm wiki for alternatives.

**Comment by mmd-osm** [comment]
Maybe you should also spend some time optimizing your queries, so that caching in umap might work. As an example, you might want to definitely familiarize yourself with `nwr`, which avoids repeating node, way, relation with the same arguments over and over. 


```
[out:json][timeout:325];
( nwr["access"!="private"]["tourism"~"^(alpine_hut|wilderness_hut)$"];
  nwr["access"!="private"]["amenity"="shelter"]["shelter_type"!="public_transport"][!"public_transport"]["leisure"!="bird_hide"];
);
out center;
```

**Comment by pangoSE** [comment]
Thanks for the suggestions. I'll improve the query and try to split it up in multiple layers also.
