### ISSUE TITLE
unexpected difference in results of >;

### ISSUE THREAD

**Issue by GerdP** [drolbr/Overpass-API#556]
see http://overpass-turbo.eu/s/Q9i
This query 
<source>rel(id:69202);>;out meta;</source><p>
returns the members AND the relation itself.
This query returns only the nodes, not the way itself:
<source>way(id:53799684);>;out meta;</source><p>
This is a bit confusing. According to the API docu I would say that the first result is wrong.

**Comment by mmd-osm** [comment]
I can’t reproduce this, the rel query doesn’t return the relation here.

**Comment by GerdP** [comment]
Arg, sorry, I replaced >>; by >;

**Comment by GerdP** [comment]
Updated link:
http://overpass-turbo.eu/s/Q9o

**Comment by mmd-osm** [comment]
Ok, so the [documentation](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Recurse_down_relations_.28.3E.3E.29) says: _Precisely, the recurse down relations standalone query returns the transitive and reflexive closure of **membership**._ 

It is implemented here: 
* https://github.com/drolbr/Overpass-API/blob/master/src/overpass_api/statements/recurse.cc#L2570-L2581 and 
* https://github.com/drolbr/Overpass-API/blob/master/src/overpass_api/statements/recurse.cc#L899-L916

In particular, `relations_loop` will always include the original (source) relation.

I think most people use `>>;` along with a union statement, in which case the difference won't matter:

```
(rel(5962786);>>;);out meta;
```

I tend to agree that the word "membership" in the documentation above might be a bit misleading, and should rather be "relation" to describe what the statement is currently doing. Maybe Roland can explain the reasoning behind this.

**Comment by drolbr** [comment]
Opposed to ways and nodes, relations can refer to each other. In particular, it is possible that relation A has relation B as a member and at the same time B has A as a member. Another, more mundane case is that somebody comes along with `(rel(A);rel(B););>>;` where A has B as a member. Some users might expect B to be in the result set because it is a member of A, other users might expect B to be absent because it is contained in the input set.

The Overpass API must behave even in these cases in a sane way. The closure is a robust and well-understood operation. Nonetheless, I happy for the question, and I'm going to clarify the documentation.

**Comment by GerdP** [comment]
BTW: similar problem with <<;
Try node(21389333);<;  and node(21389333);<<;
My understanding of the documentation is that both should return the same result, but <<; returns more relations

**Comment by mmd-osm** [comment]
`<<;` calculates the transitive clousre, it keeps on iterating over object references:

(1) node 21389333 referenced by way 4191506
(2) way 4191506 referenced by rel 1080375 
(3) rel 1080375 referenced by rel 69202
(4) rel 69202 referenced by rel 7159297

This is exactly what you get in the result. 

`<;` on the other hand doesn't resolve relations, so you would stop after step 2.

**Comment by GerdP** [comment]
node(21389333);  is the input set.
The docu for << says 
"The recurse up relations standalone query has a similar syntax to the recurse up query and differs only in two aspects:

    It is written as a double less than.
    It also recursively returns all relations that have a member relation appearing in the **input** set.
There is no relation in the input set.
What I see is that it also recursively returns all relations that have a member relation appearing in the **result** set produced by <;

**Comment by mmd-osm** [comment]
You need to read this section to the end where it says:

_Precisely, the recurse up relations standalone query returns the transitive and reflexive closure of membership backwards._

**Comment by GerdP** [comment]
For me this means: The easy to understand sentence is wrong. "transitive and reflexive closure of membership backwards" sounds very sophistic but means nothing to me. Probably those words were not used in TH Dortmund when I studied computer sience (before 1995) ;)

**Comment by drolbr** [comment]
Thank you for the feedback on the documention. I have updated the documentation to make the intended semantics clearer.

FWIW: The notions "Abschluss", "transitiv", "reflexiv" (German translations of "closure", "transitive" and "reflexive") have for sure been treated in the first two weeks of "Lineare Algebra I", given the excellent teaching at the TU (TH in former times).

**Comment by GerdP** [comment]
Oops, an important typo on my side. It was FH Dortmund. So let's say:  Maybe I should've learned it but theory was not that important in FH.

**Comment by GerdP** [comment]
I think the newer version is much clearer. Thanks!
