### ISSUE TITLE
overpass turbo hangs while rendering

### ISSUE THREAD

**Issue by GerdP** [drolbr/Overpass-API#558]
Execute this simple query:
https://overpass-turbo.eu/s/Qd0
Data is returned but popup stays in phase "rendering geoJSON" very long, maybe forever?

**Comment by mmd-osm** [comment]
The query doesn't cause a hang in overpass turbo here. However, it fails on z.overpass-api.de.

**Comment by GerdP** [comment]
I can still reproduce it. Can I anything else to provide information?

________________________________________
Von: mmd <notifications@github.com>
Gesendet: Mittwoch, 29. Januar 2020 12:55
An: drolbr/Overpass-API
Cc: GerdP; Author
Betreff: Re: [drolbr/Overpass-API] overpass turbo hangs while rendering (#558)

The query doesn't cause a hang in overpass turbo here. However, it fails on z.overpass-api.de.

**Comment by mmd-osm** [comment]
Can you check your settings in overpass turbo:

Settings --> Map --> Don't display small features as POIs.

If you set this flag to "X", the UI won't hang anymore.

That's really an issue you need to report on https://github.com/tyrasd/overpass-turbo/issues

**Comment by GerdP** [comment]
I can confim that the change of this setting solves the problem.
