### ISSUE TITLE
Collecting elements in foreach loop

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#560]
---

I'm also testing a more generic approach based on implicit Skeleton sharing

---

A frequently used pattern inside a `foreach` loops is to add new elements to an existing resultset. Eventually, the resultset will then be returned outside of the foreach loop, at the end of the query.

Unfortunately, this is surprisingly expensive today, as it involves quite a number of object allocations and copying objects. I would assume that repeated copying of the result vector inside the loop would make this an O(n²) operation. Relevant In the following methods:

- rman.move_outward
- rman.union_inward
- rman.move_all_inward_except

In Item_Statement::execute, I found high runtimes while clearing and destructing the Set (probably  related to transfer_output(rman, into)), also Item_Statement::execute(Resource_Manager&) (item.cc:208) triggers copying of elements.

![Bildschirmfoto von 2020-02-09 14-11-00](https://user-images.githubusercontent.com/5842757/74102673-06142980-4b46-11ea-9495-9c8f085620d9.png)

union_inward seems to be expensive due to copying vectors inside indexed_set_union. Also, the logic around _result_has_grown_ is not needed here, Union_Statement::execute does not evaluate the return code of this value.

![Bildschirmfoto von 2020-02-09 14-08-23](https://user-images.githubusercontent.com/5842757/74102623-af0e5480-4b45-11ea-86d5-2081b8b21119.png)

I wonder if there might be some better, more efficient way to support this rather frequent use case of adding elements to a named set. Ideally, we should keep today's syntax as it is in so widespread usage.

```
way[building](50.149186398818784,6.886367797851562,50.27683450836172,7.092189788818359);

foreach {

  (._; .result;)->.result;
}

.result out;
```

Leaving out the union/item query inside the loop is about 3-4 times faster (although it is not exactly comparable, as it doesn't sort the results).

```
way[building](50.149186398818784,6.886367797851562,50.27683450836172,7.092189788818359);

foreach {

  out;
}
```

**Comment by mmd-osm** [comment]
So this sharing approach seems to workl:

-  0.7.56: https://overpass-turbo.eu/s/Srq - Runtime: > 60s
-  0.7.59_mmd: https://overpass-turbo.eu/s/Sro - Runtime: 4s


Relevant commits: https://github.com/mmd-osm/Overpass-API/commit/506cda4c42b51763864267f62618da016d5699c9, and https://github.com/mmd-osm/Overpass-API/commit/7f72ee2c451a92ff0c50833ce51f8d9d7b7db593

This may look a bit complicated at first. The documentation on https://doc.qt.io/qt-5/qshareddatapointer.html and https://doc.qt.io/qt-5/implicit-sharing.html explains the overall concept in much more detail.

**Comment by drolbr** [comment]
Marked as enhancement for the moment. I'm still not happy with the way the execution stack works at the moment, and considering the document may lead to a better overall solution.

**Comment by mmd-osm** [comment]
> considering the document may lead to a better overall solution

I'm not exactly sure I'm following you. What is this document you're referring to here?

**Comment by mmd-osm** [comment]
Implemented in https://github.com/mmd-osm/Overpass-API, closing here.
