### ISSUE TITLE
Some more memory leaks

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#562]
Missing destructor in Value_Eval_Task to clean up `Eval_Task* rhs`: https://github.com/mmd-osm/Overpass-API/commit/d984b3bb1c35cad0c9a85b91fd1f5588f258e351

While analyzing memory leaks via `-fsanitize=leak`, I've noticed that a few unit tests also leak memory. This is a bit unfortunate as this gets in the way of finding memory leaks in the productive code. I think those memory leaks should be fixed as well:

https://github.com/mmd-osm/Overpass-API/commit/1cb690ae5c94a7038f73c4dc4b6994934896f7d2
https://github.com/mmd-osm/Overpass-API/commit/2367a8b3284a2fa343c5107ab215ad48867f8110
https://github.com/mmd-osm/Overpass-API/commit/abbe82d71cd15ab6e2812c0cbfe4a95fcdb0c812
https://github.com/mmd-osm/Overpass-API/commit/1cf79295863ab79aebdb415928de9f30a2d4ed43

**Comment by drolbr** [comment]
Fiexd in afd218913704dc71a056d8d5df5e024816d51835
