### ISSUE TITLE
Missing Info In Query

### ISSUE THREAD

**Issue by Tahfimul** [drolbr/Overpass-API#570]
I queried the way ref id: `609350841` using the Overpass-API and it was missing the tags listed here: https://www.openstreetmap.org/way/608139670 

The query returned the following:
`{'version': 0.6, 'generator': 'Overpass API 0.7.56.3 eb200aeb', 'osm3s': {'timestamp_osm_base': '2020-04-23T18:03:02Z', 'copyright': 'The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.'}, 'elements': [{'type': 'way', 'id': 609350841, 'bounds': {'minlat': 51.5084824, 'minlon': -0.1047334, 'maxlat': 51.5098744, 'maxlon': -0.1040922}, 'nodes': [2079673539, 2079674369, 1376776600, 7137569410, 1376776562, 1376776560, 1376776602, 5771940409, 1376776609, 1376776597, 1376776558, 1376776575, 1376776578, 1376776603, 1376776569, 4077627054, 4421008566, 4107646653, 4077627052, 1376776608, 1376776582, 3406832179, 3406832180, 3408487391, 1376776606, 2079673488, 1376776592, 2079673565, 2079673623, 2131782095, 1376776584, 2079673789, 1376776559, 2079673849, 2079674204, 2079674231, 1376776567, 2079673548], 'geometry': [{'lat': 51.5098544, 'lon': -0.1041573}, {'lat': 51.5096321, 'lon': -0.1041604}, {'lat': 51.5096275, 'lon': -0.1041049}, {'lat': 51.5096103, 'lon': -0.1040922}, {'lat': 51.5095928, 'lon': -0.1041029}, {'lat': 51.5095877, 'lon': -0.104165}, {'lat': 51.5090898, 'lon': -0.1041891}, {'lat': 51.5090879, 'lon': -0.1041249}, {'lat': 51.5090689, 'lon': -0.1041117}, {'lat': 51.509047, 'lon': -0.1041252}, {'lat': 51.5090467, 'lon': -0.1041894}, {'lat': 51.5086294, 'lon': -0.1041867}, {'lat': 51.5085834, 'lon': -0.1041411}, {'lat': 51.5084946, 'lon': -0.1041529}, {'lat': 51.5084849, 'lon': -0.1042082}, {'lat': 51.5084856, 'lon': -0.104223}, {'lat': 51.5084824, 'lon': -0.1044025}, {'lat': 51.508488, 'lon': -0.1045922}, {'lat': 51.5084833, 'lon': -0.1046359}, {'lat': 51.5084945, 'lon': -0.1046628}, {'lat': 51.5085376, 'lon': -0.1046782}, {'lat': 51.5085624, 'lon': -0.1047255}, {'lat': 51.5086073, 'lon': -0.1047152}, {'lat': 51.5086219, 'lon': -0.1046961}, {'lat': 51.508621, 'lon': -0.1046776}, {'lat': 51.5090643, 'lon': -0.1046772}, {'lat': 51.5090697, 'lon': -0.1047108}, {'lat': 51.5090743, 'lon': -0.1047311}, {'lat': 51.5090909, 'lon': -0.1047334}, {'lat': 51.5091025, 'lon': -0.1047147}, {'lat': 51.5091035, 'lon': -0.1046722}, {'lat': 51.5095987, 'lon': -0.1046586}, {'lat': 51.5095981, 'lon': -0.1047052}, {'lat': 51.5096095, 'lon': -0.1047283}, {'lat': 51.5096253, 'lon': -0.1047275}, {'lat': 51.5096342, 'lon': -0.1047039}, {'lat': 51.5096358, 'lon': -0.104656}, {'lat': 51.5098744, 'lon': -0.1046482}]}]}`

I hope my suggestion helps improve the system. Thank you!

**Comment by mmd-osm** [comment]
Can you please post the exact query you where executing, not just a verbal description.

**Comment by Tahfimul** [comment]
> Can you please post the exact query you where executing, not just a verbal description.

This was my exact query: http://overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%3Bway%28609350841%29%3Bout+geom%3B

> Also, 608139670 and 609350841 are two different way ids. Please decide which one you want to use in your query. https://www.openstreetmap.org/way/609350841 does not have any tags.

Yes I intended to provide https://www.openstreetmap.org/way/609350841 which does not have tags. I apologize for my mistake. If someone can aggregate the tag data for the way in the link as well as update the Overpass API, I would appreciate it. 

I hope I was able to improve the wonderful OSM project. Thank you!

**Comment by mmd-osm** [comment]
Your link is ok, you just need to put in a way id, that has tags: http://overpass-api.de/api/interpreter?data=[out%3Ajson]%3Bway(608139670)%3Bout+geom%3B

Can you close the issue if there are no further questions? Thank you.
