### ISSUE TITLE
Not able to parse xml. getting this error

### ISSUE THREAD

**Issue by Ashishsingh009** [drolbr/Overpass-API#576]
org.simpleframework.xml.core.AttributeException: Attribute 'version' does not have a match in class
 com.righthear.models.JSONOsmSet at line -1

**Comment by mmd-osm** [comment]
Please contact the vendor of your app "com.righthear" for support.

**Comment by Ashishsingh009** [comment]
By converting the response into inputStream, I'm able to parse this.
