### ISSUE TITLE
HTTP status for timeouts

### ISSUE THREAD

**Issue by repomaa** [drolbr/Overpass-API#577]
Timeouted queries misleadingly return 200 - OK as a HTTP status. IMO this should be 504 or maybe 413 to indicate a client error (since the client can amp up the timeout).

**Comment by mmd-osm** [comment]
That’s a duplicate of #94 and by design. Please close the issue if this answers your question.

**Comment by matkoniecz** [comment]
Is it safe to assume that `remark` will be present in 200 code responses iff error happened?
