### ISSUE TITLE
HTTPS certificate has expired for overpass-api.de

### ISSUE THREAD

**Issue by simon04** [drolbr/Overpass-API#579]
Accessing https://overpass-api.de/api/interpreter fails with `SEC_ERROR_EXPIRED_CERTIFICATE
`. The certificate has expired:

![2020-06-14-224953](https://user-images.githubusercontent.com/782446/84603797-85698f00-ae91-11ea-9880-77f1a11420e6.png)

**Comment by mmd-osm** [comment]
I think the automated renewal process has already updated the certificate in the meantime.

**Comment by matkoniecz** [comment]
Yes, it is working again.

**Comment by simon04** [comment]
@JOSM bug report: https://josm.openstreetmap.de/ticket/19386

Thanks for renewing!

**Comment by pedrocamargo** [comment]
It seems like that the certificate has expired again...

**Comment by pedrocamargo** [comment]
Sorry...
