### ISSUE TITLE
Support regex expression also for keys

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#59]
Conditional restrictions and similar constructs create a plethora of different tagging alternatives which are quite difficult to catch via normal Overpass API calls.

Example: http://overpass-turbo.eu/s/1jl

I'd appreciate a way to specifiy all these alternatives via a compact regex expression instead of an ever growing (and never really complete) list.

Is that technically feasible with today's data model?

Best,
mmd

**Comment by richlv** [comment]
> The second restriction is that negation doesn't work at the moment, or searching for the key only or searching for a particular value. I plan to add negation quite soon, but the other features are likely to be postponed.

Pardon a bit of necroposting. Did negation go in at some point?
Attempting to use it currently fails with "regular expressions on keys cannot be combined with negation".

**Comment by mmd-osm** [comment]
#589 is about `way[!~"."~"."]`, whereas you're probably looking for `way[~"."!~"."]`. Both variants aren't available in this repo as of today.

By the way, I've reactivated the overpass link mentioned in #589, where you can try out both variants.
