### ISSUE TITLE
Is it possible to make requests against the Dev sandbox of OSM rather than the production version?

### ISSUE THREAD

**Issue by kmpoppe** [drolbr/Overpass-API#593]
As per subject.

Asking because it would be great for application development not the check against the live data because you would be able to create your own testing objects rather than creating changes in the live data that create Changesets that need to be rolled back.

Thanks :)

Kai

**Comment by mmd-osm** [comment]
No, that’s not possible at the time due to the lack of minutely diffs on the dev instance. Maybe this will change when moving to the new replication in the next months.

**Comment by kmpoppe** [comment]
> when moving to the new replication in the next months.

? What's happening? OSM or Overpass wise?

> So the only option at this time is to install it all on your own, which is quite a bit of work to get going.

Unfortunately, that's something I don't have the time for at the moment I guess :/

**Comment by mmd-osm** [comment]
Replication on osm servers will transition from using osmosis to a new tool called osmdbt. Reason being that the old tool will no longer work with newer PostgreSQL versions.

**Comment by mmd-osm** [comment]
By the way, you would need to bring up the minutely diff topic over at https://github.com/openstreetmap/operations/issues
Right now, this issue isn't actionable due to a lack of the respective upstream data provider.

**Comment by mmd-osm** [comment]
@kmpoppe : I think there's not much point keeping this issue open, as long as the prerequisites on the osm dev box are not met. If you really need it, you should open an issue on the osm operations issue tracker instead, and reopen this issue later on.

**Comment by NeatNit** [comment]
I am guessing the situation is still the same? Has anyone opened an issue at https://github.com/openstreetmap/operations/issues as suggested? I tried to look for an open/closed issue but couldn't find one.

**Comment by mmd-osm** [comment]
Fun fact: this question is really old, it was asked the first time more than 10 years ago: https://lists.openstreetmap.org/pipermail/dev/2013-October/027439.html

**Comment by NeatNit** [comment]
If you look at https://github.com/openstreetmap/operations/issues/1134, they give the same explanation. It sounds to me like it's doable but requires a some effort by someone with the right access, plus a place to put the files for public access. Not sure why they can't use the same place they put the real planet file, I would think the dev server would be orders of magnitude smaller so it shouldn't make much of a difference in the storage logistics.

The real blocker IMHO is for someone to put in the effort to set it up. And I don't feel like I'm in any position to be asking for them to do that. Maybe if one of the Overpass operators asks, it would be considered, but right now it's just a random user asking.

**Comment by mmd-osm** [comment]
Mixing prod and non-prod environments is usually a no go, so it doesn’t make a whole lot of sense to publish the dev data on production systems.

In the end you would need to duplicate the whole stack like in https://github.com/developmentseed/osm-seed
