### ISSUE TITLE
Overpass Boundaries  / LEZ

### ISSUE THREAD

**Issue by vshcherb** [drolbr/Overpass-API#595]
This is a feature request that might sound like a question. 

Introduction:
Since OSM-mappers decided to map LEZ  https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dlow_emission_zone as boundaries, it created some difficulties for routing engines. In contrast of maxspeed= tag which is mapped on each road and could be natively processed by routing, LEZ tag is a boundary and requires propagation from boundary to the road segment itself.

Feature request:
Overpass supports boundaries natively and can query objects by certain boundaries and filters. Is it possible to process "data.osm" file containing osm ids (geometry if needed), so Overpass could filter out only ids that belongs to certain boundary. 
In case of this request the question is to detect which OSM ids belong to (boundary=low_emission_zone). OSM ids are provided by batch

**Comment by mmd-osm** [comment]
https://overpass-turbo.eu/s/Y08 would be an example query for one bbox. Note that ways will be included as a whole even if only a small part lies within the low emission zone.

You can also provide a list of way ids and check if those ids are still in the query result, in which case the way would be part of a low emission zone: https://overpass-turbo.eu/s/Y0b

Processing an data.osm would mean, that you run update_database to create an initial version of the database, followed by an area creation run via osm3s_query.

**Comment by vshcherb** [comment]
Thanks, I will need to catch up with features I was not aware of like map_to_area
