### ISSUE TITLE
"Template not found." for ambiguous Permanent ID links

### ISSUE THREAD

**Issue by JesseWeinstein** [drolbr/Overpass-API#597]
e.g. https://overpass-api.de/api/interpreter?data=%5Bout%3Acustom%5D%3Bnode%5Bplace%5D%5Bname%3D%22Bonn%22%5D%3Bout%3B

This was brought up back in 2014, in #69 -- but seems to still be a problem?

**Comment by mmd-osm** [comment]
It only affects one of the two production servers:

https://lz4.overpass-api.de/api/interpreter?data=%5Bout%3Acustom%5D%3Bnode%5Bplace%5D%5Bname%3D%22Bonn%22%5D%3Bout%3B

**Comment by mmd-osm** [comment]
Related issue: the generated HTML page has an issue with mixed content that needs fixing as well:

```
  <script src="http://openlayers.org/api/OpenLayers.js"></script>
  <script src="http://openstreetmap.org/openlayers/OpenStreetMap.js"></script>
```

**Comment by JesseWeinstein** [comment]
Thanks, I've reported this here: https://wiki.openstreetmap.org/wiki/Overpass_API/status

**Comment by mmd-osm** [comment]
Curious why you're using this feature, its usage has basically dropped close to zero over the last years.

**Comment by JesseWeinstein** [comment]
I'm working on improving the Boston T (the transit system) on https://wiki.openstreetmap.org/wiki/MBTA and I wanted to link to the various routes, and found the DisplayRoute template (which uses this).

**Comment by drolbr** [comment]
Thank you for the report. As mentioned, the report on [https://wiki.openstreetmap.org/wiki/Overpass_API/status](https://wiki.openstreetmap.org/wiki/Overpass_API/status) actually did trigger the fix. Should be done now.
