### ISSUE TITLE
The requested URL /blog/ was not found on this server.

### ISSUE THREAD

**Issue by jidanni** [drolbr/Overpass-API#599]
1. Visit http://overpass-api.de/
2. Click Blog

The requested URL /blog/ was not found on this server.

**Comment by mmd-osm** [comment]
Thanks for reporting, the link should indeed point to https://dev.overpass-api.de/blog/

**Comment by drolbr** [comment]
Fixed in the [latest minor version](https://dev.overpass-api.de/releases/osm-3s_v0.7.56.tar.gz)
