### ISSUE TITLE
output as GeoJSON is not working

### ISSUE THREAD

**Issue by michaelmgis** [drolbr/Overpass-API#600]
Following the [documentation](https://dev.overpass-api.de/overpass-doc/en/targets/formats.html), the query url can be extended by "convert item" to get a GeoJSON formatted output.

`[out:json];
( way(51.477,-0.001,51.478,0.001)[name="Blackheath Avenue"];
  node(w);
  relation(51.477,-0.001,51.478,0.001); );
convert item ::=::,::geom=geom(),_osm_type=type();
out geom;`

The output doesn't change. The api provide a JSON formatted output.

**Comment by mmd-osm** [comment]
GeoJSON primarily refers to contents of the geometry fields in the output, not for the document as a whole. You need some post processing on your own to extract those geometry fields as needed.
