### ISSUE TITLE
overpass synchronisation

### ISSUE THREAD

**Issue by sun-geo** [drolbr/Overpass-API#603]
Is there a (current general) overpass synchronisation issue, e.g. this recently deleted object:
https://pewu.github.io/osm-history/#/way/278693169
will be still displayed as result for this query:
https://overpass-turbo.eu/s/ZBD

Edit: seems the sync is off app. 24h see another example:
Added statue: https://pewu.github.io/osm-history/#/node/8070132190
will not shown by this query: https://overpass-turbo.eu/s/ZBG

Thanks for checking

**Comment by mmd-osm** [comment]
Which overpass instance are you using?

**Comment by sun-geo** [comment]
Yes. It's now working as before => closed
