### ISSUE TITLE
как получить служебные данные ПО, reverter, коментарий в .csv?

### ISSUE THREAD

**Issue by Sowa1980** [drolbr/Overpass-API#613]
как получить служебные данные  ПО, reverter, коментарий?

подскажет запрос overpass-turbo.eu, что бы извлечь эти данные из области

<tag k="source" v="Спутниковые снимки: Bing,."/>
<tag k="created_by" v="JOSM/1.5 (17428 ru)"/>
<tag k="created_by" v="reverter_plugin/35248;JOSM/1.5 (15553 ru)"/>
<tag k="comment" v="Смоленская область правки"/>

**Comment by mmd-osm** [comment]
deepl translation:
how to get the service data of the software, reverter, comment in .csv?

answer:

Overpass API does not support changeset metadata, such as changeset comments, software, etc.

Overpass API не поддерживает метаданные changeset, такие как комментарии к changeset, программное обеспечение и т.д.

Duplicate of #189
