### ISSUE TITLE
update_database - huge files consume the whole ram

### ISSUE THREAD

**Issue by officer-merge** [drolbr/Overpass-API#615]
heyho,
importing database files ~40gb crashes my system.
creating the stream to the db-file inside the update_databse.cc solved my problem.

**Comment by drolbr** [comment]
Could you please pose your question again in different words? I have no idea what you mean here.
What source file is imported with which command?

**Comment by officer-merge** [comment]
Forget about it just ran out of ram,
Thx for your question

**Comment by mmd-osm** [comment]
@officer-merge : ok, can you close your issue then? Thanks.

**Comment by officer-merge** [comment]
Yes. Was my mistake.

**Comment by mmd-osm** [comment]
No, what I meant is, press the "Close" button on Github so that the issue gets closed.

**Comment by officer-merge** [comment]
+
