### ISSUE TITLE
emergency=yes tag regarded as a feature instead of an access tag

### ISSUE THREAD

**Issue by Vakonof** [drolbr/Overpass-API#616]
This issue was raised over at the [Nominatim](https://github.com/osm-search/Nominatim/issues/2257) Github, but apparently it is related to the Overpass API.

When querying features on osm.org, Overpass seems to regard features tagged with emergency=yes as emergency features instead of other features that simply have access for emergency services. I request a change to ignore emergency=yes when describing the feature, and instead focus on other main tags such as highway=*.

A good example is the Hoogstraat in Wageningen, which is a pedestrian highway:

With emergency=yes: https://www.openstreetmap.org/way/297710230
![image](https://user-images.githubusercontent.com/11884358/114218430-ad1e6c00-9969-11eb-856c-7e18bf3b5589.png)

Without emergency=yes: https://www.openstreetmap.org/way/6921808
![image](https://user-images.githubusercontent.com/11884358/114218441-b1e32000-9969-11eb-89c1-3adf3b405b8b.png)

Friendly greetings
Thibault

**Comment by mmd-osm** [comment]
The query to determine the respective elements resides on the osm.org repo over at: https://github.com/openstreetmap/openstreetmap-website

This is the wrong repo, really.

**Comment by mmd-osm** [comment]
@Vakonof  can you please close this issue? There’s nothing left to do here. Thanks
