### ISSUE TITLE
cannot be expanded at timestamp 

### ISSUE THREAD

**Issue by matkoniecz** [drolbr/Overpass-API#618]
may be related to #482

maybe it is to be expected, but in such case less confusing message would be nice

```
[date:"2019-05-06T00:00:00Z"];
( nwr[barrier=sliding_gate]; <; >; );
out meta;
```

goes down with

`runtime error: Way 203668783 cannot be expanded at timestamp 2020-09-16T06:35:40Z.`

**Comment by mmd-osm** [comment]
On which server did you see this?

**Comment by matkoniecz** [comment]
Arghh. Sorry for a dumb report.

It is at Kumi overpass that has well known case corrupted database, especially for historic data.
