### ISSUE TITLE
How to use custom osm database

### ISSUE THREAD

**Issue by ubill88** [drolbr/Overpass-API#624]
Hi

I have an experimental osm postgres database and website api set according to
 https://github.com/openstreetmap/openstreetmap-website
Is there any way I can set the overpass-API to read my own osm db?

Thank you very much!

**Comment by mmd-osm** [comment]
Not directly. You need to export your database in OSM XML format, and import that XML file into Overpass API.
Details of doing so are a bit outside of the scope of this issue tracker.

**Comment by ubill88** [comment]
Hi @mmd-osm, 

Thanks for your reply!
Is there a tutorial or document of how to export my postgres database in OSM XML format and import to Overpass API?

**Comment by mmd-osm** [comment]
Please ask over at help.openstreetmap.org or some other community channel, on how to export your database as XML. Once you have the XML file, follow the Overpass API documentation for importing planet files.

**Comment by mmd-osm** [comment]
Also *don’t* use cloning, read the startup section under http://overpass-api.de/no_frills.html and replace references to the planet osm xml file by your own osm XML file.

**Comment by mmd-osm** [comment]
If there are no further questions, please close this issue again. Thanks!

**Comment by ubill88** [comment]
Hi @mmd-osm, thanks, for the reply!

I've asked about how to convert my postgres osm db to osm XML file here:
https://help.openstreetmap.org/questions/80768/overpass-api-on-custom-osm-postgres-database-exported-as-xml
But there's an answer says 

> If you have your own database but it has standard OSM data in it, then of course this makes no sense at all and you would simply feed Overpass OSM data downloaded from any of the usual sources!

I do have an standard OSM postgres db, do I still need to convert it into XML file?
I have my own postgres database with standard OSM data in it. There are some custom keys and values stored in my experimental region so I'm trying to create my own Overpass API.

I'm actually stuck in this part:
According to the installation guide: https://overpass-api.de/no_frills.html
`bin/download_clone.sh --source=https://dev.overpass-api.de/api_drolbr/ --db-dir="db/" --meta=no`
My question is actually here, how to feed my local osm postgres database to Overpass API?
Thank you very much!

**Comment by mmd-osm** [comment]
Please read Frederiks response again very closely, and then my comment about cloning here from a week ago.
