### ISSUE TITLE
Error contacting https://overpass-api.de/api/interpreter

### ISSUE THREAD

**Issue by jidanni** [drolbr/Overpass-API#631]
https://github.com/openstreetmap/openstreetmap-website/issues/3319

**Comment by drolbr** [comment]
This has been a service outage. See [the status page](https://wiki.openstreetmap.org/wiki/Overpass_API/status).

**Comment by mmd-osm** [comment]
I believe this issue was reported due to an overloaded instance. Follow up is here: https://github.com/openstreetmap/operations/issues/569

**Comment by jidanni** [comment]
> I've undone the change on the wiki, as it's outdated and no longer relevant.

Thanks.

P.S., @mnd-osm, how do you get notifications that I commented on this thread? I only see you replied by occasionally checking back.
