### ISSUE TITLE
Missing building in is_in response (closed way)

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#634]
I'm testing //dev.overpass-api.de/api_new_feat/ with the following way:

```
way(300882472)(if:is_closed());
out geom ;
out center ids;
```

-> Way is closed, center point within building:

![crt](https://user-images.githubusercontent.com/5842757/137538814-e7c59dbe-e152-4f22-a65d-fb940d951a4a.png)

When I try the same building using is_in, I get an empty response, although I would expect to see way 300882472 in the response.

```
is_in(51.267507, 7.1633646 );
out geom;
```

```
is_in(51.26752883362288,7.163239493966102);
out geom;
```

Other close-by buildings seem to work ok using the following query:

```
is_in({{center}});
out geom;
```

**Comment by drolbr** [comment]
Thank you for reporting the problem. Fixed in d87bd59fe08c651c499fe7640fc10a2c437a0f1a
