### ISSUE TITLE
Fix compile warning (and possible bug?)

### ISSUE THREAD

**Issue by puffetto** [drolbr/Overpass-API#648]
Hi,

I noticed this compiler warning:

`overpass_api/core/geometry.cc:1371:13: warning: implicit conversion turns floating-point number into bool: 'double' to 'bool' [-Wimplicit-conversion-floating-point-to-bool]
        if (::lon(uint32(value)<<16 > -180.))
        ~~  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`
Shouldn't that line be:

`
if (::lon(uint32(value)<<16) > -180.)
`
?

I am sorry but I do not know the code of overpass well enough to understand and check what the issue causes and then ask a pull.

Cheers,

A.

**Comment by mmd-osm** [comment]
Fixed in  fad5578
