### ISSUE TITLE
Base Layer opacity to small

### ISSUE THREAD

**Issue by martinstingl** [drolbr/Overpass-API#656]
Please set the default opacity of the background map of https://overpass-api.de/achavi/ to something like 0.7 to make it readable.
A even better solution would be to make it adjustable.

Currently I have to add the following code to the Style Editor:
.olTileImage {
  opacity: 0.7 !important;
}

**Comment by mmd-osm** [comment]
Wrong repo, achavi repo is available here: https://github.com/nrenner/achavi
