### ISSUE TITLE
replicate_id is not available at given path expected by clone script

### ISSUE THREAD

**Issue by jenishshah671993** [drolbr/Overpass-API#663]
Hi Team,
I have been trying cloning mechanism and it tries to copy replicate_id file from path EXEC_DIR/db/replicate_id but it actually reside on EXEC_DIR/replicate_id. So it's not getting copied, So when I execute download clone script it does not work as it does get replicate_id to start with.
Could you please help me with him?

below is the structure where replicate_id resides

<img width="712" alt="Screenshot 2022-04-25 at 10 27 13 AM" src="https://user-images.githubusercontent.com/13361410/165023436-8ca9ef00-ef17-4622-a7b2-27c56311bf96.png">

**Comment by mmd-osm** [comment]
It seems your question is somehow related to this Docker image: https://github.com/wiktorn/Overpass-API

Can you check with them first to see if this is caused by any of their scripts?
