### ISSUE TITLE
Endless loop in is_in

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#670]
Based on this report https://forum.openstreetmap.org/viewtopic.php?id=75791, I've found out that the following query results in an endless loop inside "is_in" (Coord_Query_Statement)

```
node(1192389996);
is_in;
```

In gdb, you can see that it's stuck somewhere in here:

```c++
    while (cur_it != input_set->nodes.end() || attic_it != input_set->attic_nodes.end())
    {
      Uint32_Index idx =
          (attic_it == input_set->attic_nodes.end() ||
              (cur_it != input_set->nodes.end() && !(attic_it->first < cur_it->first))) ? cur_it->first : attic_it->first;
      while (!tai.is_end() && tai.get_idx().val() < idx.val())
        tai.next();
      if (tai.is_end())
        continue;
```

**Comment by drolbr** [comment]
Fixed in b33c3320ea54db7aba1576d37dc4fee181237d58

**Comment by mishari** [comment]
Did this bug get reintroduced? The query doesn't seem to work anymore.

**Comment by mmd-osm** [comment]
Areas are currently re-created on one server (z.overpass-api.de) as part of #672, i.e. areas are currently unavailable. Maybe try again in a few hours.
