### ISSUE TITLE
Area - repeated/inconsistent tag key/value pairs

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#672]
This looks like a regression in 0.7.58: in some cases, the same key-value pair is repeated multiple times for the same area:

```C
area["ISO3166-1"="IT"];
out;
```

Sometimes, there are even deviating values for the same key, e.g. "operator" key:

```C
area["ISO3166-1"="AD"];
area[amenity="fuel"](area);
area._(id:3602660789);
out center meta;

```
```xml
  <area id="3602660789">
    <tag k="amenity" v="fuel"/>
    <tag k="amenity" v="fuel"/>
    <tag k="brand" v="BP"/>
    <tag k="brand" v="BP"/>
    <tag k="brand:wikidata" v="Q152057"/>
    <tag k="brand:wikidata" v="Q152057"/>
    <tag k="brand:wikipedia" v="en:BP"/>
    <tag k="brand:wikipedia" v="en:BP"/>
    <tag k="fuel:diesel" v="yes"/>
    <tag k="fuel:diesel" v="yes"/>
    <tag k="fuel:octane_100" v="yes"/>
    <tag k="fuel:octane_100" v="yes"/>
    <tag k="fuel:octane_95" v="yes"/>
    <tag k="fuel:octane_95" v="yes"/>
    <tag k="name" v="BP"/>
    <tag k="name" v="BP"/>
    <tag k="operator" v="BP"/>
    <tag k="operator" v="ΚΑΛΥΨΩ ΜΟΝ. Ε.Π.Ε. Νο 72"/>
    <tag k="payment:hellenic_fuels_SA" v="yes"/>
    <tag k="payment:hellenic_fuels_SA" v="yes"/>
    <tag k="type" v="multipolygon"/>
    <tag k="type" v="multipolygon"/>
  </area>
```

By the way, I would consider area...(area) undefined / unspecified behavior, and would propose the following alternative:

```C
area["ISO3166-1"="AD"];
wr[amenity="fuel"](area);
out center meta;
```

**Comment by drolbr** [comment]
Recreating area 3602660789 on the public instances has fixed the issue for that area.

Have you any particular reason why this should affect only version 0.7.58, or do we simply never have observed it before? Is there a setup to reproduce the issue on area creation?

**Comment by mmd-osm** [comment]
That's a good question. I can only offer a few data points for a number of public instances:

Test query:

```C
area["ISO3166-1"="IT"];
out;
```

* lz4.overpass-api.de (Overpass API 0.7.58.3) --> duplicated keys
* z.overpass-api.de (Overpass API 0.7.58.3) --> duplicated keys
* maps.mail.ru/osm/tools/overpass/ (Overpass API 0.7.57.1) --> result ok
* overpass.kumi.systems/api/ (Overpass API 0.7.57.1) --> result ok
 /overpass.openstreetmap.ru/cgi/ (Overpass API 0.7.57.1) --> result ok

**Comment by mmd-osm** [comment]
By the way, I think there's another prepare_tags function in tags_updater.h, that looks like another incarnation of the same dead code.
