### ISSUE TITLE
Scientific notation in export causes invalid GPX export

### ISSUE THREAD

**Issue by BitScout** [drolbr/Overpass-API#678]
When exporting the borders of France as GPX, one coordinate was so close to the 0th meridian that it was output in scientific notation.

My query:

```
[out:json];

area["name"="France"]->.country;
rel["name"="France"]["type"="boundary"]["admin_level"="2"];
(
way(r)["maritime" != "yes"]({{bbox}});
way(area.country)["natural"="coastline"]({{bbox}});
);

out body;
>;
out skel qt;
```

Relevant part of the export:

```
<trkpt lat="49.3267136" lon="0.0005797"/>
<trkpt lat="49.3264086" lon="-2e-7"/>
<trkpt lat="49.3261744" lon="-0.0005312"/>
```

Also see this thread: https://github.com/tyrasd/overpass-turbo/issues/588#issuecomment-1272307488

**Comment by mmd-osm** [comment]
As discussed, please close this one. The issue is with overpass turbo, NOT with Overpass API.

**Comment by BitScout** [comment]
Alright, I'm completely confused. I'll just close this, step back and let you do your thing.
