### ISSUE TITLE
Reclaim used space

### ISSUE THREAD

**Issue by boldtrn** [drolbr/Overpass-API#679]
I am hosting an Overpass instance. Lately I am running out of space. There are huge .log files.

For example:
```
39G	transactions.log
6.3G	changes.log
```

Can these files be deleted safely?

**Comment by drolbr** [comment]
> 39G	transactions.log

Yes, this can be deleted. Personally, I use a cronjob to rotate the file, and finally try to discover odd patterns on the public instance. But on a working private instance, there is probably no reason to keep the file.

> 6.3G	changes.log

There is no such file on the public instances, and such a filename is even not contained in the source code.

**Comment by boldtrn** [comment]
Thank you very much for clarifying. The `changes.log` seems to be generated by Docker image: https://github.com/wiktorn/Overpass-API/blob/a67f35ffa01233aa8de57e189c8c012dbbd580f0/bin/update_overpass.sh#L82

I removed both files.
