### ISSUE TITLE
Areas around south pole

### ISSUE THREAD

**Issue by drolbr** [drolbr/Overpass-API#68]
Currently, areas created from relations or ways that are intended to cover the south pole do cover in fact the opposite part of the globe, i.e. almost the entire globe.

Fix the software such that areas covering most of the world are recognized and inverted. Thus, those areas would cover the south pole instead of large parts of the globe.

**Comment by sanderd17** [comment]
I honestly don't consider this to be an issue with Overpass, but rather an issue with the OSM definitions of an "area". Closed ways representing an area have no direction, and relations contain "outer" and "inner" roles, which make sense on a rectangle, but not on a globe.

The only solution for users I could think of, is enabling them to negate the area.

**Comment by drolbr** [comment]
Fixed in c013547bc680c320ca3e537660effa4c67c0cab1

**Comment by tyrasd** [comment]
It's actually fixed in commit c4b6ff68830dd9f307493fc037d4dba852282457, I believe. :)
