### ISSUE TITLE
Overpass API Server blocked our IP

### ISSUE THREAD

**Issue by rbsdc** [drolbr/Overpass-API#681]
@drolbr I am currently working on the Water Fountains project (https://github.com/water-fountains) and noticed that the main Overpass API server seems to block our IP (https://www.water-fountains.org, 185.166.99.100). Is this the case and if yes, what are the reasons? We use the npm query-overpass library (https://www.npmjs.com/package/query-overpass). If I switch to the alternative server https://lz4.overpass-api.de/api/interpreter it is working again.

**Comment by rbsdc** [comment]
Thank you for the info. The query-pass library I mentioned uses the instance at https://z.overpass-api.de/api/interpreter (178.63.11.215) by default. This is the one that is not working for us anymore.

**Comment by mmd-osm** [comment]
If you keep sending requests to the same server over some longer period of time, you would automatically be rate limied. Either switch to another server in that case, or take a pause before sending further requests.

**Comment by rbsdc** [comment]
I saw the rate limits at https://wiki.openstreetmap.org/wiki/Overpass_API, but I assumed we never reached the rate limit of 10000 requests/5GB/day - however, I will double check first - thank you again!

**Comment by mmd-osm** [comment]
Yes, the information in the wiki is outdated and needs updating.

**Comment by drolbr** [comment]
According to the logs, there have been at least accesses to z.overpass-api.de since 2022-12-01. There are accesses to lz4.overpass-api.de, but most of them succeed. The [details of the rate limiting](https://dev.overpass-api.de/overpass-doc/en/preface/commons.html).

**Comment by drolbr** [comment]
I strongly suggest to set a proper user agent and/or provide your project's URL as referrer.

**Comment by matkoniecz** [comment]
> Yes, the information in the wiki is outdated and needs updating.

What would be the correct info?
