### ISSUE TITLE
Unexpected id: query behavior

### ISSUE THREAD

**Issue by Zaczero** [drolbr/Overpass-API#683]
Context:

* `1144246456` - valid way id - https://overpass-turbo.eu/s/1ruv
* `4892888216` - valid node id - https://overpass-turbo.eu/s/1rux

Now the funny part begins:

### nw(id:1144246456,4892888216) returns just the node

https://overpass-turbo.eu/s/1ruz

### way(id:1144246456,4892888216) returns nothing

https://overpass-turbo.eu/s/1ruB

### way(id:4892888216) returns corrupted? data

https://overpass-turbo.eu/s/1ruD

![image](https://user-images.githubusercontent.com/10835147/219844448-8d82dad0-8de7-40a4-aef0-5bc58dc26a9f.png)

---

I did test it over multiple instances and they all share the similar behavior.

**Comment by drolbr** [comment]
Thank you for reporting the issue. I con confirm the problem.

**Comment by drolbr** [comment]
Fixed in 7cc7a2b6ea318cf7545435fd4bc8b456cc7f7d83

**Comment by Zaczero** [comment]
Fixed, Thanks !!

**Comment by mmd-osm** [comment]
By the way, I never quite understood why combinations of different object types are permitted in the first place. After all, objects ids for nodes, ways and relations don't share a common number sequence. Filters like `nw(id:1144246456,4892888216) ` don't make much sense to me. I would simply reject them.

**Comment by Zaczero** [comment]
I think it's just for convenience reasons. I quite like it.
