### ISSUE TITLE
Support ChatGPT Plugins via .well-known/ai-plugin.json

### ISSUE THREAD

**Issue by stefangrotz** [drolbr/Overpass-API#685]
ChatGPT is right now starting to roll out a new Plugin system that allows it to access information from external APIs.

Here are the details:
* https://platform.openai.com/docs/plugins/introduction
* https://platform.openai.com/docs/plugins/getting-started

You basically have to create the file
`yourdomain.com/.well-known/ai-plugin.json`
Where you describe your API in human language.

Do you think having an official OSM Overpass plugin for ChatGPT would be nice? It could increase the load on the API, but it also could make searches a lot easier.

**Comment by drolbr** [comment]
I'm always happy to read from new ideas.

I'm also not worried of more requests. The public instances just have moved to bigger servers and have plenty of capacity.

However, ChatGPT is non-free software, and I'm unwilling to contribute to someone else's bottom line without getting anything back.

Some people [have played](https://community.openstreetmap.org/t/improving-overpass-user-experience-thanks-to-ai/97104/1) with ChatGPT and Overpass API. I suggest to move further efforts towards that thread. If the plugins intent is to advertise Overpass API then the thread there is well-indexed by search engines. If the intent is to facilitate Overpass API usage then again collecting insight there makes it easier to see what makes sense for connecting the two things.
