### ISSUE TITLE
Missing _frequent_ files in download_clone.sh?

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#689]
Since 2023-04-18, the clone directory contains a few new files for frequent nodes, ways and relations (+attic).
However, I don't see any of these new files included in the 0.7.60 download_clone.sh script.
This seems like a bug to me.

A hint for clone users: version 0.7.60 is mandatory at this point in time, clone files don't seem to work with older versions anymore due to a file format change. Error message would be something like "way_tags_global.bin.idx File_Blocks_Index: Unsupported index file format version".

**Comment by drolbr** [comment]
Fixed in 27586862e10eeeb2b1cd4d7574a3c701367d44d9
