### ISSUE TITLE
"Template not found." for ambiguous Permanent ID links

### ISSUE THREAD

**Issue by nrenner** [drolbr/Overpass-API#69]
e.g. for http://overpass-api.de/api/interpreter?data=[out%3Acustom]%3Bnode[place][name%3D%22Bonn%22]%3Bout%3B

Background: I wanted to mention [Permanent ID](http://wiki.openstreetmap.org/wiki/Overpass_API/Permanent_ID)s in a current [discussion](http://forum.openstreetmap.org/viewtopic.php?pid=389816), but some of the example links are broken, probably because the default.wiki Template for the disambiguation page is missing?

**Comment by JesseWeinstein** [comment]
On the production servers, this appears to (still) be a problem. As such, I've opened a new ticket for it, here: #597
