### ISSUE TITLE
Zero-length attic and changelog files in db when running with --meta

### ISSUE THREAD

**Issue by b1tw153** [drolbr/Overpass-API#691]
I just upgraded from v0.7.59.1 to v0.7.60.2 and now even though I'm using the --meta flag to start the osm-base dispatcher, it is creating zero-length attic and changelog files in the db directory. Then when I try to restart the dispatcher, it finds these files and refuses to run without the --attic flag.

My installation doesn't need attic data. The db clone doesn't have it, and I don't intend to use it.

The config was working fine under v0.7.59.1. Did something change in v0.7.60.2 that is causing it to create the zero-length attic and changelog files? And is there a way to fix that?

**Comment by drolbr** [comment]
Yes, there are at changes in the way the dispatcher handles files. I suspect that this somehow comes from the migration script. Could you please send an `ls -l` such that I can see which files exactly have been accidentally created?
