### ISSUE TITLE
SSL certificate for overpass-api.de is expired

### ISSUE THREAD

**Issue by pedrocamargo** [drolbr/Overpass-API#694]
As per the title.

Stack trace below.

--2023-05-29 07:41:05--  https://dev.overpass-api.de/clone//2023-05-25/replicate_id
Resolving dev.overpass-api.de (dev.overpass-api.de)... 95.217.37.171, 2a01:4f9:2b:2fd4::2
Connecting to dev.overpass-api.de (dev.overpass-api.de)|95.217.37.171|:443... connected.
ERROR: The certificate of 'dev.overpass-api.de' is not trusted.
ERROR: The certificate of 'dev.overpass-api.de' has expired.

**Comment by pedrocamargo** [comment]
Also reported here: https://github.com/openstreetmap/operations/issues/887

Not sure exactly where was the best place to do it... :-|

**Comment by mmd-osm** [comment]
I added some comments here: https://github.com/openstreetmap/operations/issues/887#issuecomment-1567376665

**Comment by mmd-osm** [comment]
I believe the issue has been resolved in the meantime...

**Comment by pedrocamargo** [comment]
It is fixed indeed
