### ISSUE TITLE
way_cnt and closed ways

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#697]
According to the wiki page: _The way_cnt criterion selects those nodes that are members of a given number of ways. E.g. the criterion (way_cnt:2) selects all crossings between ways and all nodes where two ways join._ 

I tested this using closed ways (building), and results look a bit unexpected.

This is what the query returns:

![image](https://github.com/drolbr/Overpass-API/assets/5842757/4bbcf90a-c156-45f5-bf4b-41b3d87a08f2)

I would expect the following result according to the Wiki description:

Note that the result doesn't contain closed ways where the front and back node belong to the same way.

![image](https://github.com/drolbr/Overpass-API/assets/5842757/4f11a34d-4439-4a03-9e99-2c240fe96af3)

Query:

```
[bbox:51.3424588108006,6.277366876602173,51.345114369370336,6.2813955545425415];
way[building];
node(way_cnt:2);
out;
```

I believe every node belonging to the same way may only be counted once, i.e. we need to calculate the list of distinct node ids for each way: https://github.com/mmd-osm/Overpass-API/commit/fd23189f055aa3f062b138013546d09d531571f9

**Comment by drolbr** [comment]
Thank you for reporting the issue. Fixed in b40422fd8d2f6fa6753a734e4b69455d33979a92
