### ISSUE TITLE
Missing data in query

### ISSUE THREAD

**Issue by woheller69** [drolbr/Overpass-API#701]
My Android app LavSeeker (https://f-droid.org/packages/org.woheller69.lavatories/) uses Overpass-API to find toilets (amanity=toilets) around a location.

I noticed, that not all toilets which are in OpenStreetMap and which are also found in OSMAND are listed.

E.g.
http://overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%5Btimeout%3A2%5D%3B%28node%5B%22amenity%22%3D%22toilets%22%5D%28around%3A5000%2C48%2E18%2C11%2E76%29%3B%29%3Bout%3B%3E%3Bout%20skel%20qt%3B%0A

does not list e.g.
https://www.openstreetmap.org/node/476031846

and

https://www.openstreetmap.org/way/168148603

They are tagged as amenity toilets. Any ideas?

**Comment by mmd-osm** [comment]
* https://www.openstreetmap.org/node/476031846 does not have any tags.  -> https://www.openstreetmap.org/api/0.6/node/476031846
* https://www.openstreetmap.org/way/168148603 is a way. However, in your query you're only looking for nodes.

I would really recommend to check our the  Help and Support section in the OSM Community Forum: https://community.openstreetmap.org/c/help-and-support/7/none  - That's a great place for such howto questions.

Also I can only recommend to try your queries in https://overpass-turbo.eu first, before integrating them in your own application.

**Comment by woheller69** [comment]
ok, so it is a bug on the map.
Then I will not waste time on it

**Comment by mmd-osm** [comment]
No, it's not a bug on the map, your query is simply not requesting the right information. Please follow up on the OSM community forum as mentioned, otherwise your app users will consistently see incomplete data.

**Comment by woheller69** [comment]
will not support toilets in ways.
The tags should be added to the node

**Comment by mmd-osm** [comment]
This is getting quickly off topic for this repo. https://taginfo.openstreetmap.org/tags/amenity=toilets#overview would tell you that over 100.000 restrooms are tagged as ways...

**Comment by woheller69** [comment]
According to https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets

toilets should be tagged as nodes: "Place a node centrally at the location of the toilet amenities and tag it [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=toilets."

**Comment by mmd-osm** [comment]
Your quote is immediately followed by "Alternatively draw an [area](https://wiki.openstreetmap.org/wiki/Area) over the toilet area and tag it with [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=toilets,"

End of discussion for me.

**Comment by woheller69** [comment]
Thanks. My app will find toilets also in ways in future
