### ISSUE TITLE
Make copyright notice customizable

### ISSUE THREAD

**Issue by 1ec5** [drolbr/Overpass-API#721]
The output formats always prepend a copyright notice that refers to www.openstreetmap.org and the ODbL. This is expected for any data that actually comes from OSM, but the Overpass API can also be configured for other projects that use the OSM software stack without OSM data per se. For example, OpenHistoricalMap is located at www.openhistoricalmap.org and subject to a CC0 public domain dedication. [OpenGeofiction](https://overpass.ogf.rent-a-planet.com/) is located at www.opengeofiction.net and under a nonfree Creative Commons license.

Ideally there would be a way to customize this message without having to fork the project. I understand that you wouldn’t want to make it too easy to remove attribution on OSM data. However, it probably isn’t in OSM’s interest that third parties are currently attributing non-OSM data to OSM using an OSMF trademark, while omitting their own attribution.

https://github.com/drolbr/Overpass-API/blob/a0db4f392f744d5e1304331edbf542ef6d6ce2fa/src/overpass_api/frontend/basic_formats.cc#L64-L65 https://github.com/drolbr/Overpass-API/blob/a0db4f392f744d5e1304331edbf542ef6d6ce2fa/src/overpass_api/output_formats/output_json.cc#L46-L47 https://github.com/drolbr/Overpass-API/blob/a0db4f392f744d5e1304331edbf542ef6d6ce2fa/src/overpass_api/output_formats/output_xml.cc#L38-L39

/ref OpenHistoricalMap/issues#558

**Comment by drolbr** [comment]
Thank you for pointing me to this problem for reuse.

A solution has been implemented in 1723591d6f3abb5d57bf9e57cd8a10e59c49f5f5 :
just place a file `copyright_notice` in the database directory and the first line of that file is printed as the copyright notice.

The feature will come live with the next version, 0.7.63.
