### ISSUE TITLE
JOSM automatic fix break geocode

### ISSUE THREAD

**Issue by ivanbranco** [drolbr/Overpass-API#725]
If I write a query with `{{geocodeArea:South Carolina}}->.searchArea;`
and then I click "Export" and then "JOSM", and then I allow Overpass to automatically fix the query for the export, the geocode becames:
`{{geocodeArea:Sout metah Carolina}}->.searchArea;/*fixed by auto repair*/`
changing "South" to "Sout metah"

**Comment by mmd-osm** [comment]
Anything that looks like `{{ ... }}` are overpass turbo specific extensions, which are not understood by Overpass API.
This means, you need to report your issue over at https://github.com/tyrasd/overpass-turbo/issues
It's really off topic for this repo.

**Comment by ivanbranco** [comment]
ops
