### ISSUE TITLE
Query doesn't return the complete data ,data is missing

### ISSUE THREAD

**Issue by MALKARAJ** [drolbr/Overpass-API#735]
Hi Team,
Some of the data are not returning via query. Even though the data has been present in the OpenStreetMap

`[out:json][timeout:5000];
rel(571771);
map_to_area->.searchArea;
relation["boundary"="administrative"]["ISO3166-2"~"^M"](area.searchArea);
out ids tags;`

missing data osm ids are 3825989

kindly provide some hint

**Comment by mmd-osm** [comment]
Duplicate of #702. Same question was also asked in this issue, even mentioning the same relation id 3825989.

**Comment by drolbr** [comment]
@mmd-osm Thank you for pointing to the other issue. Closing this one.
