### ISSUE TITLE
S3 Backup for Faster DB Cloning

### ISSUE THREAD

**Issue by BrendenKingTLG** [drolbr/Overpass-API#738]
Would it be possible to create an S3 backup of the database monthly, or even every few months? The download clone script currently takes about four days for me. Using S3 would be much faster.

**Comment by drolbr** [comment]
I would have to pay for S3, moving money towards a huge vendor lock-in. Even if it happens after some free-trial. This is very unlikely to happen.

However, there is work underway to reduce sizes for cloning, as the total size to transfer definitely caused headache.

**Comment by mmd-osm** [comment]
Maybe also double check your requirements. Do you need full planet coverage? Full history? If not, download some country/region extract and load that into Overpass API instead. Cloning is not a mandatory step after all.

**Comment by BrendenKingTLG** [comment]
@drolbr I get it. Glad to hear there is an effort to reduce the cloning size. 

@mmd-osm I need the full database. I ended up just standing up an EC2 and populating from a bz2.
