### ISSUE TITLE
Areas sometimes contain their defining relation and sometimes not

### ISSUE THREAD

**Issue by jeflem** [drolbr/Overpass-API#739]
Working on a project I noticed that (the public and my private) Overpass API's areas sometimes contain the relation the area has been created from and sometimes not (tested mainly with country borders around islands).

Example:
* [relation 1337126](https://www.openstreetmap.org/relation/1337126) has an equivalent area (see this [overpass-turbo query](https://overpass-turbo.eu/s/1QI5)), but the area does not contain the relation, see this [overpass-turbo query](https://overpass-turbo.eu/s/1QI6).
* but the area for [relation 941530](https://www.openstreetmap.org/relation/941530) contains the relation, see this [overpass-turbo query](https://overpass-turbo.eu/s/1QI7)

If read through all the area creation doc I could find, especially [Overpass API/Areas](https://wiki.openstreetmap.org/wiki/Overpass_API/Areas). But I do not understand the described behavior. Both examples have similar tagging (`name=...`, `admin_level=4`, `boundary=administrative`, `type=boundary`).

Question: Is this intended behaviour? If yes, what's the reason for such behavior?

**Comment by mmd-osm** [comment]
The difference is the admin_centre node in case of relation 941530. It is the only relation member that's considered to be *inside* the area. I think that's intended behavior and related to the way areas are defined for Overpass API.

**Comment by mmd-osm** [comment]
Related discussion in #669

**Comment by jeflem** [comment]
Thanks for this important hint! Now I remember the [wiki page](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_area_(area)) stating
> Relations are found if one of its members is properly inside the area

and
> A way ending on the border and not otherwise crossing the area is not found.

This explains the behavior if we realize that an area's boundary ways do not cross the area.
