### ISSUE TITLE
nodes inside a closed way

### ISSUE THREAD

**Issue by ghost** [drolbr/Overpass-API#77]
Hello,
is it possible to query something inside a closed way?

`node(poly:"50.7 7.1 50.7 7.2 50.75 7.15");`
Goes in the right direction, but the polygon is hard coded. For example: I want to ask for all amenity=bench inside(!) some forrests (landuse).

Best regards, Johannes

**Comment by mmd-osm** [comment]
You can test these queries now by temporarily pointing overpass turbo to a different test server instance: http://dev.overpass-api.de/api_mmd/

Please give it a try...

**Comment by tyrasd** [comment]
Seems to work quite well. Although [this query](http://overpass-turbo.eu/s/859) seems to return quite a few superfluous elements (for example [this one](http://www.openstreetmap.org/way/106875564)). This doesn't happen if one makes the bbox much smaller. The code doesn't consider non-closed ways, does it? Are there any plans/ideas of supporting multipolygons via this mechanism as well? There are quite a lot of MPs out there where the tags are only (or also) tagged on the outer way, which would produce false positives in queries that use this a `closed-way = area` approximation…

**Comment by mmd-osm** [comment]
Thanks for giving this feature a try. I tweaked the query a bit to better identify the original way, which was turned into a polygon: http://overpass-turbo.eu/s/87k

Obviously, for [way 106875564](http://www.openstreetmap.org/way/106875564) the corresponding polygon is derived from [way 279219108](http://www.openstreetmap.org/way/279219108). Currently, non-closed ways are automatically turned into closed ways. This seems to produce quite some strange side effects, so I'll probably have to drop this auto-completion again.

Support for complex MPs is quite limited in this version (see example 2 above for a query based on outer ways of a MP). I'll need to investigate in more detail how area creation is handling this case and if reusing some of the make pivot parts is feasible at all.

**Comment by tyrasd** [comment]
> so I'll probably have to drop this auto-completion again and silently ignore those non-closed ways

I'd suggest that as well, as I'm not aware of any data consuming tool does this kind of autocompletion from an *unclosed* way to an area (except maybe if the way has an `area=yes` tag or so maybe). Also, what about closed ways that are tagged to be *not* areas (`area=no`)?

**Comment by mmd-osm** [comment]
Check: http://gis.stackexchange.com/questions/173174/query-school-elements-using-overpass-turbo

**Comment by HolgerJeromin** [comment]
Just wanted to add that old style multi polygon are being cleaned up. So adding mp handling is much easier to implement than before.

**Comment by mmd-osm** [comment]
New attempt, this time using the original area creation logic:
* http://overpass-turbo.eu/s/FaP

**Comment by rriemann-eu** [comment]
>     * http://overpass-turbo.eu/s/Fbv (buildings without house number on the way, and as node inside building)

The example from @mmd-osm  gives a run-time error currently:

> Error: runtime error: The dispatcher (i.e. the database management system) is turned off. 

Is there any update since January this year?

**Comment by mmd-osm** [comment]
That’s expected. This query runs on a development server, that may be unavailable at any time without prior announcement.

**Comment by mmd-osm** [comment]
The query runs on a development server that may be unavailable from time to time. As long as this feature isn't available on one of the production machines and publicly announced, it is not yet available for general use. Also, there's currently no timeline for this feature.

**Comment by mmd-osm** [comment]
* https://gis.stackexchange.com/questions/356973/overpass-api-query-points-not-inside-polygons/357054

**Comment by tuukka** [comment]
This functionality would be necessary for accessing various building data:
* entrance=* (not always on the building outline)
* building:part=* (a building relation is not obligatory)
* Address nodes (often not on the building outline)
* Amenities within a building (an associated_entrances relation is rare)

It might make sense to handle buildings as a special case, if a generic solution is out of reach for now.

**Comment by mmd-osm** [comment]
This issue can be closed now, solved in 0.7.57: https://dev.overpass-api.de/blog/way_based_areas.html

**Comment by gy-mate** [comment]
@drolbr @ghost _Just a ping that you may close this issue._

**Comment by mmd-osm** [comment]
Ghost is a placeholder for deleted GitHub users, no need to mention them, they would never reply.

**Comment by gy-mate** [comment]
@mmd-osm Oh, thanks, didn't know that! :D I see it now on hover.
