### ISSUE TITLE
Querying landuse metainformation for a lat-lng

### ISSUE THREAD

**Issue by krnlde** [drolbr/Overpass-API#86]
I'm trying to always receive the ground information (landuse, leisure, amenity, natural, ...) of a given coordinate.

```
[out:json];
way(around:50.0, {{center}})->.a;
(
  way.a[amenity];
  way.a[natural];
  way.a[landuse];
  way.a[leisure];
);
out;
is_in({{center}})->.a;
(
  area.a[landuse];
  area.a[leisure];
  area.a[amenity];
  area.a[natural];
);
out;
```

What I was trying to do was to find the enclosing element for a coordinate that has at least one of the tags.

Why is there some areas that won't return a landuse information (e.g. most forests) but can be printed in whatever color and pattern it is by the tile drawer server? How do I always get these metainformation?

**Comment by krnlde** [comment]
Hey guys. Just to awake this issue from a deep slumber: If there is any news other than the mentioned workaround I'd be happy to test and contribute.

**Comment by soshial** [comment]
Same question. I'd love to know if I can load landuse for a specific location/coordinate.

Asked a [question on SO](https://gis.stackexchange.com/questions/323397/overpass-api-around-filter-doesnt-work-with-small-distances). There are a lot of such questions.
