### ISSUE TITLE
Add HTTP error header

### ISSUE THREAD

**Issue by don-vip** [drolbr/Overpass-API#94]
Hi,

We have in JOSM an error handling mechanism for OSM API based on the presence of HTTP header named "Error", which contains the English error message of an erroneous API request.

See http://josm.openstreetmap.de/browser/josm/trunk/src/org/openstreetmap/josm/io/OsmServerReader.java?rev=7082#L172

Could it be possible to add the same HTTP header to errors raised by Overpass API?

It would allow to display error messages directly to JOSM users in a standard way :)

**Comment by mmd-osm** [comment]
@don-vip : no sure if your question is answered or if there's still anything to do here.
If not, could you please close this ticket? Thanks.

**Comment by simon04** [comment]
We implemented a workaround and parse the error from the response HTML, see https://josm.openstreetmap.de/changeset/8782/josm.

**Comment by mmd-osm** [comment]
cool., thanks. I guess @don-vip can now finally close this ticket.

**Comment by don-vip** [comment]
Yeah sure. Thanks Simon :)
